<?php

declare(strict_types=1);

/**
 * Weekly status report helpers (#36404).
 *
 * Renders committed snapshot / streak JSON into Markdown with optional
 * week-over-week deltas. Lives under script/status/ so it does not bump the
 * top-level script/ file-count ratchet (#36403). No GitHub Actions — local-ci-only.
 */

/**
 * @param array<string, mixed> $current
 * @param array<string, mixed>|null $previous
 * @return array<string, array{current:int|string, previous:int|string|null, delta:int|null}>
 */
function status_report_metric_rows(array $current, ?array $previous): array
{
    $keys = [
        'spine' => 'Spine units',
        'inventory' => 'Inventory files',
        'builtins_matrix_rows' => 'Capability matrix rows',
        'builtins_vm_yes' => 'VM yes',
        'builtins_jit_yes' => 'JIT yes',
        'builtins_aot_yes' => 'AOT yes',
        'differential_cases' => 'Differential cases',
        'apps_ready' => 'Apps corpus ready',
        'apps_packages' => 'Apps corpus packages',
        'ci_green_streak_days' => 'Local CI streak (days)',
    ];
    $rows = [];
    foreach ($keys as $key => $label) {
        $cur = $current[$key] ?? null;
        if (!is_int($cur) && !is_float($cur) && !is_string($cur)) {
            continue;
        }
        $prev = null;
        if (is_array($previous) && array_key_exists($key, $previous)) {
            $prev = $previous[$key];
        }
        $delta = null;
        if (is_numeric($cur) && is_numeric($prev)) {
            $delta = (int) $cur - (int) $prev;
        }
        $rows[$label] = [
            'current' => is_numeric($cur) ? (int) $cur : (string) $cur,
            'previous' => is_numeric($prev) ? (int) $prev : (is_null($prev) ? null : (string) $prev),
            'delta' => $delta,
        ];
    }

    return $rows;
}

function status_report_format_delta(?int $delta): string
{
    if (null === $delta) {
        return 'n/a';
    }
    if (0 === $delta) {
        return '0';
    }

    return $delta > 0 ? '+'.$delta : (string) $delta;
}

/**
 * @param list<array{number:int,title:string,labels:list<string>}> $issues
 */
function status_report_render_issue_list(array $issues, int $limit = 20): string
{
    if ($issues === []) {
        return "_None listed (pass `--with-github` when `gh` is available)._\n";
    }
    $out = '';
    $n = 0;
    foreach ($issues as $issue) {
        if ($n >= $limit) {
            $out .= '- … truncated at '.$limit."\n";
            break;
        }
        $labels = $issue['labels'] ?? [];
        $labelStr = $labels === [] ? '' : ' `'.implode('` `', $labels).'`';
        $out .= sprintf(
            "- [#%d](https://github.com/PurHur/php-compiler/issues/%d) %s%s\n",
            (int) $issue['number'],
            (int) $issue['number'],
            (string) $issue['title'],
            $labelStr
        );
        ++$n;
    }

    return $out;
}

/**
 * @param array<string, mixed> $snapshot
 * @param array<string, mixed>|null $previous
 * @param list<array{number:int,title:string,labels:list<string>}> $p0
 * @param list<array{number:int,title:string,labels:list<string>}> $p1
 */
function status_report_render_markdown(
    array $snapshot,
    ?array $previous,
    string $date,
    array $p0,
    array $p1,
    string $tracker = '36379'
): string {
    $generated = (string) ($snapshot['generated_at'] ?? gmdate('Y-m-d\TH:i:s\Z'));
    $sha = (string) ($snapshot['last_green_master_sha'] ?? '');
    $shaShort = $sha !== '' ? substr($sha, 0, 12) : 'n/a';
    $rows = status_report_metric_rows($snapshot, $previous);

    $md = "# php-compiler weekly status — {$date}\n\n";
    $md .= "Generated by `script/status/report.php` (#36404) at `{$generated}`.\n\n";
    $md .= "Parent tracker: [#{$tracker}](https://github.com/PurHur/php-compiler/issues/{$tracker}).\n\n";
    $md .= "Last local-green tip: `{$shaShort}` · CI streak **".(int) ($snapshot['ci_green_streak_days'] ?? 0)."** days.\n\n";
    $md .= "## Metrics\n\n";
    $md .= "| Metric | This week | Prior | Δ |\n";
    $md .= "|---|---:|---:|---:|\n";
    foreach ($rows as $label => $row) {
        $prev = $row['previous'];
        $prevCell = null === $prev ? '—' : (string) $prev;
        $md .= sprintf(
            "| %s | %s | %s | %s |\n",
            $label,
            (string) $row['current'],
            $prevCell,
            status_report_format_delta($row['delta'])
        );
    }
    $md .= "\nNumbers come from committed `docs/status-snapshot.json` / `docs/ci-streak.json` only.\n";
    $md .= "Gate pass/fail is **not** stamped — run `make north-star5-verify-fast` locally.\n\n";
    $md .= "## Open P0 / release-blocker\n\n";
    $md .= status_report_render_issue_list($p0);
    $md .= "\n## Open IMPORTANT / P1 highlights\n\n";
    $md .= status_report_render_issue_list($p1);
    $md .= "\n## How to refresh\n\n";
    $md .= "```bash\n";
    $md .= "php script/status/snapshot.php --json-only   # refresh snapshot artifacts\n";
    $md .= "make status-report                           # write docs/pages/status/<date>.md + latest.md\n";
    $md .= "make status-report ARGS='--with-github'      # also list open P0/P1 via gh\n";
    $md .= "```\n\n";
    $md .= "No GitHub Actions workflow — this repo is local-CI-only (#394 / local-ci-only).\n";
    $md .= "Schedule `make status-report` on the maintainer box (e.g. Monday 06:00 UTC cron).\n";

    return $md;
}

/**
 * Load the most recent prior dated report's embedded snapshot metrics, if any.
 *
 * Prior reports store a JSON fence after the Metrics table for machine deltas:
 * `<!-- status-report-metrics: {...} -->`
 *
 * @return array<string, mixed>|null
 */
function status_report_load_previous_metrics(string $statusDir, string $skipDate): ?array
{
    if (!is_dir($statusDir)) {
        return null;
    }
    $files = glob($statusDir.'/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9].md') ?: [];
    rsort($files, SORT_STRING);
    foreach ($files as $path) {
        $base = basename($path, '.md');
        if ($base === $skipDate) {
            continue;
        }
        $body = (string) file_get_contents($path);
        if (preg_match('/<!-- status-report-metrics:(\{.*?\}) -->/s', $body, $m)) {
            $decoded = json_decode($m[1], true);
            if (is_array($decoded)) {
                return $decoded;
            }
        }
    }

    return null;
}

/**
 * @param array<string, mixed> $snapshot
 */
function status_report_metrics_comment(array $snapshot): string
{
    $keys = [
        'spine',
        'inventory',
        'builtins_matrix_rows',
        'builtins_vm_yes',
        'builtins_jit_yes',
        'builtins_aot_yes',
        'differential_cases',
        'apps_ready',
        'apps_packages',
        'ci_green_streak_days',
    ];
    $payload = [];
    foreach ($keys as $key) {
        if (isset($snapshot[$key]) && is_numeric($snapshot[$key])) {
            $payload[$key] = (int) $snapshot[$key];
        }
    }

    return '<!-- status-report-metrics:'.json_encode($payload, JSON_UNESCAPED_SLASHES).' -->';
}

/**
 * @return list<array{number:int,title:string,labels:list<string>}>
 */
function status_report_fetch_github_issues(string $labelQuery, int $limit = 30): array
{
    if (!status_report_gh_available()) {
        return [];
    }
    $cmd = 'gh issue list --repo PurHur/php-compiler --state open --limit '
        .escapeshellarg((string) $limit)
        .' --search '.escapeshellarg($labelQuery)
        .' --json number,title,labels 2>/dev/null';
    $raw = shell_exec($cmd);
    if (!is_string($raw) || $raw === '') {
        return [];
    }
    $decoded = json_decode($raw, true);
    if (!is_array($decoded)) {
        return [];
    }
    $out = [];
    foreach ($decoded as $row) {
        if (!is_array($row) || !isset($row['number'], $row['title'])) {
            continue;
        }
        $labels = [];
        foreach ($row['labels'] ?? [] as $lab) {
            if (is_array($lab) && isset($lab['name'])) {
                $labels[] = (string) $lab['name'];
            } elseif (is_string($lab)) {
                $labels[] = $lab;
            }
        }
        $out[] = [
            'number' => (int) $row['number'],
            'title' => (string) $row['title'],
            'labels' => $labels,
        ];
    }

    return $out;
}

function status_report_gh_available(): bool
{
    $path = shell_exec('command -v gh 2>/dev/null');

    return is_string($path) && trim($path) !== '';
}
