<?php

declare(strict_types=1);

namespace PHPCompiler\ext\tokenizer;

/**
 * Tokenizer T_* id tables (php-src ext/tokenizer/tokenizer_data.c; #7254, #4561).
 *
 * Base (reference/8.2) tables are regenerated by script/generate-token-constants.php.
 * PHP 8.4+ forward-profile ids (T_*_SET / T_PROPERTY_C + shifts) are derived here (#28130).
 */
final class TokenConstantsData
{
    /** @return array<string, int> */
    public static function nameToId(): array
    {
        $base = self::nameToIdBase();
        if (!self::usePhp84TokenIds()) {
            return $base;
        }

        return self::applyPhp84NameToId($base);
    }

    /** @return array<int, string> */
    public static function idToName(): array
    {
        if (!self::usePhp84TokenIds()) {
            return self::idToNameBase();
        }

        $nameToId = self::applyPhp84NameToId(self::nameToIdBase());
        $idToName = [];
        foreach ($nameToId as $name => $id) {
            if ('TOKEN_PARSE' === $name || 'T_PAAMAYIM_NEKUDOTAYIM' === $name) {
                continue;
            }
            if (!isset($idToName[$id])) {
                $idToName[$id] = $name;
            }
        }
        \ksort($idToName);

        return $idToName;
    }

    /** PHP 8.4 tokenizer surface: T_*_SET + T_PROPERTY_C and shifted ids (#28130). */
    private static function usePhp84TokenIds(): bool
    {
        return \version_compare(\PHPCompiler\CompilerVersion::languageProfileVersion(), '8.4.0', '>=');
    }

    /**
     * @param array<string, int> $base
     *
     * @return array<string, int>
     */
    private static function applyPhp84NameToId(array $base): array
    {
        $nameToId = $base;
        foreach ($nameToId as $name => $id) {
            if ($id >= 327) {
                $nameToId[$name] = $id + 3;
            }
        }
        $nameToId['T_PRIVATE_SET'] = 327;
        $nameToId['T_PROTECTED_SET'] = 328;
        $nameToId['T_PUBLIC_SET'] = 329;

        foreach ($nameToId as $name => $id) {
            if ($id >= 353 && !\in_array($name, ['T_PRIVATE_SET', 'T_PROTECTED_SET', 'T_PUBLIC_SET'], true)) {
                $nameToId[$name] = $id + 1;
            }
        }
        $nameToId['T_PROPERTY_C'] = 353;
        \ksort($nameToId);

        return $nameToId;
    }

    /** @return array<string, int> */
    public static function nameToIdBase(): array
    {
        return [
            'TOKEN_PARSE' => 1,
            'T_ABSTRACT' => 322,
            'T_AMPERSAND_FOLLOWED_BY_VAR_OR_VARARG' => 403,
            'T_AMPERSAND_NOT_FOLLOWED_BY_VAR_OR_VARARG' => 404,
            'T_AND_EQUAL' => 358,
            'T_ARRAY' => 341,
            'T_ARRAY_CAST' => 380,
            'T_AS' => 301,
            'T_ATTRIBUTE' => 351,
            'T_BAD_CHARACTER' => 405,
            'T_BOOLEAN_AND' => 365,
            'T_BOOLEAN_OR' => 364,
            'T_BOOL_CAST' => 382,
            'T_BREAK' => 307,
            'T_CALLABLE' => 342,
            'T_CASE' => 304,
            'T_CATCH' => 315,
            'T_CLASS' => 333,
            'T_CLASS_C' => 346,
            'T_CLONE' => 285,
            'T_CLOSE_TAG' => 391,
            'T_COALESCE' => 400,
            'T_COALESCE_EQUAL' => 363,
            'T_COMMENT' => 387,
            'T_CONCAT_EQUAL' => 356,
            'T_CONST' => 312,
            'T_CONSTANT_ENCAPSED_STRING' => 269,
            'T_CONTINUE' => 308,
            'T_CURLY_OPEN' => 396,
            'T_DEC' => 376,
            'T_DECLARE' => 299,
            'T_DEFAULT' => 305,
            'T_DIR' => 345,
            'T_DIV_EQUAL' => 355,
            'T_DNUMBER' => 261,
            'T_DO' => 292,
            'T_DOC_COMMENT' => 388,
            'T_DOLLAR_OPEN_CURLY_BRACES' => 395,
            'T_DOUBLE_ARROW' => 386,
            'T_DOUBLE_CAST' => 378,
            'T_DOUBLE_COLON' => 397,
            'T_ECHO' => 291,
            'T_ELLIPSIS' => 399,
            'T_ELSE' => 289,
            'T_ELSEIF' => 288,
            'T_EMPTY' => 331,
            'T_ENCAPSED_AND_WHITESPACE' => 268,
            'T_ENDDECLARE' => 300,
            'T_ENDFOR' => 296,
            'T_ENDFOREACH' => 298,
            'T_ENDIF' => 290,
            'T_ENDSWITCH' => 303,
            'T_ENDWHILE' => 294,
            'T_END_HEREDOC' => 394,
            'T_ENUM' => 336,
            'T_EVAL' => 274,
            'T_EXIT' => 286,
            'T_EXTENDS' => 337,
            'T_FILE' => 344,
            'T_FINAL' => 323,
            'T_FINALLY' => 316,
            'T_FN' => 311,
            'T_FOR' => 295,
            'T_FOREACH' => 297,
            'T_FUNCTION' => 310,
            'T_FUNC_C' => 349,
            'T_GLOBAL' => 320,
            'T_GOTO' => 309,
            'T_HALT_COMPILER' => 332,
            'T_IF' => 287,
            'T_IMPLEMENTS' => 338,
            'T_INC' => 375,
            'T_INCLUDE' => 272,
            'T_INCLUDE_ONCE' => 273,
            'T_INLINE_HTML' => 267,
            'T_INSTANCEOF' => 283,
            'T_INSTEADOF' => 319,
            'T_INTERFACE' => 335,
            'T_INT_CAST' => 377,
            'T_ISSET' => 330,
            'T_IS_EQUAL' => 366,
            'T_IS_GREATER_OR_EQUAL' => 371,
            'T_IS_IDENTICAL' => 368,
            'T_IS_NOT_EQUAL' => 367,
            'T_IS_NOT_IDENTICAL' => 369,
            'T_IS_SMALLER_OR_EQUAL' => 370,
            'T_LINE' => 343,
            'T_LIST' => 340,
            'T_LNUMBER' => 260,
            'T_LOGICAL_AND' => 279,
            'T_LOGICAL_OR' => 277,
            'T_LOGICAL_XOR' => 278,
            'T_MATCH' => 306,
            'T_METHOD_C' => 348,
            'T_MINUS_EQUAL' => 353,
            'T_MOD_EQUAL' => 357,
            'T_MUL_EQUAL' => 354,
            'T_NAMESPACE' => 339,
            'T_NAME_FULLY_QUALIFIED' => 263,
            'T_NAME_QUALIFIED' => 265,
            'T_NAME_RELATIVE' => 264,
            'T_NEW' => 284,
            'T_NS_C' => 350,
            'T_NS_SEPARATOR' => 398,
            'T_NULLSAFE_OBJECT_OPERATOR' => 385,
            'T_NUM_STRING' => 271,
            'T_OBJECT_CAST' => 381,
            'T_OBJECT_OPERATOR' => 384,
            'T_OPEN_TAG' => 389,
            'T_OPEN_TAG_WITH_ECHO' => 390,
            'T_OR_EQUAL' => 359,
            'T_PAAMAYIM_NEKUDOTAYIM' => 397,
            'T_PLUS_EQUAL' => 352,
            'T_POW' => 401,
            'T_POW_EQUAL' => 402,
            'T_PRINT' => 280,
            'T_PRIVATE' => 324,
            'T_PROTECTED' => 325,
            'T_PUBLIC' => 326,
            'T_READONLY' => 327,
            'T_REQUIRE' => 275,
            'T_REQUIRE_ONCE' => 276,
            'T_RETURN' => 313,
            'T_SL' => 373,
            'T_SL_EQUAL' => 361,
            'T_SPACESHIP' => 372,
            'T_SR' => 374,
            'T_SR_EQUAL' => 362,
            'T_START_HEREDOC' => 393,
            'T_STATIC' => 321,
            'T_STRING' => 262,
            'T_STRING_CAST' => 379,
            'T_STRING_VARNAME' => 270,
            'T_SWITCH' => 302,
            'T_THROW' => 317,
            'T_TRAIT' => 334,
            'T_TRAIT_C' => 347,
            'T_TRY' => 314,
            'T_UNSET' => 329,
            'T_UNSET_CAST' => 383,
            'T_USE' => 318,
            'T_VAR' => 328,
            'T_VARIABLE' => 266,
            'T_WHILE' => 293,
            'T_WHITESPACE' => 392,
            'T_XOR_EQUAL' => 360,
            'T_YIELD' => 281,
            'T_YIELD_FROM' => 282,
        ];
    }

    /** @return array<int, string> */
    public static function idToNameBase(): array
    {
        return [
            260 => 'T_LNUMBER',
            261 => 'T_DNUMBER',
            262 => 'T_STRING',
            263 => 'T_NAME_FULLY_QUALIFIED',
            264 => 'T_NAME_RELATIVE',
            265 => 'T_NAME_QUALIFIED',
            266 => 'T_VARIABLE',
            267 => 'T_INLINE_HTML',
            268 => 'T_ENCAPSED_AND_WHITESPACE',
            269 => 'T_CONSTANT_ENCAPSED_STRING',
            270 => 'T_STRING_VARNAME',
            271 => 'T_NUM_STRING',
            272 => 'T_INCLUDE',
            273 => 'T_INCLUDE_ONCE',
            274 => 'T_EVAL',
            275 => 'T_REQUIRE',
            276 => 'T_REQUIRE_ONCE',
            277 => 'T_LOGICAL_OR',
            278 => 'T_LOGICAL_XOR',
            279 => 'T_LOGICAL_AND',
            280 => 'T_PRINT',
            281 => 'T_YIELD',
            282 => 'T_YIELD_FROM',
            283 => 'T_INSTANCEOF',
            284 => 'T_NEW',
            285 => 'T_CLONE',
            286 => 'T_EXIT',
            287 => 'T_IF',
            288 => 'T_ELSEIF',
            289 => 'T_ELSE',
            290 => 'T_ENDIF',
            291 => 'T_ECHO',
            292 => 'T_DO',
            293 => 'T_WHILE',
            294 => 'T_ENDWHILE',
            295 => 'T_FOR',
            296 => 'T_ENDFOR',
            297 => 'T_FOREACH',
            298 => 'T_ENDFOREACH',
            299 => 'T_DECLARE',
            300 => 'T_ENDDECLARE',
            301 => 'T_AS',
            302 => 'T_SWITCH',
            303 => 'T_ENDSWITCH',
            304 => 'T_CASE',
            305 => 'T_DEFAULT',
            306 => 'T_MATCH',
            307 => 'T_BREAK',
            308 => 'T_CONTINUE',
            309 => 'T_GOTO',
            310 => 'T_FUNCTION',
            311 => 'T_FN',
            312 => 'T_CONST',
            313 => 'T_RETURN',
            314 => 'T_TRY',
            315 => 'T_CATCH',
            316 => 'T_FINALLY',
            317 => 'T_THROW',
            318 => 'T_USE',
            319 => 'T_INSTEADOF',
            320 => 'T_GLOBAL',
            321 => 'T_STATIC',
            322 => 'T_ABSTRACT',
            323 => 'T_FINAL',
            324 => 'T_PRIVATE',
            325 => 'T_PROTECTED',
            326 => 'T_PUBLIC',
            327 => 'T_READONLY',
            328 => 'T_VAR',
            329 => 'T_UNSET',
            330 => 'T_ISSET',
            331 => 'T_EMPTY',
            332 => 'T_HALT_COMPILER',
            333 => 'T_CLASS',
            334 => 'T_TRAIT',
            335 => 'T_INTERFACE',
            336 => 'T_ENUM',
            337 => 'T_EXTENDS',
            338 => 'T_IMPLEMENTS',
            339 => 'T_NAMESPACE',
            340 => 'T_LIST',
            341 => 'T_ARRAY',
            342 => 'T_CALLABLE',
            343 => 'T_LINE',
            344 => 'T_FILE',
            345 => 'T_DIR',
            346 => 'T_CLASS_C',
            347 => 'T_TRAIT_C',
            348 => 'T_METHOD_C',
            349 => 'T_FUNC_C',
            350 => 'T_NS_C',
            351 => 'T_ATTRIBUTE',
            352 => 'T_PLUS_EQUAL',
            353 => 'T_MINUS_EQUAL',
            354 => 'T_MUL_EQUAL',
            355 => 'T_DIV_EQUAL',
            356 => 'T_CONCAT_EQUAL',
            357 => 'T_MOD_EQUAL',
            358 => 'T_AND_EQUAL',
            359 => 'T_OR_EQUAL',
            360 => 'T_XOR_EQUAL',
            361 => 'T_SL_EQUAL',
            362 => 'T_SR_EQUAL',
            363 => 'T_COALESCE_EQUAL',
            364 => 'T_BOOLEAN_OR',
            365 => 'T_BOOLEAN_AND',
            366 => 'T_IS_EQUAL',
            367 => 'T_IS_NOT_EQUAL',
            368 => 'T_IS_IDENTICAL',
            369 => 'T_IS_NOT_IDENTICAL',
            370 => 'T_IS_SMALLER_OR_EQUAL',
            371 => 'T_IS_GREATER_OR_EQUAL',
            372 => 'T_SPACESHIP',
            373 => 'T_SL',
            374 => 'T_SR',
            375 => 'T_INC',
            376 => 'T_DEC',
            377 => 'T_INT_CAST',
            378 => 'T_DOUBLE_CAST',
            379 => 'T_STRING_CAST',
            380 => 'T_ARRAY_CAST',
            381 => 'T_OBJECT_CAST',
            382 => 'T_BOOL_CAST',
            383 => 'T_UNSET_CAST',
            384 => 'T_OBJECT_OPERATOR',
            385 => 'T_NULLSAFE_OBJECT_OPERATOR',
            386 => 'T_DOUBLE_ARROW',
            387 => 'T_COMMENT',
            388 => 'T_DOC_COMMENT',
            389 => 'T_OPEN_TAG',
            390 => 'T_OPEN_TAG_WITH_ECHO',
            391 => 'T_CLOSE_TAG',
            392 => 'T_WHITESPACE',
            393 => 'T_START_HEREDOC',
            394 => 'T_END_HEREDOC',
            395 => 'T_DOLLAR_OPEN_CURLY_BRACES',
            396 => 'T_CURLY_OPEN',
            397 => 'T_DOUBLE_COLON',
            398 => 'T_NS_SEPARATOR',
            399 => 'T_ELLIPSIS',
            400 => 'T_COALESCE',
            401 => 'T_POW',
            402 => 'T_POW_EQUAL',
            403 => 'T_AMPERSAND_FOLLOWED_BY_VAR_OR_VARARG',
            404 => 'T_AMPERSAND_NOT_FOLLOWED_BY_VAR_OR_VARARG',
            405 => 'T_BAD_CHARACTER',
        ];
    }
}

