<?php

declare(strict_types=1);

/**
 * Program shapes for script/fuzz/gen.php (#36398).
 */

function fuzz_generate_program(int $seed, string $shape = 'auto'): string
{
    $rng = new FuzzRng($seed);
    $shapes = [
        'arith_main',
        'arith_fn',
        'string_concat_loop',
        'array_list',
        'control_break',
        'mixed_scope',
    ];
    if ($shape === 'auto') {
        $shape = $rng->pick($shapes);
    } elseif (!in_array($shape, $shapes, true)) {
        throw new InvalidArgumentException("unknown shape: {$shape}");
    }

    $body = match ($shape) {
        'arith_main' => fuzz_shape_arith_main($rng),
        'arith_fn' => fuzz_shape_arith_fn($rng),
        'string_concat_loop' => fuzz_shape_string_concat_loop($rng),
        'array_list' => fuzz_shape_array_list($rng),
        'control_break' => fuzz_shape_control_break($rng),
        'mixed_scope' => fuzz_shape_mixed_scope($rng),
        default => throw new InvalidArgumentException("unknown shape: {$shape}"),
    };

    $header = "<?php\n\ndeclare(strict_types=1);\n\n"
        ."// @fuzz-seed: {$seed}\n"
        ."// @fuzz-shape: {$shape}\n"
        ."// generated by script/fuzz/gen.php (#36398)\n\n";

    return $header.$body;
}

function fuzz_shape_arith_main(FuzzRng $rng): string
{
    $a = $rng->int(-20, 40);
    $b = $rng->int(1, 17);
    $op = $rng->pick(['+', '-', '*', '%']);
    $lines = [];
    $lines[] = "\$a = {$a};";
    $lines[] = "\$b = {$b};";
    $lines[] = "\$c = \$a {$op} \$b;";
    if ($rng->bool()) {
        $lines[] = '$c = $c + ($a % 3);';
    }
    $lines[] = 'echo $a, " ", $b, " ", $c, "\n";';
    $lines[] = 'var_dump($c);';

    return implode("\n", $lines)."\n";
}

function fuzz_shape_arith_fn(FuzzRng $rng): string
{
    $n = $rng->int(2, 12);
    $typed = $rng->bool(2, 1);
    $sig = $typed ? 'function work(int $n): int' : 'function work($n)';
    $lines = [];
    $lines[] = "{$sig}";
    $lines[] = '{';
    $lines[] = '    $s = 0;';
    $lines[] = '    for ($i = 0; $i < $n; ++$i) {';
    $lines[] = '        $s += ($i % 5) + 1;';
    if ($rng->bool()) {
        $lines[] = '        if ($i === 3) { continue; }';
    }
    $lines[] = '    }';
    $lines[] = '    return $s;';
    $lines[] = '}';
    $lines[] = '';
    $lines[] = "\$r = work({$n});";
    $lines[] = 'echo $r, "\n";';
    $lines[] = 'var_dump($r);';

    return implode("\n", $lines)."\n";
}

function fuzz_shape_string_concat_loop(FuzzRng $rng): string
{
    $n = $rng->int(1, 8);
    $chunk = $rng->pick(['x', 'ab', 'Z', 'qq']);
    $lines = [];
    $lines[] = "\$s = '';";
    $lines[] = "for (\$i = 0; \$i < {$n}; ++\$i) {";
    $lines[] = "    \$s .= '{$chunk}';";
    $lines[] = '}';
    if ($rng->bool()) {
        $lines[] = "\$s .= 't';";
    }
    $lines[] = 'echo $s, "|", strlen($s), "\n";';
    $lines[] = 'var_dump(strlen($s));';

    return implode("\n", $lines)."\n";
}

function fuzz_shape_array_list(FuzzRng $rng): string
{
    $n = $rng->int(2, 6);
    $lines = [];
    $lines[] = '$a = [];';
    $lines[] = "for (\$i = 0; \$i < {$n}; ++\$i) {";
    $lines[] = '    $a[] = $i * 2;';
    $lines[] = '}';
    $lines[] = '$a[] = 99;';
    $lines[] = 'echo count($a), "|", $a[0], "|", $a[count($a) - 1], "\n";';
    $lines[] = 'var_dump(count($a));';

    return implode("\n", $lines)."\n";
}

function fuzz_shape_control_break(FuzzRng $rng): string
{
    $limit = $rng->int(4, 12);
    $stop = $rng->int(1, $limit - 1);
    $lines = [];
    $lines[] = '$s = 0;';
    $lines[] = "for (\$i = 0; \$i < {$limit}; ++\$i) {";
    $lines[] = "    if (\$i === {$stop}) { break; }";
    $lines[] = '    $s += $i;';
    $lines[] = '}';
    $lines[] = 'echo $s, "\n";';
    $lines[] = 'var_dump($s);';

    return implode("\n", $lines)."\n";
}

function fuzz_shape_mixed_scope(FuzzRng $rng): string
{
    $base = $rng->int(1, 9);
    $lines = [];
    $lines[] = 'function bump(int $x): int';
    $lines[] = '{';
    $lines[] = '    return $x + 3;';
    $lines[] = '}';
    $lines[] = '';
    $lines[] = "\$v = {$base};";
    $lines[] = '$v = bump($v);';
    $lines[] = '$v = bump($v);';
    $lines[] = 'echo $v, "\n";';
    $lines[] = 'printf("%d\n", $v);';
    $lines[] = 'var_dump($v);';

    return implode("\n", $lines)."\n";
}
