<?php
// timelib fallbackmap.h — ext/date/lib/fallbackmap.h (offset/isdst → timezone_id)
return [
    ['dst' => 0, 'offset' => -39600, 'timezone_id' => 'Pacific/Apia'],
    ['dst' => 0, 'offset' => -36000, 'timezone_id' => 'Pacific/Honolulu'],
    ['dst' => 0, 'offset' => -32400, 'timezone_id' => 'America/Anchorage'],
    ['dst' => 1, 'offset' => -28800, 'timezone_id' => 'America/Anchorage'],
    ['dst' => 0, 'offset' => -28800, 'timezone_id' => 'America/Los_Angeles'],
    ['dst' => 1, 'offset' => -25200, 'timezone_id' => 'America/Los_Angeles'],
    ['dst' => 0, 'offset' => -25200, 'timezone_id' => 'America/Denver'],
    ['dst' => 1, 'offset' => -21600, 'timezone_id' => 'America/Denver'],
    ['dst' => 0, 'offset' => -21600, 'timezone_id' => 'America/Chicago'],
    ['dst' => 1, 'offset' => -18000, 'timezone_id' => 'America/Chicago'],
    ['dst' => 0, 'offset' => -18000, 'timezone_id' => 'America/New_York'],
    ['dst' => 0, 'offset' => -16200, 'timezone_id' => 'America/Caracas'],
    ['dst' => 1, 'offset' => -14400, 'timezone_id' => 'America/New_York'],
    ['dst' => 0, 'offset' => -14400, 'timezone_id' => 'America/Halifax'],
    ['dst' => 1, 'offset' => -10800, 'timezone_id' => 'America/Halifax'],
    ['dst' => 0, 'offset' => -10800, 'timezone_id' => 'America/Sao_Paulo'],
    ['dst' => 1, 'offset' => -7200, 'timezone_id' => 'America/Sao_Paulo'],
    ['dst' => 0, 'offset' => -3600, 'timezone_id' => 'Atlantic/Azores'],
    ['dst' => 1, 'offset' => 0, 'timezone_id' => 'Atlantic/Azores'],
    ['dst' => 0, 'offset' => 0, 'timezone_id' => 'Europe/London'],
    ['dst' => 1, 'offset' => 3600, 'timezone_id' => 'Europe/London'],
    ['dst' => 0, 'offset' => 3600, 'timezone_id' => 'Europe/Paris'],
    ['dst' => 1, 'offset' => 7200, 'timezone_id' => 'Europe/Paris'],
    ['dst' => 0, 'offset' => 7200, 'timezone_id' => 'Europe/Helsinki'],
    ['dst' => 1, 'offset' => 10800, 'timezone_id' => 'Europe/Helsinki'],
    ['dst' => 0, 'offset' => 10800, 'timezone_id' => 'Europe/Moscow'],
    ['dst' => 1, 'offset' => 14400, 'timezone_id' => 'Europe/Moscow'],
    ['dst' => 0, 'offset' => 14400, 'timezone_id' => 'Asia/Dubai'],
    ['dst' => 0, 'offset' => 18000, 'timezone_id' => 'Asia/Karachi'],
    ['dst' => 0, 'offset' => 19800, 'timezone_id' => 'Asia/Kolkata'],
    ['dst' => 0, 'offset' => 20700, 'timezone_id' => 'Asia/Katmandu'],
    ['dst' => 1, 'offset' => 21600, 'timezone_id' => 'Asia/Yekaterinburg'],
    ['dst' => 1, 'offset' => 25200, 'timezone_id' => 'Asia/Novosibirsk'],
    ['dst' => 0, 'offset' => 25200, 'timezone_id' => 'Asia/Krasnoyarsk'],
    ['dst' => 0, 'offset' => 28800, 'timezone_id' => 'Asia/Shanghai'],
    ['dst' => 1, 'offset' => 28800, 'timezone_id' => 'Asia/Krasnoyarsk'],
    ['dst' => 0, 'offset' => 32400, 'timezone_id' => 'Asia/Tokyo'],
    ['dst' => 0, 'offset' => 36000, 'timezone_id' => 'Australia/Melbourne'],
    ['dst' => 1, 'offset' => 37800, 'timezone_id' => 'Australia/Adelaide'],
    ['dst' => 1, 'offset' => 39600, 'timezone_id' => 'Australia/Melbourne'],
    ['dst' => 0, 'offset' => 43200, 'timezone_id' => 'Pacific/Auckland'],
    ['dst' => 1, 'offset' => 46800, 'timezone_id' => 'Pacific/Auckland'],
];
