<?php

declare(strict_types=1);

/**
 * GENERATED by script/generate-extension-registry.php — do not edit by hand.
 *
 * The default extension set and the order it loads in (RELEASE-PLAN Phase 2.5). Regenerate with
 * `php script/generate-extension-registry.php`; `--check` fails when this file is out of date.
 *
 * Order is significant and is copied verbatim from what Runtime::loadCoreModules() did before this
 * file existed. Some constraints are declared on the modules themselves
 * ({@see \PHPCompiler\Module::getExtensionDependencies}) and verified by
 * script/check-extension-dependencies.php; others are still only implicit, which is why the order is
 * preserved rather than derived.
 *
 * The entries are literal `new` expressions on purpose: the AOT compiler resolves these statically,
 * and instantiating from a string would leave every module unreferenced and uncompiled.
 *
 * 84 extensions from ext/<name>/ext.json (#36204). Subset builds use
 * `--only=` / `--without=` on this script; runtime {@see \PHPCompiler\Module::isDefaultEnabled}
 * mirrors each manifest's default_enabled via {@see self::isDefaultEnabledFor()}.
 */

namespace PHPCompiler;

final class ExtensionRegistry
{
    /**
     * @return list<Module>
     */
    public static function defaultModules(): array
    {
        return [
            new \PHPCompiler\ext\types\Module(),
            new \PHPCompiler\ext\spl\Module(),
            new \PHPCompiler\ext\ds\Module(),
            new \PHPCompiler\ext\intl\Module(),
            new \PHPCompiler\ext\zip\Module(),
            new \PHPCompiler\ext\libxml\Module(),
            new \PHPCompiler\ext\dom\Module(),
            new \PHPCompiler\ext\xsl\Module(),
            new \PHPCompiler\ext\simplexml\Module(),
            new \PHPCompiler\ext\xml\Module(),
            new \PHPCompiler\ext\xmlrpc\Module(),
            new \PHPCompiler\ext\wddx\Module(),
            new \PHPCompiler\ext\xmlreader\Module(),
            new \PHPCompiler\ext\xmlwriter\Module(),
            new \PHPCompiler\ext\gd\Module(),
            new \PHPCompiler\ext\imagick\Module(),
            new \PHPCompiler\ext\exif\Module(),
            new \PHPCompiler\ext\fileinfo\Module(),
            new \PHPCompiler\ext\iconv\Module(),
            new \PHPCompiler\ext\gettext\Module(),
            new \PHPCompiler\ext\mbstring\Module(),
            new \PHPCompiler\ext\filter\Module(),
            new \PHPCompiler\ext\calendar\Module(),
            new \PHPCompiler\ext\ldap\Module(),
            new \PHPCompiler\ext\session\Module(),
            new \PHPCompiler\ext\bcmath\Module(),
            new \PHPCompiler\ext\gmp\Module(),
            new \PHPCompiler\ext\stats\Module(),
            new \PHPCompiler\ext\opcache\Module(),
            new \PHPCompiler\ext\openssl\Module(),
            new \PHPCompiler\ext\curl\Module(),
            new \PHPCompiler\ext\hash\Module(),
            new \PHPCompiler\ext\posix\Module(),
            new \PHPCompiler\ext\inotify\Module(),
            new \PHPCompiler\ext\pcntl\Module(),
            new \PHPCompiler\ext\sockets\Module(),
            new \PHPCompiler\ext\zmq\Module(),
            new \PHPCompiler\ext\ftp\Module(),
            new \PHPCompiler\ext\soap\Module(),
            new \PHPCompiler\ext\ffi\Module(),
            new \PHPCompiler\ext\ctype\Module(),
            new \PHPCompiler\ext\tokenizer\Module(),
            new \PHPCompiler\ext\random\Module(),
            new \PHPCompiler\ext\igbinary\Module(),
            new \PHPCompiler\ext\msgpack\Module(),
            new \PHPCompiler\ext\simdjson\Module(),
            new \PHPCompiler\ext\yaml\Module(),
            new \PHPCompiler\ext\redis\Module(),
            new \PHPCompiler\ext\memcached\Module(),
            new \PHPCompiler\ext\mongodb\Module(),
            new \PHPCompiler\ext\snmp\Module(),
            new \PHPCompiler\ext\zstd\Module(),
            new \PHPCompiler\ext\lzf\Module(),
            new \PHPCompiler\ext\lz4\Module(),
            new \PHPCompiler\ext\bz2\Module(),
            new \PHPCompiler\ext\rar\Module(),
            new \PHPCompiler\ext\imap\Module(),
            new \PHPCompiler\ext\eio\Module(),
            new \PHPCompiler\ext\ssh2\Module(),
            new \PHPCompiler\ext\brotli\Module(),
            new \PHPCompiler\ext\sodium\Module(),
            new \PHPCompiler\ext\sqlite3\Module(),
            new \PHPCompiler\ext\pgsql\Module(),
            new \PHPCompiler\ext\odbc\Module(),
            new \PHPCompiler\ext\oci8\Module(),
            new \PHPCompiler\ext\dba\Module(),
            new \PHPCompiler\ext\mailparse\Module(),
            new \PHPCompiler\ext\enchant\Module(),
            new \PHPCompiler\ext\gnupg\Module(),
            new \PHPCompiler\ext\pspell\Module(),
            new \PHPCompiler\ext\mysqli\Module(),
            new \PHPCompiler\ext\sqlsrv\Module(),
            new \PHPCompiler\ext\tidy\Module(),
            new \PHPCompiler\ext\pdo\Module(),
            new \PHPCompiler\ext\phar\Module(),
            new \PHPCompiler\ext\uri\Module(),
            new \PHPCompiler\ext\uuid\Module(),
            new \PHPCompiler\ext\uploadprogress\Module(),
            new \PHPCompiler\ext\apcu\Module(),
            new \PHPCompiler\ext\sysvshm\Module(),
            new \PHPCompiler\ext\sysvsem\Module(),
            new \PHPCompiler\ext\sysvmsg\Module(),
            new \PHPCompiler\ext\reflection\Module(),
            new \PHPCompiler\ext\standard\Module(),
        ];
    }

    /**
     * Declared depends[] from every ext/<name>/ext.json (#36204).
     *
     * Keyed by ext/ directory name (not getExtensionName() — 20 modules report 'standard').
     *
     * @return array<string, list<string>>
     */
    public static function dependenciesByDirectory(): array
    {
        return [
            'dom' => ['libxml'],
            'xsl' => ['libxml', 'dom'],
            'simplexml' => ['libxml'],
            'xml' => ['libxml'],
            'xmlreader' => ['libxml'],
            'xmlwriter' => ['libxml'],
        ];
    }

    /**
     * default_enabled from every ext/<name>/ext.json (#36204).
     *
     * @return array<string, bool>
     */
    public static function defaultEnabledByDirectory(): array
    {
        return [
            'types' => true,
            'spl' => true,
            'ds' => true,
            'intl' => true,
            'zip' => true,
            'libxml' => true,
            'dom' => true,
            'xsl' => true,
            'simplexml' => true,
            'xml' => true,
            'xmlrpc' => true,
            'wddx' => true,
            'xmlreader' => true,
            'xmlwriter' => true,
            'gd' => true,
            'imagick' => true,
            'exif' => true,
            'fileinfo' => true,
            'iconv' => true,
            'gettext' => true,
            'mbstring' => true,
            'filter' => true,
            'calendar' => true,
            'ldap' => true,
            'session' => true,
            'bcmath' => true,
            'gmp' => true,
            'stats' => true,
            'opcache' => true,
            'openssl' => true,
            'curl' => true,
            'hash' => true,
            'posix' => true,
            'inotify' => true,
            'pcntl' => true,
            'sockets' => true,
            'zmq' => true,
            'ftp' => true,
            'soap' => true,
            'ffi' => true,
            'ctype' => true,
            'tokenizer' => true,
            'random' => true,
            'igbinary' => true,
            'msgpack' => true,
            'simdjson' => true,
            'yaml' => true,
            'redis' => true,
            'memcached' => true,
            'mongodb' => true,
            'snmp' => true,
            'zstd' => true,
            'lzf' => true,
            'lz4' => true,
            'bz2' => true,
            'rar' => true,
            'imap' => true,
            'eio' => true,
            'ssh2' => true,
            'brotli' => true,
            'sodium' => true,
            'sqlite3' => true,
            'pgsql' => true,
            'odbc' => true,
            'oci8' => true,
            'dba' => true,
            'mailparse' => true,
            'enchant' => true,
            'gnupg' => true,
            'pspell' => true,
            'mysqli' => true,
            'sqlsrv' => true,
            'tidy' => true,
            'pdo' => true,
            'phar' => true,
            'uri' => true,
            'uuid' => true,
            'uploadprogress' => true,
            'apcu' => true,
            'sysvshm' => true,
            'sysvsem' => true,
            'sysvmsg' => true,
            'reflection' => true,
            'standard' => true,
        ];
    }

    /**
     * @return list<string>
     */
    public static function dependenciesFor(string $directory): array
    {
        return self::dependenciesByDirectory()[$directory] ?? [];
    }

    public static function isDefaultEnabledFor(string $directory): bool
    {
        return self::defaultEnabledByDirectory()[$directory] ?? true;
    }
}
