<?php

declare(strict_types=1);

namespace PHPCompiler\ext\intl;

/**
 * ICU UErrorCode globals registered by php-src ext/intl (php_intl.c / utypes.h; #23998).
 *
 * Values match ICU UErrorCode; Zend exposes them as bare globals under get_defined_constants(true)["intl"].
 */
final class IcuErrorConstants
{
    /** @return array<string, int> */
    public static function registeredConstants(): array
    {
        return [
            'U_AMBIGUOUS_ALIAS_WARNING' => -122,
            'U_BAD_VARIABLE_DEFINITION' => 65536,
            'U_BRK_ASSIGN_ERROR' => 66053,
            'U_BRK_ERROR_LIMIT' => 66062,
            'U_BRK_ERROR_START' => 66048,
            'U_BRK_HEX_DIGITS_EXPECTED' => 66049,
            'U_BRK_INIT_ERROR' => 66058,
            'U_BRK_INTERNAL_ERROR' => 66048,
            'U_BRK_MALFORMED_RULE_TAG' => 66061,
            'U_BRK_MISMATCHED_PAREN' => 66055,
            'U_BRK_NEW_LINE_IN_QUOTED_STRING' => 66056,
            'U_BRK_RULE_EMPTY_SET' => 66059,
            'U_BRK_RULE_SYNTAX' => 66051,
            'U_BRK_SEMICOLON_EXPECTED' => 66050,
            'U_BRK_UNCLOSED_SET' => 66052,
            'U_BRK_UNDEFINED_VARIABLE' => 66057,
            'U_BRK_UNRECOGNIZED_OPTION' => 66060,
            'U_BRK_VARIABLE_REDFINITION' => 66054,
            'U_BUFFER_OVERFLOW_ERROR' => 15,
            'U_CE_NOT_FOUND_ERROR' => 21,
            'U_COLLATOR_VERSION_MISMATCH' => 28,
            'U_DIFFERENT_UCA_VERSION' => -121,
            'U_ENUM_OUT_OF_SYNC_ERROR' => 25,
            'U_ERROR_LIMIT' => 66818,
            'U_ERROR_WARNING_LIMIT' => -119,
            'U_ERROR_WARNING_START' => -128,
            'U_FILE_ACCESS_ERROR' => 4,
            'U_FMT_PARSE_ERROR_LIMIT' => 65812,
            'U_FMT_PARSE_ERROR_START' => 65792,
            'U_IDNA_ACE_PREFIX_ERROR' => 66564,
            'U_IDNA_CHECK_BIDI_ERROR' => 66562,
            'U_IDNA_DOMAIN_NAME_TOO_LONG_ERROR' => 66568,
            'U_IDNA_ERROR_LIMIT' => 66569,
            'U_IDNA_ERROR_START' => 66560,
            'U_IDNA_LABEL_TOO_LONG_ERROR' => 66566,
            'U_IDNA_PROHIBITED_ERROR' => 66560,
            'U_IDNA_STD3_ASCII_RULES_ERROR' => 66563,
            'U_IDNA_UNASSIGNED_ERROR' => 66561,
            'U_IDNA_VERIFICATION_ERROR' => 66565,
            'U_IDNA_ZERO_LENGTH_LABEL_ERROR' => 66567,
            'U_ILLEGAL_ARGUMENT_ERROR' => 1,
            'U_ILLEGAL_CHARACTER' => 65567,
            'U_ILLEGAL_CHAR_FOUND' => 12,
            'U_ILLEGAL_CHAR_IN_SEGMENT' => 65564,
            'U_ILLEGAL_ESCAPE_SEQUENCE' => 18,
            'U_ILLEGAL_PAD_POSITION' => 65800,
            'U_INDEX_OUTOFBOUNDS_ERROR' => 8,
            'U_INTERNAL_PROGRAM_ERROR' => 5,
            'U_INTERNAL_TRANSLITERATOR_ERROR' => 65568,
            'U_INVALID_CHAR_FOUND' => 10,
            'U_INVALID_FORMAT_ERROR' => 3,
            'U_INVALID_FUNCTION' => 65570,
            'U_INVALID_ID' => 65569,
            'U_INVALID_PROPERTY_PATTERN' => 65561,
            'U_INVALID_RBT_SYNTAX' => 65560,
            'U_INVALID_STATE_ERROR' => 27,
            'U_INVALID_TABLE_FILE' => 14,
            'U_INVALID_TABLE_FORMAT' => 13,
            'U_INVARIANT_CONVERSION_ERROR' => 26,
            'U_MALFORMED_EXPONENTIAL_PATTERN' => 65795,
            'U_MALFORMED_PRAGMA' => 65562,
            'U_MALFORMED_RULE' => 65537,
            'U_MALFORMED_SET' => 65538,
            'U_MALFORMED_SYMBOL_REFERENCE' => 65539,
            'U_MALFORMED_UNICODE_ESCAPE' => 65540,
            'U_MALFORMED_VARIABLE_DEFINITION' => 65541,
            'U_MALFORMED_VARIABLE_REFERENCE' => 65542,
            'U_MEMORY_ALLOCATION_ERROR' => 7,
            'U_MESSAGE_PARSE_ERROR' => 6,
            'U_MISMATCHED_SEGMENT_DELIMITERS' => 65543,
            'U_MISPLACED_ANCHOR_START' => 65544,
            'U_MISPLACED_COMPOUND_FILTER' => 65558,
            'U_MISPLACED_CURSOR_OFFSET' => 65545,
            'U_MISPLACED_QUANTIFIER' => 65546,
            'U_MISSING_OPERATOR' => 65547,
            'U_MISSING_RESOURCE_ERROR' => 2,
            'U_MISSING_SEGMENT_CLOSE' => 65548,
            'U_MULTIPLE_ANTE_CONTEXTS' => 65549,
            'U_MULTIPLE_COMPOUND_FILTERS' => 65559,
            'U_MULTIPLE_CURSORS' => 65550,
            'U_MULTIPLE_DECIMAL_SEPARATORS' => 65793,
            'U_MULTIPLE_DECIMAL_SEPERATORS' => 65793,
            'U_MULTIPLE_EXPONENTIAL_SYMBOLS' => 65794,
            'U_MULTIPLE_PAD_SPECIFIERS' => 65798,
            'U_MULTIPLE_PERCENT_SYMBOLS' => 65796,
            'U_MULTIPLE_PERMILL_SYMBOLS' => 65797,
            'U_MULTIPLE_POST_CONTEXTS' => 65551,
            'U_NO_SPACE_AVAILABLE' => 20,
            'U_NO_WRITE_PERMISSION' => 30,
            'U_PARSE_ERROR' => 9,
            'U_PARSE_ERROR_LIMIT' => 65571,
            'U_PARSE_ERROR_START' => 65536,
            'U_PATTERN_SYNTAX_ERROR' => 65799,
            'U_PRIMARY_TOO_LONG_ERROR' => 22,
            'U_REGEX_BAD_ESCAPE_SEQUENCE' => 66307,
            'U_REGEX_BAD_INTERVAL' => 66312,
            'U_REGEX_ERROR_LIMIT' => 66326,
            'U_REGEX_ERROR_START' => 66304,
            'U_REGEX_INTERNAL_ERROR' => 66304,
            'U_REGEX_INVALID_BACK_REF' => 66314,
            'U_REGEX_INVALID_FLAG' => 66315,
            'U_REGEX_INVALID_STATE' => 66306,
            'U_REGEX_LOOK_BEHIND_LIMIT' => 66316,
            'U_REGEX_MAX_LT_MIN' => 66313,
            'U_REGEX_MISMATCHED_PAREN' => 66310,
            'U_REGEX_NUMBER_TOO_BIG' => 66311,
            'U_REGEX_PROPERTY_SYNTAX' => 66308,
            'U_REGEX_RULE_SYNTAX' => 66305,
            'U_REGEX_SET_CONTAINS_STRING' => 66317,
            'U_REGEX_UNIMPLEMENTED' => 66309,
            'U_RESOURCE_TYPE_MISMATCH' => 17,
            'U_RULE_MASK_ERROR' => 65557,
            'U_SAFECLONE_ALLOCATED_WARNING' => -126,
            'U_SORT_KEY_TOO_SHORT_WARNING' => -123,
            'U_STANDARD_ERROR_LIMIT' => 32,
            'U_STATE_OLD_WARNING' => -125,
            'U_STATE_TOO_OLD_ERROR' => 23,
            'U_STRINGPREP_CHECK_BIDI_ERROR' => 66562,
            'U_STRINGPREP_PROHIBITED_ERROR' => 66560,
            'U_STRINGPREP_UNASSIGNED_ERROR' => 66561,
            'U_STRING_NOT_TERMINATED_WARNING' => -124,
            'U_TOO_MANY_ALIASES_ERROR' => 24,
            'U_TRAILING_BACKSLASH' => 65552,
            'U_TRUNCATED_CHAR_FOUND' => 11,
            'U_UNCLOSED_SEGMENT' => 65563,
            'U_UNDEFINED_SEGMENT_REFERENCE' => 65553,
            'U_UNDEFINED_VARIABLE' => 65554,
            'U_UNEXPECTED_TOKEN' => 65792,
            'U_UNMATCHED_BRACES' => 65801,
            'U_UNQUOTED_SPECIAL' => 65555,
            'U_UNSUPPORTED_ATTRIBUTE' => 65803,
            'U_UNSUPPORTED_ERROR' => 16,
            'U_UNSUPPORTED_ESCAPE_SEQUENCE' => 19,
            'U_UNSUPPORTED_PROPERTY' => 65802,
            'U_UNTERMINATED_QUOTE' => 65556,
            'U_USELESS_COLLATOR_ERROR' => 29,
            'U_USING_DEFAULT_WARNING' => -127,
            'U_USING_FALLBACK_WARNING' => -128,
            'U_VARIABLE_RANGE_EXHAUSTED' => 65565,
            'U_VARIABLE_RANGE_OVERLAP' => 65566,
            'U_ZERO_ERROR' => 0,
        ];
    }
}
