<?php

declare(strict_types=1);

// @fuzz-seed: 3
// @fuzz-shape: array_list
// generated by script/fuzz/gen.php (#36398)

$a = [];
for ($i = 0; $i < 3; ++$i) {
    $a[] = $i * 2;
}
$a[] = 99;
echo count($a), "|", $a[0], "|", $a[count($a) - 1], "\n";
var_dump(count($a));
