<?php

declare(strict_types=1);

// @fuzz-seed: 42
// @fuzz-shape: arith_main
// generated by script/fuzz/gen.php (#36398)

$a = -16;
$b = 4;
$c = $a + $b;
$c = $c + ($a % 3);
echo $a, " ", $b, " ", $c, "\n";
var_dump($c);
