<?php

declare(strict_types=1);

// @fuzz-seed: 30004
// @fuzz-shape: static_counter_fn
// generated by script/fuzz/gen.php (#36398)

function tick(): int
{
    static $n = 0;
    $n = $n + 1;
    return $n;
}

$last = 0;
for ($i = 0; $i < 5; ++$i) {
    $last = tick();
}
echo $last, "|", tick(), "\n";
var_dump($last);
