<?php

declare(strict_types=1);

// @fuzz-seed: 2
// @fuzz-shape: arith_main
// generated by script/fuzz/gen.php (#36398)

$a = -8;
$b = 13;
$c = $a * $b;
$c = $c + ($a % 3);
echo $a, " ", $b, " ", $c, "\n";
var_dump($c);
