<?php

declare(strict_types=1);

// @fuzz-seed: 30002
// @fuzz-shape: string_offset_assign
// generated by script/fuzz/gen.php (#36398)

$s = 'wxyz';
$s[1] = '0';
$s .= "!";
echo $s, "|", strlen($s), "|", $s[0], "\n";
var_dump(strlen($s));
