<?php

declare(strict_types=1);

// @fuzz-seed: 20009
// @fuzz-shape: nested_array_isset
// generated by script/fuzz/gen.php (#36398)

$m = [];
for ($i = 0; $i < 2; ++$i) {
    $m[$i] = ["v" => $i, "t" => $i * 2];
}
$hits = 0;
for ($i = 0; $i < 2; ++$i) {
    if ((isset($m[$i]["v"]) && isset($m[$i]["t"])) && $m[$i]["t"] === $i * 2) {
        ++$hits;
    }
}
echo $hits, "|", $m[0]["v"], "\n";
var_dump($hits);
