<?php

declare(strict_types=1);

// @fuzz-seed: 30003
// @fuzz-shape: switch_int_fallthrough
// generated by script/fuzz/gen.php (#36398)

$n = 4;
$s = 0;
switch ($n) {
    case 0:
        $s += 1;
        // fallthrough
    case 1:
        $s += 10;
        break;
    case 2:
        $s += 100;
        break;
    default:
        $s += 7;
}
echo $n, "|", $s, "\n";
var_dump($s);
