<?php

declare(strict_types=1);

// @fuzz-seed: 30005
// @fuzz-shape: array_plus_vs_merge
// generated by script/fuzz/gen.php (#36398)

$a = [];
$b = [];
for ($i = 0; $i < 4; ++$i) {
    $a[$i] = $i;
    $b[$i] = $i + 10;
}
$b["x"] = 99;
$plus = $a + $b;
$merged = array_merge($a, $b);
echo count($plus), "|", count($merged), "|", $plus[0], "|", $merged[0], "\n";
var_dump(count($plus), count($merged));
