<?php

declare(strict_types=1);

// @fuzz-seed: 30001
// @fuzz-shape: foreach_byref_mutate
// generated by script/fuzz/gen.php (#36398)

$a = [];
for ($i = 0; $i < 3; ++$i) {
    $a[] = $i;
}
foreach ($a as &$v) {
    $v = $v + 1;
}
unset($v);
$sum = 0;
foreach ($a as $x) {
    $sum += $x;
}
echo count($a), "|", $a[0], "|", $sum, "\n";
var_dump($sum);
