<?php

declare(strict_types=1);

// @fuzz-seed: 30006
// @fuzz-shape: new_static_counter_ctor_args
// generated by script/fuzz/gen.php (#36398) — New_ sibling side-effect args

function mk($n)
{
    static $c = 0;

    return ++$c + $n;
}

class Box
{
    public $a;
    public $b;

    public function __construct($a, $b)
    {
        $this->a = $a;
        $this->b = $b;
    }
}

$o = new Box(mk(0), mk(0));
echo $o->a, "|", $o->b, "\n";
var_dump($o->a, $o->b);
