<?php
echo 'UNLIMATERECEIVER=', defined('SOAP_ACTOR_UNLIMATERECEIVER') ? (string) SOAP_ACTOR_UNLIMATERECEIVER : 'UNDEF', "\n";
echo 'UNLIMATED=', defined('SOAP_ACTOR_UNLIMATED') ? (string) SOAP_ACTOR_UNLIMATED : 'UNDEF', "\n";
