<?php
// Repro for #22703 — ROUNDING_MODE honored in format().
$f = new NumberFormatter('en_US', NumberFormatter::DECIMAL);
$f->setAttribute(NumberFormatter::FRACTION_DIGITS, 0);
$mode = NumberFormatter::ROUND_HALFEVEN;
$f->setAttribute(NumberFormatter::ROUNDING_MODE, $mode);
echo 'HALFEVEN=', $f->format(1.5), '|', $f->format(2.5), '|', $f->format(3.5), "\n";
$f = new NumberFormatter('en_US', NumberFormatter::DECIMAL);
$f->setAttribute(NumberFormatter::FRACTION_DIGITS, 0);
$mode = NumberFormatter::ROUND_HALFDOWN;
$f->setAttribute(NumberFormatter::ROUNDING_MODE, $mode);
echo 'HALFDOWN=', $f->format(1.5), '|', $f->format(2.5), '|', $f->format(3.5), "\n";
$f = new NumberFormatter('en_US', NumberFormatter::DECIMAL);
$f->setAttribute(NumberFormatter::FRACTION_DIGITS, 0);
$mode = NumberFormatter::ROUND_CEILING;
$f->setAttribute(NumberFormatter::ROUNDING_MODE, $mode);
echo 'CEILING=', $f->format(1.1), '|', $f->format(-1.5), "\n";
$f = new NumberFormatter('en_US', NumberFormatter::DECIMAL);
$f->setAttribute(NumberFormatter::FRACTION_DIGITS, 0);
$mode = NumberFormatter::ROUND_FLOOR;
$f->setAttribute(NumberFormatter::ROUNDING_MODE, $mode);
echo 'FLOOR=', $f->format(1.9), '|', $f->format(-1.5), "\n";
$f = new NumberFormatter('en_US', NumberFormatter::DECIMAL);
$f->setAttribute(NumberFormatter::FRACTION_DIGITS, 0);
$mode = NumberFormatter::ROUND_DOWN;
$f->setAttribute(NumberFormatter::ROUNDING_MODE, $mode);
echo 'DOWN=', $f->format(1.5), '|', $f->format(2.5), '|', $f->format(3.5), "\n";
$f = new NumberFormatter('en_US', NumberFormatter::DECIMAL);
$f->setAttribute(NumberFormatter::FRACTION_DIGITS, 0);
$mode = NumberFormatter::ROUND_UP;
$f->setAttribute(NumberFormatter::ROUNDING_MODE, $mode);
echo 'UP=', $f->format(1.5), '|', $f->format(2.5), '|', $f->format(3.5), "\n";
