<?php

declare(strict_types=1);

namespace PHPCompiler\ext\sodium;

/**
 * SODIUM_* extension constants (php-src ext/sodium/sodium.c; issue #13078).
 */
final class SodiumConstants
{
    /** @return array<string, int|string> */
    public static function registeredConstants(): array
    {
        $out = [];
        try {
            $identity = VmSodium::libraryIdentity();
            // Library identity (php-src ext/sodium/libsodium.c; #24069)
            $out['SODIUM_LIBRARY_VERSION'] = $identity['version'];
            $out['SODIUM_LIBRARY_MAJOR_VERSION'] = $identity['major'];
            $out['SODIUM_LIBRARY_MINOR_VERSION'] = $identity['minor'];
        } catch (\Throwable) {
            // available() without version symbols — omit rather than fake (#24069)
        }

        return $out + [
            'SODIUM_CRYPTO_SECRETBOX_KEYBYTES' => VmSodium::CRYPTO_SECRETBOX_KEYBYTES,
            'SODIUM_CRYPTO_SECRETBOX_NONCEBYTES' => VmSodium::CRYPTO_SECRETBOX_NONCEBYTES,
            'SODIUM_CRYPTO_SECRETBOX_MACBYTES' => VmSodium::CRYPTO_SECRETBOX_MACBYTES,
            'SODIUM_CRYPTO_AUTH_KEYBYTES' => VmSodium::CRYPTO_AUTH_KEYBYTES,
            'SODIUM_CRYPTO_AUTH_BYTES' => VmSodium::CRYPTO_AUTH_BYTES,
            'SODIUM_CRYPTO_STREAM_KEYBYTES' => VmSodium::CRYPTO_STREAM_KEYBYTES,
            'SODIUM_CRYPTO_STREAM_NONCEBYTES' => VmSodium::CRYPTO_STREAM_NONCEBYTES,
            'SODIUM_CRYPTO_STREAM_XCHACHA20_KEYBYTES' => VmSodium::CRYPTO_STREAM_XCHACHA20_KEYBYTES,
            'SODIUM_CRYPTO_STREAM_XCHACHA20_NONCEBYTES' => VmSodium::CRYPTO_STREAM_XCHACHA20_NONCEBYTES,
            'SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_KEYBYTES' => VmSodium::CRYPTO_AEAD_XCHACHA20POLY1305_IETF_KEYBYTES,
            'SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES' => VmSodium::CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES,
            // php-src registers NSECBYTES (not NSECRETBYTES); same value 0 (#24110)
            'SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NSECBYTES' => VmSodium::CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NSECRETBYTES,
            'SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_ABYTES' => VmSodium::CRYPTO_AEAD_XCHACHA20POLY1305_IETF_ABYTES,
            'SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_KEYBYTES' => VmSodium::CRYPTO_AEAD_CHACHA20POLY1305_KEYBYTES,
            'SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_NPUBBYTES' => VmSodium::CRYPTO_AEAD_CHACHA20POLY1305_NPUBBYTES,
            'SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_NSECBYTES' => VmSodium::CRYPTO_AEAD_CHACHA20POLY1305_NSECRETBYTES,
            'SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_ABYTES' => VmSodium::CRYPTO_AEAD_CHACHA20POLY1305_ABYTES,
            'SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_IETF_KEYBYTES' => VmSodium::CRYPTO_AEAD_CHACHA20POLY1305_IETF_KEYBYTES,
            'SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_IETF_NPUBBYTES' => VmSodium::CRYPTO_AEAD_CHACHA20POLY1305_IETF_NPUBBYTES,
            'SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_IETF_NSECBYTES' => VmSodium::CRYPTO_AEAD_CHACHA20POLY1305_IETF_NSECRETBYTES,
            'SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_IETF_ABYTES' => VmSodium::CRYPTO_AEAD_CHACHA20POLY1305_IETF_ABYTES,
            'SODIUM_CRYPTO_GENERICHASH_BYTES' => VmSodium::CRYPTO_GENERICHASH_BYTES,
            'SODIUM_CRYPTO_GENERICHASH_BYTES_MIN' => VmSodium::CRYPTO_GENERICHASH_BYTES_MIN,
            'SODIUM_CRYPTO_GENERICHASH_BYTES_MAX' => VmSodium::CRYPTO_GENERICHASH_BYTES_MAX,
            'SODIUM_CRYPTO_GENERICHASH_KEYBYTES' => VmSodium::CRYPTO_GENERICHASH_KEYBYTES,
            'SODIUM_CRYPTO_GENERICHASH_KEYBYTES_MIN' => VmSodium::CRYPTO_GENERICHASH_KEYBYTES_MIN,
            'SODIUM_CRYPTO_GENERICHASH_KEYBYTES_MAX' => VmSodium::CRYPTO_GENERICHASH_KEYBYTES_MAX,
            'SODIUM_CRYPTO_SCALARMULT_BYTES' => VmSodium::CRYPTO_SCALARMULT_BYTES,
            'SODIUM_CRYPTO_SCALARMULT_SCALARBYTES' => VmSodium::CRYPTO_SCALARMULT_SCALARBYTES,
            'SODIUM_CRYPTO_CORE_RISTRETTO255_BYTES' => VmSodium::CRYPTO_CORE_RISTRETTO255_BYTES,
            'SODIUM_CRYPTO_CORE_RISTRETTO255_HASHBYTES' => VmSodium::CRYPTO_CORE_RISTRETTO255_HASHBYTES,
            'SODIUM_CRYPTO_CORE_RISTRETTO255_SCALARBYTES' => VmSodium::CRYPTO_CORE_RISTRETTO255_SCALARBYTES,
            'SODIUM_CRYPTO_CORE_RISTRETTO255_NONREDUCEDSCALARBYTES' => VmSodium::CRYPTO_CORE_RISTRETTO255_NONREDUCEDSCALARBYTES,
            'SODIUM_CRYPTO_SCALARMULT_RISTRETTO255_BYTES' => VmSodium::CRYPTO_SCALARMULT_RISTRETTO255_BYTES,
            'SODIUM_CRYPTO_SCALARMULT_RISTRETTO255_SCALARBYTES' => VmSodium::CRYPTO_SCALARMULT_RISTRETTO255_SCALARBYTES,
            'SODIUM_CRYPTO_BOX_SECRETKEYBYTES' => VmSodium::CRYPTO_BOX_SECRETKEYBYTES,
            'SODIUM_CRYPTO_BOX_PUBLICKEYBYTES' => VmSodium::CRYPTO_BOX_PUBLICKEYBYTES,
            'SODIUM_CRYPTO_BOX_KEYPAIRBYTES' => VmSodium::CRYPTO_BOX_KEYPAIRBYTES,
            'SODIUM_CRYPTO_BOX_SEEDBYTES' => VmSodium::CRYPTO_BOX_SEEDBYTES,
            'SODIUM_CRYPTO_BOX_MACBYTES' => VmSodium::CRYPTO_BOX_MACBYTES,
            'SODIUM_CRYPTO_BOX_NONCEBYTES' => VmSodium::CRYPTO_BOX_NONCEBYTES,
            'SODIUM_CRYPTO_BOX_SEALBYTES' => VmSodium::CRYPTO_BOX_SEALBYTES,
            'SODIUM_CRYPTO_KX_PUBLICKEYBYTES' => VmSodium::CRYPTO_KX_PUBLICKEYBYTES,
            'SODIUM_CRYPTO_KX_SECRETKEYBYTES' => VmSodium::CRYPTO_KX_SECRETKEYBYTES,
            'SODIUM_CRYPTO_KX_KEYPAIRBYTES' => VmSodium::CRYPTO_KX_KEYPAIRBYTES,
            'SODIUM_CRYPTO_KX_SEEDBYTES' => VmSodium::CRYPTO_KX_SEEDBYTES,
            'SODIUM_CRYPTO_KX_SESSIONKEYBYTES' => VmSodium::CRYPTO_KX_SESSIONKEYBYTES,
            'SODIUM_CRYPTO_AEAD_AES256GCM_KEYBYTES' => VmSodium::CRYPTO_AEAD_AES256GCM_KEYBYTES,
            'SODIUM_CRYPTO_AEAD_AES256GCM_NPUBBYTES' => VmSodium::CRYPTO_AEAD_AES256GCM_NPUBBYTES,
            'SODIUM_CRYPTO_AEAD_AES256GCM_NSECBYTES' => VmSodium::CRYPTO_AEAD_AES256GCM_NSECRETBYTES,
            'SODIUM_CRYPTO_AEAD_AES256GCM_ABYTES' => VmSodium::CRYPTO_AEAD_AES256GCM_ABYTES,
            ...self::aegisConstants(),
            'SODIUM_CRYPTO_SIGN_BYTES' => VmSodium::CRYPTO_SIGN_BYTES,
            'SODIUM_CRYPTO_SIGN_SEEDBYTES' => VmSodium::CRYPTO_SIGN_SEEDBYTES,
            'SODIUM_CRYPTO_SIGN_PUBLICKEYBYTES' => VmSodium::CRYPTO_SIGN_PUBLICKEYBYTES,
            'SODIUM_CRYPTO_SIGN_SECRETKEYBYTES' => VmSodium::CRYPTO_SIGN_SECRETKEYBYTES,
            'SODIUM_CRYPTO_SIGN_KEYPAIRBYTES' => VmSodium::CRYPTO_SIGN_KEYPAIRBYTES,
            'SODIUM_CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_ABYTES' => VmSodium::CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_ABYTES,
            'SODIUM_CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_HEADERBYTES' => VmSodium::CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_HEADERBYTES,
            'SODIUM_CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_KEYBYTES' => VmSodium::CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_KEYBYTES,
            'SODIUM_CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_MESSAGEBYTES_MAX' => VmSodium::CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_MESSAGEBYTES_MAX,
            'SODIUM_CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_TAG_MESSAGE' => VmSodium::CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_TAG_MESSAGE,
            'SODIUM_CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_TAG_PUSH' => VmSodium::CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_TAG_PUSH,
            'SODIUM_CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_TAG_REKEY' => VmSodium::CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_TAG_REKEY,
            'SODIUM_CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_TAG_FINAL' => VmSodium::CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_TAG_FINAL,
            'SODIUM_CRYPTO_SHORTHASH_BYTES' => VmSodium::CRYPTO_SHORTHASH_BYTES,
            'SODIUM_CRYPTO_SHORTHASH_KEYBYTES' => VmSodium::CRYPTO_SHORTHASH_KEYBYTES,
            'SODIUM_CRYPTO_KDF_BYTES_MIN' => VmSodium::CRYPTO_KDF_BYTES_MIN,
            'SODIUM_CRYPTO_KDF_BYTES_MAX' => VmSodium::CRYPTO_KDF_BYTES_MAX,
            'SODIUM_CRYPTO_KDF_CONTEXTBYTES' => VmSodium::CRYPTO_KDF_CONTEXTBYTES,
            'SODIUM_CRYPTO_KDF_KEYBYTES' => VmSodium::CRYPTO_KDF_KEYBYTES,
            'SODIUM_CRYPTO_PWHASH_ALG_ARGON2I13' => VmSodium::CRYPTO_PWHASH_ALG_ARGON2I13,
            'SODIUM_CRYPTO_PWHASH_ALG_ARGON2ID13' => VmSodium::CRYPTO_PWHASH_ALG_ARGON2ID13,
            'SODIUM_CRYPTO_PWHASH_ALG_DEFAULT' => VmSodium::CRYPTO_PWHASH_ALG_DEFAULT,
            'SODIUM_CRYPTO_PWHASH_SALTBYTES' => VmSodium::CRYPTO_PWHASH_SALTBYTES,
            'SODIUM_CRYPTO_PWHASH_STRPREFIX' => VmSodium::CRYPTO_PWHASH_STRPREFIX,
            'SODIUM_CRYPTO_PWHASH_OPSLIMIT_INTERACTIVE' => VmSodium::CRYPTO_PWHASH_OPSLIMIT_INTERACTIVE,
            'SODIUM_CRYPTO_PWHASH_MEMLIMIT_INTERACTIVE' => VmSodium::CRYPTO_PWHASH_MEMLIMIT_INTERACTIVE,
            'SODIUM_CRYPTO_PWHASH_OPSLIMIT_MODERATE' => VmSodium::CRYPTO_PWHASH_OPSLIMIT_MODERATE,
            'SODIUM_CRYPTO_PWHASH_MEMLIMIT_MODERATE' => VmSodium::CRYPTO_PWHASH_MEMLIMIT_MODERATE,
            'SODIUM_CRYPTO_PWHASH_OPSLIMIT_SENSITIVE' => VmSodium::CRYPTO_PWHASH_OPSLIMIT_SENSITIVE,
            'SODIUM_CRYPTO_PWHASH_MEMLIMIT_SENSITIVE' => VmSodium::CRYPTO_PWHASH_MEMLIMIT_SENSITIVE,
            // scrypt (php-src ext/sodium/libsodium.c; #21460)
            'SODIUM_CRYPTO_PWHASH_SCRYPTSALSA208SHA256_SALTBYTES' => VmSodium::CRYPTO_PWHASH_SCRYPTSALSA208SHA256_SALTBYTES,
            'SODIUM_CRYPTO_PWHASH_SCRYPTSALSA208SHA256_STRPREFIX' => VmSodium::CRYPTO_PWHASH_SCRYPTSALSA208SHA256_STRPREFIX,
            'SODIUM_CRYPTO_PWHASH_SCRYPTSALSA208SHA256_OPSLIMIT_INTERACTIVE' => VmSodium::CRYPTO_PWHASH_SCRYPTSALSA208SHA256_OPSLIMIT_INTERACTIVE,
            'SODIUM_CRYPTO_PWHASH_SCRYPTSALSA208SHA256_MEMLIMIT_INTERACTIVE' => VmSodium::CRYPTO_PWHASH_SCRYPTSALSA208SHA256_MEMLIMIT_INTERACTIVE,
            'SODIUM_CRYPTO_PWHASH_SCRYPTSALSA208SHA256_OPSLIMIT_SENSITIVE' => VmSodium::CRYPTO_PWHASH_SCRYPTSALSA208SHA256_OPSLIMIT_SENSITIVE,
            'SODIUM_CRYPTO_PWHASH_SCRYPTSALSA208SHA256_MEMLIMIT_SENSITIVE' => VmSodium::CRYPTO_PWHASH_SCRYPTSALSA208SHA256_MEMLIMIT_SENSITIVE,
            // sodium_base64_VARIANT_* (php-src ext/sodium/libsodium.c; #20675)
            'SODIUM_BASE64_VARIANT_ORIGINAL' => VmSodium::BASE64_VARIANT_ORIGINAL,
            'SODIUM_BASE64_VARIANT_ORIGINAL_NO_PADDING' => VmSodium::BASE64_VARIANT_ORIGINAL_NO_PADDING,
            'SODIUM_BASE64_VARIANT_URLSAFE' => VmSodium::BASE64_VARIANT_URLSAFE,
            'SODIUM_BASE64_VARIANT_URLSAFE_NO_PADDING' => VmSodium::BASE64_VARIANT_URLSAFE_NO_PADDING,
        ];
    }

    /**
     * AEGIS size constants — only when libsodium provides the primitives (php-src #ifdef; #20518).
     *
     * @return array<string, int>
     */
    private static function aegisConstants(): array
    {
        $out = [];
        if (SodiumExtensionPolicy::advertisesAegis128l()) {
            $out['SODIUM_CRYPTO_AEAD_AEGIS128L_KEYBYTES'] = VmSodium::CRYPTO_AEAD_AEGIS128L_KEYBYTES;
            $out['SODIUM_CRYPTO_AEAD_AEGIS128L_NPUBBYTES'] = VmSodium::CRYPTO_AEAD_AEGIS128L_NPUBBYTES;
            $out['SODIUM_CRYPTO_AEAD_AEGIS128L_NSECBYTES'] = VmSodium::CRYPTO_AEAD_AEGIS128L_NSECRETBYTES;
            $out['SODIUM_CRYPTO_AEAD_AEGIS128L_ABYTES'] = VmSodium::CRYPTO_AEAD_AEGIS128L_ABYTES;
        }
        if (SodiumExtensionPolicy::advertisesAegis256()) {
            $out['SODIUM_CRYPTO_AEAD_AEGIS256_KEYBYTES'] = VmSodium::CRYPTO_AEAD_AEGIS256_KEYBYTES;
            $out['SODIUM_CRYPTO_AEAD_AEGIS256_NPUBBYTES'] = VmSodium::CRYPTO_AEAD_AEGIS256_NPUBBYTES;
            $out['SODIUM_CRYPTO_AEAD_AEGIS256_NSECBYTES'] = VmSodium::CRYPTO_AEAD_AEGIS256_NSECRETBYTES;
            $out['SODIUM_CRYPTO_AEAD_AEGIS256_ABYTES'] = VmSodium::CRYPTO_AEAD_AEGIS256_ABYTES;
        }

        return $out;
    }
}
