<?php

declare(strict_types=1);

namespace PHPCompiler\ext\sodium;

/**
 * SODIUM_* extension constants (php-src ext/sodium/sodium.c; issue #13078).
 */
final class SodiumConstants
{
    /** @return array<string, int> */
    public static function registeredConstants(): array
    {
        return [
            'SODIUM_CRYPTO_SECRETBOX_KEYBYTES' => VmSodium::CRYPTO_SECRETBOX_KEYBYTES,
            'SODIUM_CRYPTO_SECRETBOX_NONCEBYTES' => VmSodium::CRYPTO_SECRETBOX_NONCEBYTES,
            'SODIUM_CRYPTO_SECRETBOX_MACBYTES' => VmSodium::CRYPTO_SECRETBOX_MACBYTES,
            'SODIUM_CRYPTO_AUTH_KEYBYTES' => VmSodium::CRYPTO_AUTH_KEYBYTES,
            'SODIUM_CRYPTO_AUTH_BYTES' => VmSodium::CRYPTO_AUTH_BYTES,
            'SODIUM_CRYPTO_STREAM_KEYBYTES' => VmSodium::CRYPTO_STREAM_KEYBYTES,
            'SODIUM_CRYPTO_STREAM_NONCEBYTES' => VmSodium::CRYPTO_STREAM_NONCEBYTES,
            'SODIUM_CRYPTO_STREAM_XCHACHA20_KEYBYTES' => VmSodium::CRYPTO_STREAM_XCHACHA20_KEYBYTES,
            'SODIUM_CRYPTO_STREAM_XCHACHA20_NONCEBYTES' => VmSodium::CRYPTO_STREAM_XCHACHA20_NONCEBYTES,
            'SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_KEYBYTES' => VmSodium::CRYPTO_AEAD_XCHACHA20POLY1305_IETF_KEYBYTES,
            'SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES' => VmSodium::CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES,
            'SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NSECRETBYTES' => VmSodium::CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NSECRETBYTES,
            'SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_ABYTES' => VmSodium::CRYPTO_AEAD_XCHACHA20POLY1305_IETF_ABYTES,
            'SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_KEYBYTES' => VmSodium::CRYPTO_AEAD_CHACHA20POLY1305_KEYBYTES,
            'SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_NPUBBYTES' => VmSodium::CRYPTO_AEAD_CHACHA20POLY1305_NPUBBYTES,
            'SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_NSECBYTES' => VmSodium::CRYPTO_AEAD_CHACHA20POLY1305_NSECRETBYTES,
            'SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_ABYTES' => VmSodium::CRYPTO_AEAD_CHACHA20POLY1305_ABYTES,
            'SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_IETF_KEYBYTES' => VmSodium::CRYPTO_AEAD_CHACHA20POLY1305_IETF_KEYBYTES,
            'SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_IETF_NPUBBYTES' => VmSodium::CRYPTO_AEAD_CHACHA20POLY1305_IETF_NPUBBYTES,
            'SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_IETF_NSECBYTES' => VmSodium::CRYPTO_AEAD_CHACHA20POLY1305_IETF_NSECRETBYTES,
            'SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_IETF_ABYTES' => VmSodium::CRYPTO_AEAD_CHACHA20POLY1305_IETF_ABYTES,
            'SODIUM_CRYPTO_GENERICHASH_BYTES' => VmSodium::CRYPTO_GENERICHASH_BYTES,
            'SODIUM_CRYPTO_GENERICHASH_BYTES_MIN' => VmSodium::CRYPTO_GENERICHASH_BYTES_MIN,
            'SODIUM_CRYPTO_GENERICHASH_BYTES_MAX' => VmSodium::CRYPTO_GENERICHASH_BYTES_MAX,
            'SODIUM_CRYPTO_GENERICHASH_KEYBYTES' => VmSodium::CRYPTO_GENERICHASH_KEYBYTES,
            'SODIUM_CRYPTO_GENERICHASH_KEYBYTES_MIN' => VmSodium::CRYPTO_GENERICHASH_KEYBYTES_MIN,
            'SODIUM_CRYPTO_GENERICHASH_KEYBYTES_MAX' => VmSodium::CRYPTO_GENERICHASH_KEYBYTES_MAX,
            'SODIUM_CRYPTO_SCALARMULT_BYTES' => VmSodium::CRYPTO_SCALARMULT_BYTES,
            'SODIUM_CRYPTO_SCALARMULT_SCALARBYTES' => VmSodium::CRYPTO_SCALARMULT_SCALARBYTES,
            'SODIUM_CRYPTO_BOX_SECRETKEYBYTES' => VmSodium::CRYPTO_BOX_SECRETKEYBYTES,
            'SODIUM_CRYPTO_BOX_PUBLICKEYBYTES' => VmSodium::CRYPTO_BOX_PUBLICKEYBYTES,
            'SODIUM_CRYPTO_BOX_KEYPAIRBYTES' => VmSodium::CRYPTO_BOX_KEYPAIRBYTES,
            'SODIUM_CRYPTO_BOX_MACBYTES' => VmSodium::CRYPTO_BOX_MACBYTES,
            'SODIUM_CRYPTO_BOX_NONCEBYTES' => VmSodium::CRYPTO_BOX_NONCEBYTES,
            'SODIUM_CRYPTO_BOX_SEALBYTES' => VmSodium::CRYPTO_BOX_SEALBYTES,
            'SODIUM_CRYPTO_KX_PUBLICKEYBYTES' => VmSodium::CRYPTO_KX_PUBLICKEYBYTES,
            'SODIUM_CRYPTO_KX_SECRETKEYBYTES' => VmSodium::CRYPTO_KX_SECRETKEYBYTES,
            'SODIUM_CRYPTO_KX_KEYPAIRBYTES' => VmSodium::CRYPTO_KX_KEYPAIRBYTES,
            'SODIUM_CRYPTO_KX_SEEDBYTES' => VmSodium::CRYPTO_KX_SEEDBYTES,
            'SODIUM_CRYPTO_KX_SESSIONKEYBYTES' => VmSodium::CRYPTO_KX_SESSIONKEYBYTES,
            'SODIUM_CRYPTO_AEAD_AES256GCM_KEYBYTES' => VmSodium::CRYPTO_AEAD_AES256GCM_KEYBYTES,
            'SODIUM_CRYPTO_AEAD_AES256GCM_NPUBBYTES' => VmSodium::CRYPTO_AEAD_AES256GCM_NPUBBYTES,
            'SODIUM_CRYPTO_AEAD_AES256GCM_NSECBYTES' => VmSodium::CRYPTO_AEAD_AES256GCM_NSECRETBYTES,
            'SODIUM_CRYPTO_AEAD_AES256GCM_ABYTES' => VmSodium::CRYPTO_AEAD_AES256GCM_ABYTES,
            'SODIUM_CRYPTO_SIGN_BYTES' => VmSodium::CRYPTO_SIGN_BYTES,
            'SODIUM_CRYPTO_SIGN_SEEDBYTES' => VmSodium::CRYPTO_SIGN_SEEDBYTES,
            'SODIUM_CRYPTO_SIGN_PUBLICKEYBYTES' => VmSodium::CRYPTO_SIGN_PUBLICKEYBYTES,
            'SODIUM_CRYPTO_SIGN_SECRETKEYBYTES' => VmSodium::CRYPTO_SIGN_SECRETKEYBYTES,
            'SODIUM_CRYPTO_SIGN_KEYPAIRBYTES' => VmSodium::CRYPTO_SIGN_KEYPAIRBYTES,
            'SODIUM_CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_ABYTES' => VmSodium::CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_ABYTES,
            'SODIUM_CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_HEADERBYTES' => VmSodium::CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_HEADERBYTES,
            'SODIUM_CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_KEYBYTES' => VmSodium::CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_KEYBYTES,
            'SODIUM_CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_TAG_MESSAGE' => VmSodium::CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_TAG_MESSAGE,
            'SODIUM_CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_TAG_PUSH' => VmSodium::CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_TAG_PUSH,
            'SODIUM_CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_TAG_REKEY' => VmSodium::CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_TAG_REKEY,
            'SODIUM_CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_TAG_FINAL' => VmSodium::CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_TAG_FINAL,
            'SODIUM_CRYPTO_SHORTHASH_BYTES' => VmSodium::CRYPTO_SHORTHASH_BYTES,
            'SODIUM_CRYPTO_SHORTHASH_KEYBYTES' => VmSodium::CRYPTO_SHORTHASH_KEYBYTES,
            'SODIUM_CRYPTO_KDF_BYTES_MIN' => VmSodium::CRYPTO_KDF_BYTES_MIN,
            'SODIUM_CRYPTO_KDF_BYTES_MAX' => VmSodium::CRYPTO_KDF_BYTES_MAX,
            'SODIUM_CRYPTO_KDF_CONTEXTBYTES' => VmSodium::CRYPTO_KDF_CONTEXTBYTES,
            'SODIUM_CRYPTO_KDF_KEYBYTES' => VmSodium::CRYPTO_KDF_KEYBYTES,
        ];
    }
}
