#!/usr/bin/env php
<?php

declare(strict_types=1);

$root = dirname(__DIR__);
require $root.'/vendor/autoload.php';

$hasJitLowering = static function (string $source): bool {
    return (bool) preg_match(
        '/JitStringArg|JitLongArg|JitBoolArg|->jitString\s*\(|->jitLong\s*\(|->jitBool\s*\(|'
        .'pow::toJitDouble|JitDate::|JitGetallheaders::|JitPendingHeaders::|constReal\s*\(/',
        $source
    );
};

$isVmOnlyDeferred = static function (string $name, string $source): bool {
    return \PHPCompiler\JIT\SelfHostBuiltinPolicy::isVmOnlyDeferred($name);
};

$rows = [];
foreach (glob($root.'/ext/standard/*.php') as $file) {
    $base = basename($file, '.php');
    if (str_starts_with($base, 'Jit') || str_starts_with($base, 'Vm') || 'Module' === $base) {
        continue;
    }
    $source = (string) file_get_contents($file);
    if (!preg_match('/function\s+call\s*\(/', $source)) {
        continue;
    }
    $name = $base;
    if (preg_match("/parent::__construct\\('\\s*([^']+)\\s*'\\)/", $source, $matches)) {
        $name = $matches[1];
    }
    $deferred = $isVmOnlyDeferred($name, $source);
    $rows[] = [
        'name' => $name,
        'file' => substr($file, strlen($root) + 1),
        'deferred' => $deferred,
        'hasJitArg' => !$deferred && $hasJitLowering($source),
    ];
}
usort($rows, static fn (array $a, array $b): int => strcmp($a['name'], $b['name']));
$deferredRows = array_values(array_filter($rows, static fn (array $row): bool => $row['deferred']));
$missing = array_values(array_filter($rows, static fn (array $row): bool => !$row['deferred'] && !$row['hasJitArg']));
$present = array_values(array_filter($rows, static fn (array $row): bool => !$row['deferred'] && $row['hasJitArg']));

$md = "# Stdlib JIT arg-lowering audit\n\n";
$md .= "Auto-generated by `script/audit-stdlib-jit.php`. Regenerate: `php script/audit-stdlib-jit.php`\n\n";
$md .= "| Metric | Count |\n|--------|------:|\n";
$md .= '| `call()` implementations | '.count($rows)." |\n";
$md .= '| With JitStringArg/JitLongArg (or zero-arg LLVM) | '.count($present)." |\n";
$md .= '| Missing arg helpers (actionable for JIT) | '.count($missing)." |\n";
$md .= '| Deferred (VM-only) | '.count($deferredRows)." |\n";
$md .= '| Self-host auto-stub batch | '.\PHPCompiler\JIT\SelfHostBuiltinPolicy::autoStubBatchCount()." |\n\n";
$md .= "## Missing (sorted)\n\n";
if ([] === $missing) {
    $md .= "_None — all JIT `call()` builtins are lowered or deferred._\n";
} else {
    foreach ($missing as $row) {
        $md .= '- `'.$row['name'].'` — `'.$row['file']."`\n";
    }
}
$md .= "\n## Deferred (VM-only)\n\n";
foreach ($deferredRows as $row) {
    $category = \PHPCompiler\JIT\SelfHostBuiltinPolicy::categoryFor($row['name']) ?? 'vm-only';
    $md .= '- `'.$row['name'].'` ('.$category.') — `'.$row['file']."`\n";
}
$md .= "\n## Present (sorted)\n\n";
foreach ($present as $row) {
    $md .= '- `'.$row['name'].'` — `'.$row['file']."`\n";
}

$outFile = $root.'/docs/stdlib-jit-audit.md';
file_put_contents($outFile, $md);
fwrite(
    STDOUT,
    'Wrote '.$outFile.' (missing='.count($missing).', deferred='.count($deferredRows).', present='.count($present).")\n"
);
