#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Build a gen-0 split-TU chunk plan for parallel/resumable emit (#36387 / #36147).
 *
 * Modes:
 *   --micro[=N]     N tiny echo fixtures (default 4) — gate/orchestrator smoke
 *   --ext=a,b,c     one chunk per extension directory (Zend-loadable autoload preamble)
 *   --plan-out=PATH write JSON (default stdout)
 *   --entries-dir=D where generated entry .php files go (default build/chunks/entries)
 *
 * The plan is consumed by script/bootstrap-gen0-chunks.sh. Receipts live next to
 * objects under CHUNK_OUT_DIR; a fresh fingerprint skips re-emit.
 */

$root = dirname(__DIR__);
$micro = null;
$exts = [];
$planOut = null;
$entriesDir = $root.'/build/chunks/entries';

foreach (array_slice($argv, 1) as $arg) {
    if ($arg === '--micro' || str_starts_with($arg, '--micro=')) {
        $micro = $arg === '--micro' ? 4 : max(1, (int) substr($arg, 8));
        continue;
    }
    if (str_starts_with($arg, '--ext=')) {
        foreach (explode(',', substr($arg, 6)) as $name) {
            $name = trim($name);
            if ($name !== '') {
                $exts[] = $name;
            }
        }
        continue;
    }
    if (str_starts_with($arg, '--plan-out=')) {
        $planOut = substr($arg, 11);
        continue;
    }
    if (str_starts_with($arg, '--entries-dir=')) {
        $entriesDir = substr($arg, 14);
        if ($entriesDir !== '' && $entriesDir[0] !== '/') {
            $entriesDir = $root.'/'.$entriesDir;
        }
        continue;
    }
    fwrite(STDERR, "bootstrap-gen0-chunk-plan: unknown argument {$arg}\n");
    exit(2);
}

if ($micro === null && $exts === []) {
    fwrite(STDERR, "bootstrap-gen0-chunk-plan: pass --micro[=N] and/or --ext=name[,name…]\n");
    exit(2);
}

if (!is_dir($entriesDir) && !mkdir($entriesDir, 0755, true) && !is_dir($entriesDir)) {
    fwrite(STDERR, "bootstrap-gen0-chunk-plan: cannot create {$entriesDir}\n");
    exit(1);
}

$chunks = [];

if ($micro !== null) {
    for ($i = 0; $i < $micro; $i++) {
        $id = sprintf('micro-%02d', $i);
        $entry = $entriesDir.'/'.$id.'.php';
        $body = "<?php\n"
            ."// Generated by bootstrap-gen0-chunk-plan.php — micro split-TU fixture (#36387).\n"
            .'echo "chunk-'.$id.'\n";'."\n";
        if (file_put_contents($entry, $body) === false) {
            fwrite(STDERR, "bootstrap-gen0-chunk-plan: cannot write {$entry}\n");
            exit(1);
        }
        $chunks[] = [
            'chunk_id' => $id,
            'entry' => $entry,
            'kind' => 'micro',
        ];
    }
}

foreach ($exts as $ext) {
    $srcDir = $root.'/ext/'.$ext;
    if (!is_dir($srcDir)) {
        fwrite(STDERR, "bootstrap-gen0-chunk-plan: missing extension {$srcDir}\n");
        exit(1);
    }
    $id = 'ext-'.$ext;
    $entry = $entriesDir.'/'.$id.'.php';
    $lines = [
        '<?php',
        '',
        '// Generated by bootstrap-gen0-chunk-plan.php — spine chunk TU for ext/'.$ext.' (#36387).',
        '// Autoloader first so Zend can load ModuleAbstract / Func\\Internal (spine-chunk-probe trap #1).',
        '',
        "require_once __DIR__ . '/../../../vendor/autoload.php';",
    ];
    $files = [];
    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($srcDir, FilesystemIterator::SKIP_DOTS)
    );
    foreach ($iterator as $fileInfo) {
        if (!$fileInfo->isFile() || $fileInfo->getExtension() !== 'php') {
            continue;
        }
        $files[] = $fileInfo->getPathname();
    }
    sort($files, SORT_STRING);
    if ($files === []) {
        fwrite(STDERR, "bootstrap-gen0-chunk-plan: no .php files under ext/{$ext}\n");
        exit(1);
    }
    foreach ($files as $abs) {
        $rel = substr($abs, strlen($root) + 1);
        $lines[] = "require_once __DIR__ . '/../../../{$rel}';";
    }
    $lines[] = '';
    if (file_put_contents($entry, implode("\n", $lines)."\n") === false) {
        fwrite(STDERR, "bootstrap-gen0-chunk-plan: cannot write {$entry}\n");
        exit(1);
    }
    $chunks[] = [
        'chunk_id' => $id,
        'entry' => $entry,
        'kind' => 'ext',
        'file_count' => count($files),
    ];
}

$plan = [
    'version' => 1,
    'generated_at' => gmdate('c'),
    'root' => $root,
    'entries_dir' => $entriesDir,
    'chunk_count' => count($chunks),
    'chunks' => $chunks,
    'note' => 'Consumed by script/bootstrap-gen0-chunks.sh for parallel object-only emit + resume (#36387).',
];

$json = json_encode($plan, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)."\n";
if ($planOut === null || $planOut === '-' || $planOut === '') {
    fwrite(STDOUT, $json);
    exit(0);
}
$dir = dirname($planOut);
if ($dir !== '' && $dir !== '.' && !is_dir($dir) && !mkdir($dir, 0755, true) && !is_dir($dir)) {
    fwrite(STDERR, "bootstrap-gen0-chunk-plan: cannot create {$dir}\n");
    exit(1);
}
if (file_put_contents($planOut, $json) === false) {
    fwrite(STDERR, "bootstrap-gen0-chunk-plan: cannot write {$planOut}\n");
    exit(1);
}
fwrite(STDOUT, "bootstrap-gen0-chunk-plan: wrote {$planOut} ({$plan['chunk_count']} chunks)\n");
exit(0);
