<?php

declare(strict_types=1);

/**
 * M5 vendor prelink helpers (issue #1416).
 */

/** @var array<string, string> */
const BOOTSTRAP_VENDOR_PRELINK_PACKAGES = [
    'ircmaxell/php-cfg' => 'CFG + traversers',
    'ircmaxell/php-types' => 'TypeReconstructor',
    'ircmaxell/php-llvm' => 'LLVM FFI from PHP JIT',
];

/**
 * @return list<string> repo-relative paths under vendor/<package>/lib
 */
function bootstrapVendorPrelinkLibPhpFiles(string $root, string $package): array
{
    $libDir = $root.'/vendor/'.$package.'/lib';
    if (!is_dir($libDir)) {
        return [];
    }
    $paths = [];
    $it = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($libDir, FilesystemIterator::SKIP_DOTS)
    );
    foreach ($it as $file) {
        if (!$file->isFile() || !str_ends_with(strtolower($file->getFilename()), '.php')) {
            continue;
        }
        $paths[] = ltrim(str_replace('\\', '/', substr($file->getPathname(), strlen($root))), '/');
    }
    sort($paths);

    return $paths;
}

function bootstrapVendorPrelinkSlug(string $package): string
{
    return str_replace('/', '-', $package);
}

/**
 * @param list<string> $vendorRelPaths repo-relative vendor/*.php paths
 */
function bootstrapVendorPrelinkRenderBundle(
    string $package,
    string $role,
    array $vendorRelPaths,
    string $bundleRelPath
): string {
    $lines = [];
    $lines[] = '<?php';
    $lines[] = '';
    $lines[] = 'declare(strict_types=1);';
    $lines[] = '';
    $lines[] = '/**';
    $lines[] = ' * M5 vendor prelink bundle: `'.$package.'` ('.$role.').';
    $lines[] = ' * Auto-generated by `script/bootstrap-vendor-objects.php` — do not edit.';
    $lines[] = ' * Issue #1416.';
    $lines[] = ' */';
    $lines[] = '';
    foreach ($vendorRelPaths as $rel) {
        $lines[] = "require_once __DIR__.'/../../../{$rel}';";
    }
    $lines[] = '';
    $lines[] = "echo 'bootstrap-vendor-prelink ".bootstrapVendorPrelinkSlug($package)." OK\\n';";
    $lines[] = '';

    return implode("\n", $lines)."\n";
}

/**
 * @return array{version: int, generated_at: string, packages: array<string, array<string, mixed>>}
 */
function bootstrapVendorPrelinkEmptyManifest(string $root): array
{
    $packages = [];
    foreach (BOOTSTRAP_VENDOR_PRELINK_PACKAGES as $package => $role) {
        $slug = bootstrapVendorPrelinkSlug($package);
        $files = bootstrapVendorPrelinkLibPhpFiles($root, $package);
        $packages[$package] = [
            'role' => $role,
            'slug' => $slug,
            'bundle' => 'test/bootstrap-vendor-prelink/generated/'.$slug.'_bundle.php',
            'object' => 'prelinked/bootstrap-vendor/'.$slug.'.o',
            'archive' => 'prelinked/bootstrap-vendor/'.$slug.'.a',
            'php_files' => count($files),
            'status' => 'pending',
            'blocker' => null,
        ];
    }

    return [
        'version' => 1,
        'generated_at' => gmdate('c'),
        'packages' => $packages,
    ];
}

/**
 * @param array{version: int, generated_at: string, packages: array<string, array<string, mixed>>} $manifest
 */
function bootstrapVendorPrelinkWriteManifest(string $path, array $manifest): void
{
    $manifest['generated_at'] = gmdate('c');
    $json = json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)."\n";
    $dir = dirname($path);
    if (!is_dir($dir)) {
        mkdir($dir, 0775, true);
    }
    file_put_contents($path, $json);
}

/**
 * @return array{version: int, generated_at: string, packages: array<string, array<string, mixed>>}|null
 */
function bootstrapVendorPrelinkReadManifest(string $path): ?array
{
    if (!is_file($path)) {
        return null;
    }
    $data = json_decode((string) file_get_contents($path), true);

    return is_array($data) ? $data : null;
}

/**
 * @return list<string> repo-relative object paths that exist on disk
 */
function bootstrapVendorPrelinkExistingObjects(string $root, array $manifest): array
{
    $found = [];
    foreach ($manifest['packages'] as $info) {
        if (!is_array($info)) {
            continue;
        }
        $rel = $info['object'] ?? '';
        if (!is_string($rel) || '' === $rel) {
            continue;
        }
        $abs = $root.'/'.$rel;
        if (is_file($abs)) {
            $found[] = $rel;
        }
    }

    return $found;
}

function bootstrapVendorPrelinkVendorTreePresent(string $root): bool
{
    foreach (array_keys(BOOTSTRAP_VENDOR_PRELINK_PACKAGES) as $package) {
        if (!is_dir($root.'/vendor/'.$package)) {
            return false;
        }
    }

    return is_file($root.'/vendor/autoload.php');
}

/**
 * M5 cold boot: verify committed bundles + manifest without regenerating from vendor/ (#2841).
 *
 * @param array{version: int, generated_at: string, packages: array<string, array<string, mixed>>} $manifest
 */
function bootstrapVendorPrelinkColdBootCheck(string $root, string $manifestPath, array $manifest): int
{
    if (!is_file($manifestPath)) {
        fwrite(STDERR, "Missing {$manifestPath}; cold boot requires committed manifest\n");

        return 1;
    }

    foreach (BOOTSTRAP_VENDOR_PRELINK_PACKAGES as $package => $role) {
        $slug = bootstrapVendorPrelinkSlug($package);
        $bundleRel = 'test/bootstrap-vendor-prelink/generated/'.$slug.'_bundle.php';
        $bundleAbs = $root.'/'.$bundleRel;
        if (!is_file($bundleAbs)) {
            fwrite(STDERR, "Missing bundle {$bundleRel}; cold boot requires committed vendor prelink bundles\n");

            return 1;
        }
        $bundleBody = (string) file_get_contents($bundleAbs);
        if (!str_contains($bundleBody, "vendor/{$package}/")) {
            fwrite(STDERR, "Bundle {$bundleRel} does not reference vendor/{$package} sources\n");

            return 1;
        }
        $expectedFiles = (int) ($manifest['packages'][$package]['php_files'] ?? 0);
        if ($expectedFiles <= 0) {
            fwrite(STDERR, "Manifest php_files for {$package} must be > 0 for cold boot\n");

            return 1;
        }
        $requireCount = substr_count($bundleBody, 'require_once');
        if ($requireCount < $expectedFiles) {
            fwrite(STDERR, "Bundle {$bundleRel} has {$requireCount} require_once lines; manifest expects {$expectedFiles}\n");

            return 1;
        }
    }

    return 0;
}

/**
 * When vendor/ is absent, reuse committed prelinked .o artifacts instead of Zend rebuild (#2841).
 *
 * @param array{version: int, generated_at: string, packages: array<string, array<string, mixed>>} $manifest
 *
 * @return int exit code (0 = all packages satisfied from disk)
 */
function bootstrapVendorPrelinkColdBootCompileFromCommitted(string $root, string $manifestPath, array &$manifest): int
{
    $failures = 0;
    foreach (BOOTSTRAP_VENDOR_PRELINK_PACKAGES as $package => $role) {
        $slug = bootstrapVendorPrelinkSlug($package);
        $objectRel = $manifest['packages'][$package]['object'] ?? '';
        if (!is_string($objectRel) || '' === $objectRel) {
            ++$failures;
            continue;
        }
        $objectAbs = $root.'/'.$objectRel;
        if (!is_file($objectAbs)) {
            $manifest['packages'][$package]['status'] = 'missing_object';
            $manifest['packages'][$package]['blocker'] = 'cold boot: committed '.$objectRel.' missing (restore vendor/ for rebuild — #2849)';
            ++$failures;
            continue;
        }
        $manifest['packages'][$package]['status'] = 'object_ok';
        $manifest['packages'][$package]['blocker'] = null;
        fwrite(STDOUT, "OK {$package} → {$objectRel} (cold boot: committed prelink)\n");
    }

    bootstrapVendorPrelinkWriteManifest($manifestPath, $manifest);

    if ($failures > 0) {
        fwrite(STDERR, "bootstrap-vendor-objects: {$failures} package(s) missing committed prelink .o (vendor/ absent)\n");

        return 1;
    }

    fwrite(STDOUT, "bootstrap-vendor-objects: cold boot — all prelink objects from committed artifacts\n");

    return 0;
}

/**
 * Resolve gen-0 vendor prelink AOT invoker: compiled driver when present, else Zend php bin/compile.php (#2842, #2849).
 *
 * @return array{mode: 'native'|'zend', argv: list<string>}
 */
function bootstrapVendorPrelinkResolveCompileInvoker(string $root): array
{
    if ('1' === (string) getenv('BOOTSTRAP_GEN0_ZEND_ONLY')) {
        return [
            'mode' => 'zend',
            'argv' => [PHP_BINARY, $root.'/bin/compile.php'],
        ];
    }

    foreach ([
        $root.'/build/selfhost-compile-driver',
        $root.'/build/selfhost-native-compile-driver',
        $root.'/build/bin-compile-aot',
    ] as $candidate) {
        if (is_executable($candidate)) {
            return [
                'mode' => 'native',
                'argv' => [$candidate],
            ];
        }
    }

    return [
        'mode' => 'zend',
        'argv' => [PHP_BINARY, $root.'/bin/compile.php'],
    ];
}

/** Shell command for vendor bundle AOT → .o (env + driver + -o + entry). */
function bootstrapVendorPrelinkBuildCompileCommand(
    string $root,
    string $buildBase,
    string $bundleAbs
): string {
    $inv = bootstrapVendorPrelinkResolveCompileInvoker($root);
    $argv = array_map('escapeshellarg', $inv['argv']);

    return 'PHP_COMPILER_VENDOR_PRELINK=1 PHP_COMPILER_SELFHOST_AOT=0 PHP_COMPILER_KEEP_OBJECT_FILE=1 '
        .implode(' ', $argv)
        .' -o '.escapeshellarg($buildBase)
        .' '.escapeshellarg($bundleAbs)
        .' 2>&1';
}
