<?php

declare(strict_types=1);

/**
 * Generate a minimized self-host spine entry for bisecting segfaults in compiled drivers.
 *
 * Intended for the inventory argv driver crash in `bootstrap-selfhost-lib-spine-smoke` (#2967 / #2989).
 *
 * Usage:
 *   php script/bootstrap-spine-minimize-entry.php --in test/selfhost/compiler_lib_spine_smoke/main.php --out build/spine-min.php --limit 50
 */

$in = null;
$out = null;
$limit = null;

for ($i = 1; $i < $argc; $i++) {
    $arg = $argv[$i];
    if ('--in' === $arg && isset($argv[$i + 1])) {
        $in = $argv[++$i];
        continue;
    }
    if ('--out' === $arg && isset($argv[$i + 1])) {
        $out = $argv[++$i];
        continue;
    }
    if ('--limit' === $arg && isset($argv[$i + 1])) {
        $limit = (int) $argv[++$i];
        continue;
    }
}

if (!is_string($in) || '' === $in || !is_string($out) || '' === $out || !is_int($limit) || $limit <= 0) {
    fwrite(STDERR, "bootstrap-spine-minimize-entry: expected --in <path> --out <path> --limit <n>\n");
    exit(2);
}
if (!is_file($in)) {
    fwrite(STDERR, "bootstrap-spine-minimize-entry: missing input file {$in}\n");
    exit(2);
}

$lines = file($in, FILE_IGNORE_NEW_LINES);
if (false === $lines) {
    fwrite(STDERR, "bootstrap-spine-minimize-entry: failed to read {$in}\n");
    exit(2);
}

$header = [];
$requires = [];
foreach ($lines as $line) {
    if (str_starts_with($line, 'require_once ')) {
        $requires[] = $line;
        continue;
    }
    // Keep the top-of-file prologue until the first require_once.
    if ([] === $requires) {
        $header[] = $line;
    }
}

if ([] === $requires) {
    fwrite(STDERR, "bootstrap-spine-minimize-entry: no require_once lines found in {$in}\n");
    exit(2);
}

$requires = array_slice($requires, 0, $limit);

$dir = dirname($out);
if ('' !== $dir && !is_dir($dir) && !@mkdir($dir, 0775, true) && !is_dir($dir)) {
    fwrite(STDERR, "bootstrap-spine-minimize-entry: failed to create output dir {$dir}\n");
    exit(2);
}

$content = implode("\n", $header)."\n\n";
$content .= "/**\n";
$content .= " * GENERATED by script/bootstrap-spine-minimize-entry.php\n";
$content .= " * Source: {$in}\n";
$content .= " * Limit: {$limit}\n";
$content .= " */\n\n";
$content .= implode("\n", $requires)."\n";

if (false === file_put_contents($out, $content)) {
    fwrite(STDERR, "bootstrap-spine-minimize-entry: failed to write {$out}\n");
    exit(2);
}

fwrite(STDERR, "bootstrap-spine-minimize-entry: wrote {$out} ({$limit} require_once)\n");

