<?php

declare(strict_types=1);

/**
 * M5 vendor prelink helpers (issue #1416).
 */

/** @var array<string, string> */
const BOOTSTRAP_VENDOR_PRELINK_PACKAGES = [
    'ircmaxell/php-cfg' => 'CFG + traversers',
    'ircmaxell/php-types' => 'TypeReconstructor',
    'ircmaxell/php-llvm' => 'LLVM FFI from PHP JIT',
];

/**
 * @return list<string> repo-relative paths under vendor/<package>/lib
 */
function bootstrapVendorPrelinkLibPhpFiles(string $root, string $package): array
{
    $libDir = $root.'/vendor/'.$package.'/lib';
    if (!is_dir($libDir)) {
        return [];
    }
    $paths = [];
    $it = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($libDir, FilesystemIterator::SKIP_DOTS)
    );
    foreach ($it as $file) {
        if (!$file->isFile() || !str_ends_with(strtolower($file->getFilename()), '.php')) {
            continue;
        }
        $paths[] = ltrim(str_replace('\\', '/', substr($file->getPathname(), strlen($root))), '/');
    }
    sort($paths);

    return $paths;
}

function bootstrapVendorPrelinkSlug(string $package): string
{
    return str_replace('/', '-', $package);
}

/**
 * @param list<string> $vendorRelPaths repo-relative vendor/*.php paths
 */
function bootstrapVendorPrelinkRenderBundle(
    string $package,
    string $role,
    array $vendorRelPaths,
    string $bundleRelPath
): string {
    $lines = [];
    $lines[] = '<?php';
    $lines[] = '';
    $lines[] = 'declare(strict_types=1);';
    $lines[] = '';
    $lines[] = '/**';
    $lines[] = ' * M5 vendor prelink bundle: `'.$package.'` ('.$role.').';
    $lines[] = ' * Auto-generated by `script/bootstrap-vendor-objects.php` — do not edit.';
    $lines[] = ' * Issue #1416.';
    $lines[] = ' */';
    $lines[] = '';
    foreach ($vendorRelPaths as $rel) {
        $lines[] = "require_once __DIR__.'/../../../{$rel}';";
    }
    $lines[] = '';
    $lines[] = "echo 'bootstrap-vendor-prelink ".bootstrapVendorPrelinkSlug($package)." OK\\n';";
    $lines[] = '';

    return implode("\n", $lines)."\n";
}

/**
 * @return array{version: int, generated_at: string, packages: array<string, array<string, mixed>>}
 */
function bootstrapVendorPrelinkEmptyManifest(string $root): array
{
    $packages = [];
    foreach (BOOTSTRAP_VENDOR_PRELINK_PACKAGES as $package => $role) {
        $slug = bootstrapVendorPrelinkSlug($package);
        $files = bootstrapVendorPrelinkLibPhpFiles($root, $package);
        $packages[$package] = [
            'role' => $role,
            'slug' => $slug,
            'bundle' => 'test/bootstrap-vendor-prelink/generated/'.$slug.'_bundle.php',
            'object' => 'prelinked/bootstrap-vendor/'.$slug.'.o',
            'archive' => 'prelinked/bootstrap-vendor/'.$slug.'.a',
            'php_files' => count($files),
            'status' => 'pending',
            'blocker' => null,
        ];
    }

    return [
        'version' => 1,
        'generated_at' => gmdate('c'),
        'packages' => $packages,
    ];
}

/**
 * @param array{version: int, generated_at: string, packages: array<string, array<string, mixed>>} $manifest
 */
function bootstrapVendorPrelinkWriteManifest(string $path, array $manifest): void
{
    $manifest['generated_at'] = gmdate('c');
    $json = json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)."\n";
    $dir = dirname($path);
    if (!is_dir($dir)) {
        mkdir($dir, 0775, true);
    }
    file_put_contents($path, $json);
}

/**
 * @return array{version: int, generated_at: string, packages: array<string, array<string, mixed>>}|null
 */
function bootstrapVendorPrelinkReadManifest(string $path): ?array
{
    if (!is_file($path)) {
        return null;
    }
    $data = json_decode((string) file_get_contents($path), true);

    return is_array($data) ? $data : null;
}

/**
 * @return list<string> repo-relative object paths that exist on disk
 */
function bootstrapVendorPrelinkExistingObjects(string $root, array $manifest): array
{
    $found = [];
    foreach ($manifest['packages'] as $info) {
        if (!is_array($info)) {
            continue;
        }
        $rel = $info['object'] ?? '';
        if (!is_string($rel) || '' === $rel) {
            continue;
        }
        $abs = $root.'/'.$rel;
        if (is_file($abs)) {
            $found[] = $rel;
        }
    }

    return $found;
}
