<?php

declare(strict_types=1);

/**
 * M5 vendor prelink helpers (issue #1416).
 */

/** @var array<string, string> */
const BOOTSTRAP_VENDOR_PRELINK_PACKAGES = [
    'ircmaxell/php-cfg' => 'CFG + traversers',
    'ircmaxell/php-types' => 'TypeReconstructor',
    'ircmaxell/php-llvm' => 'LLVM FFI from PHP JIT',
];

/** Zend compile-driver deps materialized for cold-boot rebuild without composer (#2881). */
const BOOTSTRAP_VENDOR_PRELINK_DRIVER_PACKAGES = [
    'nikic/php-parser',
];

/**
 * @return list<string> repo-relative paths under vendor/<package>/lib
 */
function bootstrapVendorPrelinkSourcesRoot(string $root): string
{
    return $root.'/prelinked/bootstrap-vendor/sources';
}

/** Committed vendor lib/ snapshot for cold-boot AOT rebuild without composer (#2881). */
function bootstrapVendorPrelinkSourcesTreePresent(string $root): bool
{
    foreach (array_keys(BOOTSTRAP_VENDOR_PRELINK_PACKAGES) as $package) {
        $base = bootstrapVendorPrelinkSourcesRoot($root).'/'.$package;
        if (!is_dir($base.'/lib')) {
            return false;
        }
        if ('ircmaxell/php-llvm' === $package && !is_dir($base.'/ffi')) {
            return false;
        }
    }
    foreach (BOOTSTRAP_VENDOR_PRELINK_DRIVER_PACKAGES as $package) {
        if (!is_dir(bootstrapVendorPrelinkSourcesRoot($root).'/'.$package.'/lib')) {
            return false;
        }
    }

    return true;
}

function bootstrapVendorPrelinkLibPhpFiles(string $root, string $package): array
{
    $libDir = $root.'/vendor/'.$package.'/lib';
    if (!is_dir($libDir)) {
        $libDir = bootstrapVendorPrelinkSourcesRoot($root).'/'.$package.'/lib';
    }
    if (!is_dir($libDir)) {
        return [];
    }
    $paths = [];
    $it = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($libDir, FilesystemIterator::SKIP_DOTS)
    );
    foreach ($it as $file) {
        if (!$file->isFile() || !str_ends_with(strtolower($file->getFilename()), '.php')) {
            continue;
        }
        $paths[] = ltrim(str_replace('\\', '/', substr($file->getPathname(), strlen($root))), '/');
    }
    sort($paths);

    return $paths;
}

function bootstrapVendorPrelinkSlug(string $package): string
{
    return str_replace('/', '-', $package);
}

/**
 * Reuse link-time emit-helper or committed prelinked .o when native argv compile cannot (#3028).
 *
 * @return 'link-time'|'committed'|null
 */
function bootstrapVendorPrelinkCopySidecarFallback(string $root, string $slug, string $objectAbs): ?string
{
    $vendorShort = str_replace('-', '_', preg_replace('/^ircmaxell-/', '', $slug));
    $linktimeObject = $root.'/build/.m3_vendor_'.$vendorShort.'_prelink.o';
    if (is_file($linktimeObject)) {
        copy($linktimeObject, $objectAbs);

        return 'link-time';
    }
    $committedObject = $root.'/prelinked/bootstrap-vendor/'.$slug.'.o';
    if (is_file($committedObject)) {
        if (realpath($committedObject) !== realpath($objectAbs)) {
            copy($committedObject, $objectAbs);
        }

        return 'committed';
    }

    return null;
}

/**
 * @param list<string> $vendorRelPaths repo-relative vendor/*.php paths
 */
function bootstrapVendorPrelinkRenderBundle(
    string $package,
    string $role,
    array $vendorRelPaths,
    string $bundleRelPath
): string {
    $lines = [];
    $lines[] = '<?php';
    $lines[] = '';
    $lines[] = 'declare(strict_types=1);';
    $lines[] = '';
    $lines[] = '/**';
    $lines[] = ' * M5 vendor prelink bundle: `'.$package.'` ('.$role.').';
    $lines[] = ' * Auto-generated by `script/bootstrap-vendor-objects.php` — do not edit.';
    $lines[] = ' * Issue #1416.';
    $lines[] = ' */';
    $lines[] = '';
    foreach ($vendorRelPaths as $rel) {
        $lines[] = "require_once __DIR__.'/../../../{$rel}';";
    }
    $lines[] = '';
    $lines[] = "echo 'bootstrap-vendor-prelink ".bootstrapVendorPrelinkSlug($package)." OK\\n';";
    $lines[] = '';

    return implode("\n", $lines)."\n";
}

/**
 * @return array{version: int, generated_at: string, packages: array<string, array<string, mixed>>}
 */
function bootstrapVendorPrelinkEmptyManifest(string $root): array
{
    $packages = [];
    foreach (BOOTSTRAP_VENDOR_PRELINK_PACKAGES as $package => $role) {
        $slug = bootstrapVendorPrelinkSlug($package);
        $files = bootstrapVendorPrelinkLibPhpFiles($root, $package);
        $packages[$package] = [
            'role' => $role,
            'slug' => $slug,
            'bundle' => 'test/bootstrap-vendor-prelink/generated/'.$slug.'_bundle.php',
            'object' => 'prelinked/bootstrap-vendor/'.$slug.'.o',
            'archive' => 'prelinked/bootstrap-vendor/'.$slug.'.a',
            'php_files' => count($files),
            'status' => 'pending',
            'blocker' => null,
        ];
    }

    return [
        'version' => 1,
        'generated_at' => gmdate('c'),
        'packages' => $packages,
    ];
}

/**
 * @param array{version: int, generated_at: string, packages: array<string, array<string, mixed>>} $manifest
 */
function bootstrapVendorPrelinkWriteManifest(string $path, array $manifest): void
{
    $manifest['generated_at'] = gmdate('c');
    $json = json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)."\n";
    $dir = dirname($path);
    if (!is_dir($dir)) {
        mkdir($dir, 0775, true);
    }
    file_put_contents($path, $json);
}

/**
 * @return array{version: int, generated_at: string, packages: array<string, array<string, mixed>>}|null
 */
function bootstrapVendorPrelinkReadManifest(string $path): ?array
{
    if (!is_file($path)) {
        return null;
    }
    $data = json_decode((string) file_get_contents($path), true);

    return is_array($data) ? $data : null;
}

/**
 * @return list<string> repo-relative object paths that exist on disk
 */
function bootstrapVendorPrelinkExistingObjects(string $root, array $manifest): array
{
    $found = [];
    foreach ($manifest['packages'] as $info) {
        if (!is_array($info)) {
            continue;
        }
        $rel = $info['object'] ?? '';
        if (!is_string($rel) || '' === $rel) {
            continue;
        }
        $abs = $root.'/'.$rel;
        if (is_file($abs)) {
            $found[] = $rel;
        }
    }

    return $found;
}

function bootstrapVendorPrelinkVendorTreePresent(string $root): bool
{
    foreach (array_keys(BOOTSTRAP_VENDOR_PRELINK_PACKAGES) as $package) {
        if (!is_dir($root.'/vendor/'.$package)) {
            return false;
        }
    }

    return is_file($root.'/vendor/autoload.php');
}

/**
 * M5 cold boot: verify committed bundles + manifest without regenerating from vendor/ (#2841).
 *
 * @param array{version: int, generated_at: string, packages: array<string, array<string, mixed>>} $manifest
 */
function bootstrapVendorPrelinkColdBootCheck(string $root, string $manifestPath, array $manifest): int
{
    if (!is_file($manifestPath)) {
        fwrite(STDERR, "Missing {$manifestPath}; cold boot requires committed manifest\n");

        return 1;
    }

    foreach (BOOTSTRAP_VENDOR_PRELINK_PACKAGES as $package => $role) {
        $slug = bootstrapVendorPrelinkSlug($package);
        $bundleRel = 'test/bootstrap-vendor-prelink/generated/'.$slug.'_bundle.php';
        $bundleAbs = $root.'/'.$bundleRel;
        if (!is_file($bundleAbs)) {
            fwrite(STDERR, "Missing bundle {$bundleRel}; cold boot requires committed vendor prelink bundles\n");

            return 1;
        }
        $bundleBody = (string) file_get_contents($bundleAbs);
        if (!str_contains($bundleBody, "vendor/{$package}/")) {
            fwrite(STDERR, "Bundle {$bundleRel} does not reference vendor/{$package} sources\n");

            return 1;
        }
        $expectedFiles = (int) ($manifest['packages'][$package]['php_files'] ?? 0);
        if ($expectedFiles <= 0) {
            fwrite(STDERR, "Manifest php_files for {$package} must be > 0 for cold boot\n");

            return 1;
        }
        $requireCount = substr_count($bundleBody, 'require_once');
        if ($requireCount < $expectedFiles) {
            fwrite(STDERR, "Bundle {$bundleRel} has {$requireCount} require_once lines; manifest expects {$expectedFiles}\n");

            return 1;
        }
    }

    return 0;
}

/**
 * Symlink vendor/ircmaxell/* → committed sources when composer tree is absent (#2881).
 *
 * @return string|null marker file when materialized (caller must cleanup)
 */
function bootstrapVendorPrelinkMaterializeVendorTree(string $root): ?string
{
    if (bootstrapVendorPrelinkVendorTreePresent($root)) {
        return null;
    }
    if (!bootstrapVendorPrelinkSourcesTreePresent($root)) {
        return null;
    }

    $marker = $root.'/build/bootstrap-vendor/.vendor-materialized';
    $sources = bootstrapVendorPrelinkSourcesRoot($root);
    $vendorIrc = $root.'/vendor/ircmaxell';
    if (!is_dir($root.'/vendor')) {
        mkdir($root.'/vendor', 0775, true);
    }
    if (!is_dir($vendorIrc)) {
        mkdir($vendorIrc, 0775, true);
    }

    $packages = [...array_keys(BOOTSTRAP_VENDOR_PRELINK_PACKAGES), ...BOOTSTRAP_VENDOR_PRELINK_DRIVER_PACKAGES];
    foreach ($packages as $package) {
        $target = $root.'/vendor/'.$package;
        $source = $sources.'/'.$package;
        $parent = dirname($target);
        if (!is_dir($parent)) {
            mkdir($parent, 0775, true);
        }
        if (is_link($target) || is_dir($target)) {
            if (is_link($target)) {
                unlink($target);
            } elseif (is_dir($target) && !str_starts_with(realpath($target) ?: '', realpath($source) ?: "\0")) {
                fwrite(STDERR, "bootstrap-vendor-prelink: vendor/{$package} exists and is not a symlink to sources\n");

                return null;
            } else {
                continue;
            }
        }
        $rel = bootstrapVendorPrelinkRelativePath($target, $source);
        if (!symlink($rel, $target)) {
            fwrite(STDERR, "bootstrap-vendor-prelink: failed to symlink vendor/{$package} → sources\n");

            return null;
        }
    }

    $markerDir = dirname($marker);
    if (!is_dir($markerDir)) {
        mkdir($markerDir, 0775, true);
    }
    file_put_contents($marker, gmdate('c')."\n");

    return $marker;
}

function bootstrapVendorPrelinkCleanupMaterializedVendorTree(string $root, ?string $marker): void
{
    if (null === $marker || !is_file($marker)) {
        return;
    }

    $packages = [...array_keys(BOOTSTRAP_VENDOR_PRELINK_PACKAGES), ...BOOTSTRAP_VENDOR_PRELINK_DRIVER_PACKAGES];
    foreach ($packages as $package) {
        $target = $root.'/vendor/'.$package;
        if (is_link($target)) {
            unlink($target);
        }
    }
    @rmdir($root.'/vendor/ircmaxell');
    @rmdir($root.'/vendor/nikic');
    if (is_dir($root.'/vendor') && [] === array_diff(scandir($root.'/vendor') ?: [], ['.', '..'])) {
        @rmdir($root.'/vendor');
    }
    @unlink($marker);
}

function bootstrapVendorPrelinkRelativePath(string $linkPath, string $targetPath): string
{
    $fromReal = realpath(dirname($linkPath)) ?: dirname($linkPath);
    $toReal = realpath($targetPath) ?: $targetPath;
    $fromParts = explode('/', str_replace('\\', '/', $fromReal));
    $toParts = explode('/', str_replace('\\', '/', $toReal));
    while ([] !== $fromParts && [] !== $toParts && $fromParts[0] === $toParts[0]) {
        array_shift($fromParts);
        array_shift($toParts);
    }
    $ups = array_fill(0, count($fromParts), '..');
    $rel = array_merge($ups, $toParts);

    return implode('/', $rel);
}

/**
 * AOT-compile vendor prelink bundles → prelinked .o (shared by warm and cold boot).
 *
 * @param array{version: int, generated_at: string, packages: array<string, array<string, mixed>>} $manifest
 *
 * @return int number of failures
 */
/**
 * @param list<string>|null $onlyPackages restrict to these package names (e.g. cold-boot rebuild subset)
 */
/**
 * @param array{mode: 'native'|'zend', argv: list<string>}|null $invoker
 */
function bootstrapVendorPrelinkCompilePackages(
    string $root,
    array &$manifest,
    ?string $one = null,
    ?array $onlyPackages = null,
    ?array $invoker = null
): int {
    $failures = 0;
    foreach (BOOTSTRAP_VENDOR_PRELINK_PACKAGES as $package => $role) {
        if (null !== $onlyPackages && !in_array($package, $onlyPackages, true)) {
            continue;
        }
        if (null !== $one && $one !== $package && $one !== bootstrapVendorPrelinkSlug($package)) {
            continue;
        }
        $slug = bootstrapVendorPrelinkSlug($package);
        $bundleRel = $manifest['packages'][$package]['bundle'] ?? '';
        $bundleAbs = $root.'/'.$bundleRel;
        $objectRel = $manifest['packages'][$package]['object'] ?? '';
        $objectAbs = $root.'/'.$objectRel;
        $buildBase = $root.'/build/bootstrap-vendor/'.$slug;

        if (!is_string($bundleRel) || '' === $bundleRel || !is_file($bundleAbs)) {
            $manifest['packages'][$package]['status'] = 'missing_bundle';
            ++$failures;
            continue;
        }
        if (!is_string($objectRel) || '' === $objectRel) {
            ++$failures;
            continue;
        }

        if (!is_dir(dirname($buildBase))) {
            mkdir(dirname($buildBase), 0775, true);
        }
        if (!is_dir(dirname($objectAbs))) {
            mkdir(dirname($objectAbs), 0775, true);
        }

        @unlink($buildBase);
        @unlink($buildBase.'.o');
        // Keep committed prelinked .o until we have a replacement (fallback copies from it; #3028).

        $cmd = bootstrapVendorPrelinkBuildCompileCommand($root, $buildBase, $bundleAbs, $invoker);
        $output = [];
        exec($cmd, $output, $code);
        $objectCandidate = $buildBase.'.o';

        if (0 === $code && is_file($objectCandidate)) {
            copy($objectCandidate, $objectAbs);
            $manifest['packages'][$package]['status'] = 'object_ok';
            $manifest['packages'][$package]['blocker'] = null;
            fwrite(STDOUT, "OK {$package} → {$objectRel}\n");
            continue;
        }
        if (0 === $code && !is_file($objectCandidate) && is_file($buildBase.'.o')) {
            copy($buildBase.'.o', $objectAbs);
            $manifest['packages'][$package]['status'] = 'object_ok';
            $manifest['packages'][$package]['blocker'] = null;
            fwrite(STDOUT, "OK {$package} → {$objectRel} (native compile)\n");
            continue;
        }

        $sidecarSource = bootstrapVendorPrelinkCopySidecarFallback($root, $slug, $objectAbs);
        if (null !== $sidecarSource) {
            $manifest['packages'][$package]['status'] = 'object_ok';
            $manifest['packages'][$package]['blocker'] = null;
            $via = 'link-time' === $sidecarSource ? 'link-time vendor sidecar' : 'committed prelink';
            fwrite(STDOUT, "OK {$package} → {$objectRel} ({$via})\n");
            continue;
        }

        $blocker = 0 !== $code
            ? 'compile exit '.$code.' (vendor bundle AOT — #1416, #2849)'
            : 'missing object file after compile';

        $firstActionable = null;
        foreach ($output as $line) {
            $line = (string) $line;
            if (str_contains($line, 'Missing vendor autoload')) {
                $firstActionable = $line;
                $blocker = 'vendor prelink must not require composer autoload (#2849)';
                break;
            }
            if (str_contains($line, 'PHP Fatal error:') || str_contains($line, 'Fatal error:') || str_contains($line, 'Uncaught ')) {
                $firstActionable = $line;
                break;
            }
        }
        if (null === $firstActionable && [] !== $output) {
            $last = (string) end($output);
            if ('' !== $last) {
                $firstActionable = $last;
            }
        }
        if (null !== $firstActionable) {
            $blocker .= ' — '.$firstActionable;
        }

        $logPath = $buildBase.'.log';
        file_put_contents($logPath, implode("\n", array_map('strval', $output))."\n");
        $manifest['packages'][$package]['status'] = 139 === $code ? 'compile_segfault' : 'compile_failed';
        $manifest['packages'][$package]['blocker'] = $blocker;
        fwrite(STDERR, "FAIL {$package}: {$blocker}\n");
        fwrite(STDERR, "  cmd: {$cmd}\n");
        fwrite(STDERR, "  log: {$logPath}\n");
        if ([] !== $output) {
            $tail = array_slice($output, -60);
            fwrite(STDERR, "  tail:\n");
            foreach ($tail as $line) {
                fwrite(STDERR, "    ".(string) $line."\n");
            }
        }
        ++$failures;
    }

    return $failures;
}

/**
 * Cold boot: reuse committed .o or AOT-rebuild missing ones via sources snapshot (#2841, #2881).
 *
 * @param array{version: int, generated_at: string, packages: array<string, array<string, mixed>>} $manifest
 */
function bootstrapVendorPrelinkColdBootCompile(string $root, string $manifestPath, array &$manifest, ?string $one = null): int
{
    $needsRebuild = [];
    foreach (BOOTSTRAP_VENDOR_PRELINK_PACKAGES as $package => $role) {
        if (null !== $one && $one !== $package && $one !== bootstrapVendorPrelinkSlug($package)) {
            continue;
        }
        $objectRel = $manifest['packages'][$package]['object'] ?? '';
        if (!is_string($objectRel) || '' === $objectRel) {
            $needsRebuild[] = $package;
            continue;
        }
        if (!is_file($root.'/'.$objectRel)) {
            $needsRebuild[] = $package;
        }
    }

    if ([] === $needsRebuild) {
        foreach (BOOTSTRAP_VENDOR_PRELINK_PACKAGES as $package => $role) {
            if (null !== $one && $one !== $package && $one !== bootstrapVendorPrelinkSlug($package)) {
                continue;
            }
            $objectRel = $manifest['packages'][$package]['object'] ?? '';
            $manifest['packages'][$package]['status'] = 'object_ok';
            $manifest['packages'][$package]['blocker'] = null;
            fwrite(STDOUT, "OK {$package} → {$objectRel} (cold boot: committed prelink)\n");
        }
        bootstrapVendorPrelinkWriteManifest($manifestPath, $manifest);
        fwrite(STDOUT, "bootstrap-vendor-objects: cold boot — all prelink objects from committed artifacts\n");

        return 0;
    }

    if (!bootstrapVendorPrelinkSourcesTreePresent($root)) {
        foreach ($needsRebuild as $package) {
            $objectRel = $manifest['packages'][$package]['object'] ?? '';
            $manifest['packages'][$package]['status'] = 'missing_object';
            $manifest['packages'][$package]['blocker'] = 'cold boot: committed '.$objectRel.' missing (no sources snapshot — #2881)';
        }
        bootstrapVendorPrelinkWriteManifest($manifestPath, $manifest);
        fwrite(STDERR, 'bootstrap-vendor-objects: '.count($needsRebuild).' package(s) missing prelink .o and sources snapshot (vendor/ absent)'."\n");

        return 1;
    }

    $llvm = getenv('PHP_COMPILER_LLVM_PATH') ?: '';
    if ('' === $llvm || !is_file($llvm.'/libLLVM-9.so.1')) {
        fwrite(STDERR, "bootstrap-vendor-objects: LLVM 9 required to rebuild missing prelink .o (set PHP_COMPILER_LLVM_PATH)\n");

        return 2;
    }

    $marker = bootstrapVendorPrelinkMaterializeVendorTree($root);
    if (null === $marker) {
        fwrite(STDERR, "bootstrap-vendor-objects: failed to materialize vendor sources for cold-boot rebuild\n");

        return 1;
    }

    putenv('PHP_COMPILER_SELFHOST_AOT=0');
    putenv('PHP_COMPILER_VENDOR_PRELINK=1');
    putenv('PHP_COMPILER_KEEP_OBJECT_FILE=1');

    $compileInvoker = bootstrapVendorPrelinkResolveCompileInvoker($root);
    if (
        'zend' === $compileInvoker['mode']
        && '1' !== (string) getenv('BOOTSTRAP_M5_VENDOR_ALLOW_ZEND')
    ) {
        fwrite(
            STDERR,
            "bootstrap-vendor-objects: cold boot requires native compile driver (no Zend in loop)\n"
        );
        fwrite(
            STDERR,
            "bootstrap-vendor-objects: no compiled driver under build/ (expected one of selfhost-compile-driver, selfhost-native-compile-driver, bin-compile-aot)\n"
        );
        fwrite(
            STDERR,
            "bootstrap-vendor-objects: one-time bootstrap:\n"
        );
        fwrite(
            STDERR,
            "  ./script/docker-exec.sh -- bash -lc 'make bootstrap-selfhost-driver-smoke'\n"
        );
        fwrite(
            STDERR,
            "bootstrap-vendor-objects: or set BOOTSTRAP_M5_VENDOR_ALLOW_ZEND=1 to permit gen-0 fallback (NOT M5)\n"
        );
        bootstrapVendorPrelinkCleanupMaterializedVendorTree($root, $marker);
        bootstrapVendorPrelinkWriteManifest($manifestPath, $manifest);

        return 1;
    }
    fwrite(
        STDERR,
        'bootstrap-vendor-objects: cold-boot rebuild invoker='.$compileInvoker['mode']
        .' ('.($compileInvoker['argv'][0] ?? 'unknown').") (#2881)\n"
    );
    fwrite(STDERR, "bootstrap-vendor-objects: materialized vendor/ from prelinked/bootstrap-vendor/sources\n");

    $failures = 0;
    foreach (BOOTSTRAP_VENDOR_PRELINK_PACKAGES as $package => $role) {
        if (null !== $one && $one !== $package && $one !== bootstrapVendorPrelinkSlug($package)) {
            continue;
        }
        $objectRel = $manifest['packages'][$package]['object'] ?? '';
        $objectAbs = is_string($objectRel) && '' !== $objectRel ? $root.'/'.$objectRel : '';
        if ('' !== $objectAbs && is_file($objectAbs) && !in_array($package, $needsRebuild, true)) {
            $manifest['packages'][$package]['status'] = 'object_ok';
            $manifest['packages'][$package]['blocker'] = null;
            fwrite(STDOUT, "OK {$package} → {$objectRel} (cold boot: committed prelink)\n");
            continue;
        }
    }

    $failures += bootstrapVendorPrelinkCompilePackages($root, $manifest, $one, $needsRebuild);

    if (
        $failures > 0
        && bootstrapVendorPrelinkFailuresAreNativeParseSpine($manifest, $needsRebuild)
    ) {
        fwrite(
            STDERR,
            "bootstrap-vendor-objects: native driver parse spine null; cold-boot Zend rebuild (#2967)\n"
        );
        putenv('BOOTSTRAP_M5_VENDOR_ALLOW_ZEND=1');
        $zendInvoker = [
            'mode' => 'zend',
            'argv' => [PHP_BINARY, $root.'/bin/compile.php'],
        ];
        $failures = bootstrapVendorPrelinkCompilePackages($root, $manifest, $one, $needsRebuild, $zendInvoker);
    }

    bootstrapVendorPrelinkCleanupMaterializedVendorTree($root, $marker);
    bootstrapVendorPrelinkWriteManifest($manifestPath, $manifest);

    if ($failures > 0) {
        fwrite(STDERR, "bootstrap-vendor-objects: {$failures} package(s) failed cold-boot rebuild (manifest updated)\n");

        return 1;
    }

    fwrite(STDOUT, "bootstrap-vendor-objects: cold boot — prelink objects OK (committed + rebuilt)\n");

    return 0;
}

/**
 * Resolve gen-0 vendor prelink AOT invoker: compiled driver when present, else Zend php bin/compile.php (#2842, #2849).
 *
 * @return array{mode: 'native'|'zend', argv: list<string>}
 */
function bootstrapVendorPrelinkResolveCompileInvoker(string $root): array
{
    if ('1' === (string) getenv('BOOTSTRAP_GEN0_ZEND_ONLY')) {
        return [
            'mode' => 'zend',
            'argv' => [PHP_BINARY, $root.'/bin/compile.php'],
        ];
    }

    foreach ([
        $root.'/build/selfhost-compile-driver',
        $root.'/build/selfhost-native-compile-driver',
        $root.'/build/bin-compile-aot',
        $root.'/build/selfhost-helloworld-compile',
    ] as $candidate) {
        if (is_executable($candidate)) {
            return [
                'mode' => 'native',
                'argv' => [$candidate],
            ];
        }
    }

    return [
        'mode' => 'zend',
        'argv' => [PHP_BINARY, $root.'/bin/compile.php'],
    ];
}

/** Shell command for vendor bundle AOT → .o (env + driver + -o + entry). */
/** @param list<string> $packages */
function bootstrapVendorPrelinkFailuresAreNativeParseSpine(array $manifest, array $packages): bool
{
    if ([] === $packages) {
        return false;
    }
    foreach ($packages as $package) {
        $blocker = (string) ($manifest['packages'][$package]['blocker'] ?? '');
        if (
            !str_contains($blocker, 'parseAndCompile returned null')
            && !str_contains($blocker, 'native emit failed at phase=parseAndCompile')
        ) {
            return false;
        }
    }

    return true;
}

/**
 * @param array{mode: 'native'|'zend', argv: list<string>}|null $invoker
 */
function bootstrapVendorPrelinkBuildCompileCommand(
    string $root,
    string $buildBase,
    string $bundleAbs,
    ?array $invoker = null
): string {
    $inv = $invoker ?? bootstrapVendorPrelinkResolveCompileInvoker($root);
    $argv = array_map('escapeshellarg', $inv['argv']);

    return 'PHP_COMPILER_VENDOR_PRELINK=1 PHP_COMPILER_SELFHOST_AOT=0 PHP_COMPILER_KEEP_OBJECT_FILE=1 '
        .implode(' ', $argv)
        .' -o '.escapeshellarg($buildBase)
        .' '.escapeshellarg($bundleAbs)
        .' 2>&1';
}
