#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Inventory vendor packages on the compiler bootstrap path (M5 fast path).
 *
 * Usage:
 *   php script/bootstrap-vendor-inventory.php
 *   php script/bootstrap-vendor-inventory.php --json
 *   php script/bootstrap-vendor-inventory.php --check
 */

$root = dirname(__DIR__);
require $root.'/vendor/autoload.php';

$check = in_array('--check', $argv, true);
$jsonOut = in_array('--json', $argv, true);
$outFile = $root.'/docs/bootstrap-vendor-inventory.md';

/** @var array<string, string> */
const BOOTSTRAP_VENDOR_PACKAGES = [
    'nikic/php-parser' => 'AST parse (Runtime constructor)',
    'ircmaxell/php-cfg' => 'CFG + traversers',
    'ircmaxell/php-types' => 'TypeReconstructor',
    'ircmaxell/php-llvm' => 'LLVM FFI from PHP JIT',
    'pre/plugin' => 'Parser plugin / autoload',
];

function bootstrapVendorCountFiles(string $vendorRoot, string $package): int
{
    $dir = $vendorRoot.'/'.$package;
    if (!is_dir($dir)) {
        return 0;
    }
    $count = 0;
    $it = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($dir, FilesystemIterator::SKIP_DOTS)
    );
    foreach ($it as $file) {
        if ($file->isFile() && str_ends_with(strtolower($file->getFilename()), '.php')) {
            ++$count;
        }
    }

    return $count;
}

/** @param array{totals: array{php_files: int}, packages: array<string, array{php_files: int, role: string}>} $report */
function bootstrapVendorRenderMarkdown(array $report): string
{
    $lines = [];
    $lines[] = '# Bootstrap vendor inventory (M5 prelink path)';
    $lines[] = '';
    $lines[] = 'Auto-generated by `script/bootstrap-vendor-inventory.php`. Vendor needed for parse → CFG → JIT when Zend is retired ([#1403](https://github.com/PurHur/php-compiler/issues/1403)).';
    $lines[] = '';
    $lines[] = 'Regenerate: `php script/bootstrap-vendor-inventory.php`';
    $lines[] = '';
    $lines[] = '## Summary';
    $lines[] = '';
    $lines[] = '| Metric | Count |';
    $lines[] = '|--------|------:|';
    $lines[] = '| Vendor PHP files (bootstrap packages) | **'.$report['totals']['php_files'].'** |';
    $lines[] = '| Packages | **'.count($report['packages']).'** |';
    $lines[] = '';
    $lines[] = '**M5 strategy:** prelink as native objects or bitcode; self-host links `lib/` + prelinked vendor — no `vendor/autoload.php` at cold boot. Compiler logic stays PHP; see [`docs/bootstrap-m5-fast-path.md`](bootstrap-m5-fast-path.md).';
    $lines[] = '';
    $lines[] = '## Packages';
    $lines[] = '';
    $lines[] = '| Package | PHP files | Role |';
    $lines[] = '|---------|----------:|------|';
    foreach ($report['packages'] as $name => $info) {
        $lines[] = '| `'.$name.'` | '.$info['php_files'].' | '.$info['role'].' |';
    }
    $lines[] = '';
    $lines[] = '## Non-goals (v1)';
    $lines[] = '';
    $lines[] = '- Compiling vendor from source inside the self-host bundle';
    $lines[] = '- Self-hosting LLVM FFI without prelinked php-llvm artifacts';
    $lines[] = '';

    return implode("\n", $lines)."\n";
}

$vendorRoot = $root.'/vendor';
$packages = [];
$totalFiles = 0;
foreach (BOOTSTRAP_VENDOR_PACKAGES as $package => $role) {
    $count = bootstrapVendorCountFiles($vendorRoot, $package);
    $packages[$package] = ['php_files' => $count, 'role' => $role];
    $totalFiles += $count;
}

$report = [
    'totals' => ['php_files' => $totalFiles],
    'packages' => $packages,
];

if ($jsonOut) {
    echo json_encode($report, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)."\n";
    exit(0);
}

$markdown = bootstrapVendorRenderMarkdown($report);
if ($check) {
    if (!is_file($outFile)) {
        fwrite(STDERR, "Missing {$outFile}; run: php script/bootstrap-vendor-inventory.php\n");
        exit(1);
    }
    if ((string) file_get_contents($outFile) !== $markdown) {
        fwrite(STDERR, "Stale {$outFile}; regenerate with: php script/bootstrap-vendor-inventory.php\n");
        exit(1);
    }
    exit(0);
}

file_put_contents($outFile, $markdown);
fwrite(STDOUT, "Wrote {$outFile} ({$totalFiles} vendor PHP files)\n");
