#!/usr/bin/env bash
# Shared docker run wrapper: cgroup memory cap + CI env defaults (issue #497).
set -euo pipefail

_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=ci-defaults.env
source "$_SCRIPT_DIR/ci-defaults.env"

# Usage: ci_docker_run [docker run flags and image...] -- command...
ci_docker_run() {
  docker run --rm \
    -m "${PHP_COMPILER_DOCKER_MEM}" \
    --memory-swap "${PHP_COMPILER_DOCKER_MEM_SWAP}" \
    -e "PHP_COMPILER_CI_RAM_GB=${PHP_COMPILER_CI_RAM_GB}" \
    -e "PHP_COMPILER_MEMORY_LIMIT=${PHP_COMPILER_MEMORY_LIMIT}" \
    -e "PHP_COMPILER_LLVM_MEMORY_LIMIT=${PHP_COMPILER_LLVM_MEMORY_LIMIT}" \
    -e "PHP_COMPILER_SKIP_SERVE_TESTS=${PHP_COMPILER_SKIP_SERVE_TESTS:-}" \
    -e "JIT_PREFLIGHT_GATE=${JIT_PREFLIGHT_GATE:-}" \
    -e "NORTH_STAR2_VERIFY_GATE=${NORTH_STAR2_VERIFY_GATE:-1}" \
    -e "BOOTSTRAP_TEST_SUBSET_GATE=${BOOTSTRAP_TEST_SUBSET_GATE:-0}" \
    -e "BOOTSTRAP_TEST_SUBSET_STRICT=${BOOTSTRAP_TEST_SUBSET_STRICT:-0}" \
    -e "WAVE3_ROADMAP_SYNC_GATE=${WAVE3_ROADMAP_SYNC_GATE:-1}" \
    -e "M2_SPINE_ISSUE_HYGIENE_GATE=${M2_SPINE_ISSUE_HYGIENE_GATE:-1}" \
    -e "EXAMPLES_README_SYNC_GATE=${EXAMPLES_README_SYNC_GATE:-1}" \
    -e "EXAMPLES_LADDER_DISCOVERY_GATE=${EXAMPLES_LADDER_DISCOVERY_GATE:-1}" \
    -e "REBUILD_EXAMPLES_005_SYNC_GATE=${REBUILD_EXAMPLES_005_SYNC_GATE:-1}" \
    -e "REBUILD_EXAMPLES_006_SYNC_GATE=${REBUILD_EXAMPLES_006_SYNC_GATE:-1}" \
    -e "ROOT_README_SYNC_GATE=${ROOT_README_SYNC_GATE:-1}" \
    -e "DEVELOPMENT_STATUS_SYNC_GATE=${DEVELOPMENT_STATUS_SYNC_GATE:-1}" \
    -e "DEVELOPMENT_STATUS_007_SYNC_GATE=${DEVELOPMENT_STATUS_007_SYNC_GATE:-0}" \
    -e "ROOT_README_006_SYNC_GATE=${ROOT_README_006_SYNC_GATE:-1}" \
    -e "ROOT_README_007_SYNC_GATE=${ROOT_README_007_SYNC_GATE:-1}" \
    -e "CAPABILITIES_006_SYNC_GATE=${CAPABILITIES_006_SYNC_GATE:-1}" \
    -e "SELFHOST_SPINE_COUNT_SYNC_GATE=${SELFHOST_SPINE_COUNT_SYNC_GATE:-1}" \
    -e "SELFHOST_SPINE_COVERAGE_SYNC_GATE=${SELFHOST_SPINE_COVERAGE_SYNC_GATE:-1}" \
    -e "SELFHOST_M4_GEN2_SYNC_GATE=${SELFHOST_M4_GEN2_SYNC_GATE:-0}" \
    -e "BOOTSTRAP_M3_COMPILE_SMOKE_PROBE_GATE=${BOOTSTRAP_M3_COMPILE_SMOKE_PROBE_GATE:-1}" \
    -e "BOOTSTRAP_M3_COMPILE_SMOKE_STRICT_GATE=${BOOTSTRAP_M3_COMPILE_SMOKE_STRICT_GATE:-0}" \
    -e "COMPILER_DRIVER_SMOKE_GATE=${COMPILER_DRIVER_SMOKE_GATE:-0}" \
    -e "M3_ALLOWLIST_SYNC_GATE=${M3_ALLOWLIST_SYNC_GATE:-1}" \
    -e "BOOTSTRAP_M5_DOC_SYNC_GATE=${BOOTSTRAP_M5_DOC_SYNC_GATE:-1}" \
    -e "BOOTSTRAP_VENDOR_INVENTORY_SYNC_GATE=${BOOTSTRAP_VENDOR_INVENTORY_SYNC_GATE:-1}" \
    -e "INIT_MINIWEBAPP_PARITY_GATE=${INIT_MINIWEBAPP_PARITY_GATE:-1}" \
    -e "CAPABILITIES_SESSIONSWEB_SYNC_GATE=${CAPABILITIES_SESSIONSWEB_SYNC_GATE:-1}" \
    -e "CAPABILITIES_THROWS_SYNC_GATE=${CAPABILITIES_THROWS_SYNC_GATE:-0}" \
    -e "NESTED_RETURN_COMPLIANCE_GATE=${NESTED_RETURN_COMPLIANCE_GATE:-1}" \
    -e "ATTRIBUTES_COMPLIANCE_GATE=${ATTRIBUTES_COMPLIANCE_GATE:-1}" \
    -e "REHASH_COMPLIANCE_GATE=${REHASH_COMPLIANCE_GATE:-1}" \
    -e "COALESCE_COMPLIANCE_GATE=${COALESCE_COMPLIANCE_GATE:-1}" \
    -e "JIT_VARIABLE_FUNCTION_COMPLIANCE_GATE=${JIT_VARIABLE_FUNCTION_COMPLIANCE_GATE:-1}" \
    "$@"
}
