#!/usr/bin/env bash
# Shared docker run wrapper: cgroup memory cap + CI env defaults (issue #497).
set -euo pipefail

_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=ci-defaults.env
source "$_SCRIPT_DIR/ci-defaults.env"

# Extra docker run flags injected by CI/harness environments (issues #2244, #2249).
# Prefer explicit PHP_COMPILER_DOCKER_RUN_OPTS but fall back to HARNESS_DOCKER_RUN_OPTS.
_ci_docker_extra_opts=()
if [[ -n "${PHP_COMPILER_DOCKER_RUN_OPTS:-${HARNESS_DOCKER_RUN_OPTS:-}}" ]]; then
  # shellcheck disable=SC2206
  _ci_docker_extra_opts=(${PHP_COMPILER_DOCKER_RUN_OPTS:-${HARNESS_DOCKER_RUN_OPTS}})
fi

# Runforge / agent-harness sandboxes export HARNESS_* (issue #2249).
ci_docker_harness_context() {
  [[ -n "${HARNESS_HOST:-}" || -n "${HARNESS_PORT:-}" || -n "${HARNESS_DATA_DIR:-}" ]]
}

if [[ "${PHP_COMPILER_REQUIRE_DOCKER_RUN_OPTS:-0}" = "1" ]] && [[ ${#_ci_docker_extra_opts[@]} -eq 0 ]]; then
  echo "ci-docker-run: missing required \$PHP_COMPILER_DOCKER_RUN_OPTS / \$HARNESS_DOCKER_RUN_OPTS" >&2
  echo "ci-docker-run: set HARNESS_DOCKER_RUN_OPTS (recommended on harness) or override with PHP_COMPILER_DOCKER_RUN_OPTS" >&2
  echo "ci-docker-run: harness entrypoints: make test-harness / ./script/docker-exec.sh / ./script/docker-ci-local.sh" >&2
  exit 2
fi

# Best-effort nudge in non-strict mode (avoid spamming by printing once per process).
if [[ ${#_ci_docker_extra_opts[@]} -eq 0 ]] && [[ -z "${_CI_DOCKER_RUN_OPTS_WARNED:-}" ]]; then
  export _CI_DOCKER_RUN_OPTS_WARNED=1
  if ci_docker_harness_context; then
    echo "ci-docker-run: harness warning: \$HARNESS_DOCKER_RUN_OPTS is unset — set resource limits (e.g. --memory=8g --cpus=2) or use make test-harness" >&2
  else
    echo "ci-docker-run: warning: no \$HARNESS_DOCKER_RUN_OPTS / \$PHP_COMPILER_DOCKER_RUN_OPTS set (possible OOM/flakiness on harness)" >&2
  fi
fi

# Shared docker create/run flags (memory cap + harness opts + CI env).
_ci_docker_common_args=(
  "${_ci_docker_extra_opts[@]}"
  -m "${PHP_COMPILER_DOCKER_MEM}"
  --memory-swap "${PHP_COMPILER_DOCKER_MEM_SWAP}"
  -e "PHP_COMPILER_CI_RAM_GB=${PHP_COMPILER_CI_RAM_GB}"
  -e "PHP_COMPILER_MEMORY_LIMIT=${PHP_COMPILER_MEMORY_LIMIT}"
  -e "PHP_COMPILER_LLVM_MEMORY_LIMIT=${PHP_COMPILER_LLVM_MEMORY_LIMIT}"
  -e "PHP_COMPILER_SKIP_SERVE_TESTS=${PHP_COMPILER_SKIP_SERVE_TESTS:-}"
  -e "JIT_PREFLIGHT_GATE=${JIT_PREFLIGHT_GATE:-}"
  -e "NORTH_STAR2_VERIFY_GATE=${NORTH_STAR2_VERIFY_GATE:-1}"
  -e "NORTH_STAR2_THROWSWEB_GATE=${NORTH_STAR2_THROWSWEB_GATE:-1}"
  -e "NORTH_STAR3_VERIFY_GATE=${NORTH_STAR3_VERIFY_GATE:-0}"
  -e "BOOTSTRAP_TEST_SUBSET_GATE=${BOOTSTRAP_TEST_SUBSET_GATE:-0}"
  -e "BOOTSTRAP_TEST_SUBSET_STRICT=${BOOTSTRAP_TEST_SUBSET_STRICT:-0}"
  -e "WAVE3_ROADMAP_SYNC_GATE=${WAVE3_ROADMAP_SYNC_GATE:-1}"
  -e "M2_SPINE_ISSUE_HYGIENE_GATE=${M2_SPINE_ISSUE_HYGIENE_GATE:-1}"
  -e "EXAMPLES_README_SYNC_GATE=${EXAMPLES_README_SYNC_GATE:-1}"
  -e "EXAMPLES_LADDER_DISCOVERY_GATE=${EXAMPLES_LADDER_DISCOVERY_GATE:-1}"
  -e "REBUILD_EXAMPLES_005_SYNC_GATE=${REBUILD_EXAMPLES_005_SYNC_GATE:-1}"
  -e "REBUILD_EXAMPLES_006_SYNC_GATE=${REBUILD_EXAMPLES_006_SYNC_GATE:-1}"
  -e "REBUILD_EXAMPLES_009_SYNC_GATE=${REBUILD_EXAMPLES_009_SYNC_GATE:-1}"
  -e "REBUILD_EXAMPLES_003_JIT_PROJECT_SYNC_GATE=${REBUILD_EXAMPLES_003_JIT_PROJECT_SYNC_GATE:-0}"
  -e "ROOT_README_SYNC_GATE=${ROOT_README_SYNC_GATE:-1}"
  -e "DEVELOPMENT_STATUS_SYNC_GATE=${DEVELOPMENT_STATUS_SYNC_GATE:-1}"
  -e "DEVELOPMENT_STATUS_007_SYNC_GATE=${DEVELOPMENT_STATUS_007_SYNC_GATE:-1}"
  -e "ROOT_README_006_SYNC_GATE=${ROOT_README_006_SYNC_GATE:-1}"
  -e "ROOT_README_007_SYNC_GATE=${ROOT_README_007_SYNC_GATE:-1}"
  -e "ROOT_README_008_SYNC_GATE=${ROOT_README_008_SYNC_GATE:-0}"
  -e "ROOT_README_009_SYNC_GATE=${ROOT_README_009_SYNC_GATE:-1}"
  -e "DEVELOPMENT_STATUS_009_SYNC_GATE=${DEVELOPMENT_STATUS_009_SYNC_GATE:-1}"
  -e "CAPABILITIES_006_SYNC_GATE=${CAPABILITIES_006_SYNC_GATE:-1}"
  -e "SELFHOST_SPINE_COUNT_SYNC_GATE=${SELFHOST_SPINE_COUNT_SYNC_GATE:-1}"
  -e "SELFHOST_SPINE_COVERAGE_SYNC_GATE=${SELFHOST_SPINE_COVERAGE_SYNC_GATE:-1}"
  -e "SELFHOST_SPINE_DEFERRED_SYNC_GATE=${SELFHOST_SPINE_DEFERRED_SYNC_GATE:-1}"
  -e "SELFHOST_M4_GEN2_SYNC_GATE=${SELFHOST_M4_GEN2_SYNC_GATE:-1}"
  -e "BOOTSTRAP_M3_COMPILE_SMOKE_PROBE_GATE=${BOOTSTRAP_M3_COMPILE_SMOKE_PROBE_GATE:-1}"
  -e "BOOTSTRAP_M3_COMPILE_SMOKE_STRICT_GATE=${BOOTSTRAP_M3_COMPILE_SMOKE_STRICT_GATE:-0}"
  -e "BOOTSTRAP_RUNTIME_COMPILE_SMOKE_PROBE_GATE=${BOOTSTRAP_RUNTIME_COMPILE_SMOKE_PROBE_GATE:-1}"
  -e "BOOTSTRAP_RUNTIME_COMPILE_SMOKE_STRICT_GATE=${BOOTSTRAP_RUNTIME_COMPILE_SMOKE_STRICT_GATE:-0}"
  -e "BOOTSTRAP_M3_STRICT_SYNC_GATE=${BOOTSTRAP_M3_STRICT_SYNC_GATE:-0}"
  -e "BOOTSTRAP_LOOP_PROBE_GATE=${BOOTSTRAP_LOOP_PROBE_GATE:-0}"
  -e "BOOTSTRAP_M4_LOOP_PROBE=${BOOTSTRAP_M4_LOOP_PROBE:-0}"
  -e "COMPILER_DRIVER_SMOKE_GATE=${COMPILER_DRIVER_SMOKE_GATE:-1}"
  -e "BOOTSTRAP_JIT_UNIT_PROBE_GATE=${BOOTSTRAP_JIT_UNIT_PROBE_GATE:-0}"
  -e "BOOTSTRAP_VM_UNIT_PROBE_GATE=${BOOTSTRAP_VM_UNIT_PROBE_GATE:-0}"
  -e "BOOTSTRAP_PHPTYPES_UNIT_PROBE_GATE=${BOOTSTRAP_PHPTYPES_UNIT_PROBE_GATE:-1}"
  -e "BOOTSTRAP_M3_EMIT_TU_EXECUTE_GATE=${BOOTSTRAP_M3_EMIT_TU_EXECUTE_GATE:-0}"
  -e "M3_ALLOWLIST_SYNC_GATE=${M3_ALLOWLIST_SYNC_GATE:-1}"
  -e "BOOTSTRAP_M5_DOC_SYNC_GATE=${BOOTSTRAP_M5_DOC_SYNC_GATE:-1}"
  -e "BOOTSTRAP_INVENTORY_LINT_SYNC_GATE=${BOOTSTRAP_INVENTORY_LINT_SYNC_GATE:-0}"
  -e "BOOTSTRAP_INVENTORY_TRIAGE_SYNC_GATE=${BOOTSTRAP_INVENTORY_TRIAGE_SYNC_GATE:-0}"
  -e "STDLIB_JIT_DEFERRED_SYNC_GATE=${STDLIB_JIT_DEFERRED_SYNC_GATE:-0}"
  -e "DOCTOR_GATES_MATRIX_SYNC_GATE=${DOCTOR_GATES_MATRIX_SYNC_GATE:-1}"
  -e "BOOTSTRAP_VENDOR_INVENTORY_SYNC_GATE=${BOOTSTRAP_VENDOR_INVENTORY_SYNC_GATE:-1}"
  -e "INIT_MINIWEBAPP_PARITY_GATE=${INIT_MINIWEBAPP_PARITY_GATE:-1}"
  -e "MINIWEBAPP_LINT_ZERO_GATE=${MINIWEBAPP_LINT_ZERO_GATE:-1}"
  -e "CAPABILITIES_SESSIONSWEB_SYNC_GATE=${CAPABILITIES_SESSIONSWEB_SYNC_GATE:-1}"
  -e "CAPABILITIES_THROWS_SYNC_GATE=${CAPABILITIES_THROWS_SYNC_GATE:-1}"
  -e "CAPABILITIES_OOP_SYNC_GATE=${CAPABILITIES_OOP_SYNC_GATE:-0}"
  -e "NESTED_RETURN_COMPLIANCE_GATE=${NESTED_RETURN_COMPLIANCE_GATE:-1}"
  -e "ATTRIBUTES_COMPLIANCE_GATE=${ATTRIBUTES_COMPLIANCE_GATE:-1}"
  -e "REHASH_COMPLIANCE_GATE=${REHASH_COMPLIANCE_GATE:-1}"
  -e "COALESCE_COMPLIANCE_GATE=${COALESCE_COMPLIANCE_GATE:-1}"
  -e "JIT_VARIABLE_FUNCTION_COMPLIANCE_GATE=${JIT_VARIABLE_FUNCTION_COMPLIANCE_GATE:-1}"
  -e "JIT_SERVER_SUPERGLOBAL_GATE=${JIT_SERVER_SUPERGLOBAL_GATE:-1}"
  -e "EXAMPLES_SELFHOSTPROBE_SMOKE_GATE=${EXAMPLES_SELFHOSTPROBE_SMOKE_GATE:-1}"
)

# Usage: ci_docker_create [docker create flags and image...] -- command...
ci_docker_create() {
  docker create "${_ci_docker_common_args[@]}" "$@"
}

# Usage: ci_docker_run [docker run flags and image...] -- command...
ci_docker_run() {
  docker run --rm "${_ci_docker_common_args[@]}" "$@"
}
