<?php

declare(strict_types=1);

/**
 * Regenerate lib/AOT/runtime/builtin_function_names.inc from ext Module registrations.
 */
require __DIR__.'/../vendor/autoload.php';

$names = [];
foreach ([new PHPCompiler\ext\standard\Module(), new PHPCompiler\ext\types\Module()] as $module) {
    foreach ($module->getFunctions() as $func) {
        $names[] = strtolower($func->getName());
    }
}
$names = array_values(array_unique($names));
sort($names);

$target = __DIR__.'/../lib/AOT/runtime/builtin_function_names.inc';
$body = "/* Generated by script/gen-builtin-function-names-inc.php — do not edit. */\n";
$body .= "static const char *phpc_builtin_functions[] = {\n";
foreach ($names as $name) {
    $body .= '    "'.addslashes($name)."\",\n";
}
$body .= "};\n";
$body .= 'static const size_t phpc_builtin_functions_count = '.count($names).";\n";

file_put_contents($target, $body);
fwrite(STDERR, 'Wrote '.count($names)." names to {$target}\n");
