<?php

declare(strict_types=1);

/**
 * Generate docs/pages/bench.html from benchmarks/history/*.json + RESULTS.json (#36385).
 *
 * Embeds history JSON in the page so it works from a static file:// or docs site
 * without a directory listing API.
 *
 * Usage:
 *   php script/generate-bench-chart.php
 *   ./script/docker-exec.sh -- bash -lc 'php script/generate-bench-chart.php'
 */

$root = dirname(__DIR__);
$historyDir = $root.'/benchmarks/history';
$resultsPath = $root.'/benchmarks/v2/RESULTS.json';
$webPath = $root.'/benchmarks/v2/WEB_REQUEST.json';
$outPath = $root.'/docs/pages/bench.html';

$points = [];
if (is_dir($historyDir)) {
    $files = glob($historyDir.'/*.json') ?: [];
    sort($files, \SORT_STRING);
    foreach ($files as $file) {
        $doc = json_decode((string) file_get_contents($file), true);
        if (!is_array($doc) || !isset($doc['cases']) || !is_array($doc['cases'])) {
            continue;
        }
        $sha = basename($file, '.json');
        $points[] = [
            'sha' => $sha,
            'generated_at' => $doc['generated_at'] ?? null,
            'cases' => summarizeCases($doc['cases']),
            'web_request' => summarizeWeb($doc['web_request'] ?? null),
        ];
    }
}

$latest = null;
if (is_file($resultsPath)) {
    $doc = json_decode((string) file_get_contents($resultsPath), true);
    if (is_array($doc) && isset($doc['cases']) && is_array($doc['cases'])) {
        $latest = [
            'sha' => 'RESULTS',
            'generated_at' => $doc['generated_at'] ?? null,
            'cases' => summarizeCases($doc['cases']),
            'web_request' => summarizeWeb($doc['web_request'] ?? null),
        ];
    }
}

$webStandalone = null;
if (is_file($webPath)) {
    $webDoc = json_decode((string) file_get_contents($webPath), true);
    if (is_array($webDoc)) {
        $webStandalone = summarizeWeb($webDoc);
    }
}

$payload = [
    'generated_at' => gmdate('Y-m-d\TH:i:s\Z'),
    'history' => $points,
    'latest' => $latest,
    'web_request' => $webStandalone ?? ($latest['web_request'] ?? null),
];

$json = json_encode($payload, \JSON_UNESCAPED_SLASHES);
if (false === $json) {
    fwrite(STDERR, "generate-bench-chart: json_encode failed\n");
    exit(1);
}

$html = <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>php-compiler benchmark history</title>
  <style>
    body { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; margin: 2rem; max-width: 72rem; color: #111; }
    h1 { font-size: 1.25rem; }
    h2 { font-size: 1.05rem; margin-top: 2rem; }
    table { border-collapse: collapse; width: 100%; margin-top: 0.75rem; font-size: 0.85rem; }
    th, td { border-bottom: 1px solid #ccc; padding: 0.35rem 0.5rem; text-align: left; vertical-align: middle; }
    th { font-weight: 600; }
    .muted { color: #666; font-size: 0.9rem; }
    .spark { display: inline-block; vertical-align: middle; }
    .na { color: #999; }
    code { font-size: 0.9em; }
  </style>
</head>
<body>
  <h1>Benchmark history (#36385)</h1>
  <p class="muted">
    Generated by <code>php script/generate-bench-chart.php</code> from
    <code>benchmarks/history/*.json</code> and <code>benchmarks/v2/RESULTS.json</code>.
    Ratios are AOT / Zend wall time (lower is better). <code>n/a</code> means build failed,
    timed out, or output mismatched Zend.
  </p>
  <p>
    Gate: <code>./script/bench-gate.sh --v2</code> ·
    Suite: <code>benchmarks/v2/README.md</code> ·
    Web column: <code>php script/bench-web-request.php</code>
  </p>
  <div id="meta" class="muted"></div>
  <h2>Latest AOT/Zend ratios</h2>
  <div id="latest"></div>
  <h2>Ratio sparklines (history)</h2>
  <div id="sparks"></div>
  <h2>Web-request (MiniWebApp)</h2>
  <div id="web"></div>
  <script type="application/json" id="bench-data">{$json}</script>
  <script>
(function () {
  var data = JSON.parse(document.getElementById('bench-data').textContent);
  document.getElementById('meta').textContent =
    'Page generated at ' + (data.generated_at || '?') +
    ' · history points: ' + (data.history ? data.history.length : 0);

  function esc(s) {
    return String(s).replace(/[&<>"']/g, function (c) {
      return ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c];
    });
  }

  function spark(values, width, height) {
    width = width || 120; height = height || 28;
    var nums = values.filter(function (v) { return typeof v === 'number' && isFinite(v); });
    if (!nums.length) {
      return '<span class="na">n/a</span>';
    }
    var min = Math.min.apply(null, nums);
    var max = Math.max.apply(null, nums);
    var span = (max - min) || 1;
    var step = width / Math.max(values.length - 1, 1);
    var pts = [];
    for (var i = 0; i < values.length; i++) {
      var v = values[i];
      if (typeof v !== 'number' || !isFinite(v)) continue;
      var x = i * step;
      var y = height - ((v - min) / span) * (height - 2) - 1;
      pts.push(x.toFixed(1) + ',' + y.toFixed(1));
    }
    if (!pts.length) return '<span class="na">n/a</span>';
    return '<svg class="spark" width="' + width + '" height="' + height +
      '" viewBox="0 0 ' + width + ' ' + height + '" aria-hidden="true">' +
      '<polyline fill="none" stroke="#0b57d0" stroke-width="1.5" points="' +
      pts.join(' ') + '"/></svg>';
  }

  function renderLatest(latest) {
    var el = document.getElementById('latest');
    if (!latest || !latest.cases) {
      el.innerHTML = '<p class="na">No RESULTS.json yet — run <code>php script/bench.php --v2</code>.</p>';
      return;
    }
    var names = Object.keys(latest.cases).sort();
    var rows = names.map(function (name) {
      var c = latest.cases[name];
      var ratio = c.ratio_aot_over_zend;
      var ratioCell = (typeof ratio === 'number') ? ratio.toFixed(3) : '<span class="na">n/a</span>';
      var aot = (typeof c.aot === 'number') ? c.aot.toFixed(4) : 'n/a';
      var zend = (typeof c.zend === 'number') ? c.zend.toFixed(4) : 'n/a';
      return '<tr><td>' + esc(name) + '</td><td>' + zend + '</td><td>' + aot +
        '</td><td>' + ratioCell + '</td></tr>';
    }).join('');
    el.innerHTML = '<p class="muted">sha/source: ' + esc(latest.sha) +
      (latest.generated_at ? (' · ' + esc(latest.generated_at)) : '') + '</p>' +
      '<table><thead><tr><th>case</th><th>Zend (s)</th><th>AOT (s)</th><th>ratio</th></tr></thead><tbody>' +
      rows + '</tbody></table>';
  }

  function renderSparks(history) {
    var el = document.getElementById('sparks');
    if (!history || !history.length) {
      el.innerHTML = '<p class="na">No history JSON under <code>benchmarks/history/</code> yet. ' +
        'Set <code>PHP_COMPILER_BENCH_HISTORY=1</code> when running <code>bench.php --v2</code>.</p>';
      return;
    }
    var caseNames = {};
    history.forEach(function (p) {
      Object.keys(p.cases || {}).forEach(function (n) { caseNames[n] = true; });
    });
    var names = Object.keys(caseNames).sort();
    var rows = names.map(function (name) {
      var series = history.map(function (p) {
        var c = (p.cases || {})[name];
        return c && typeof c.ratio_aot_over_zend === 'number' ? c.ratio_aot_over_zend : null;
      });
      var last = series[series.length - 1];
      var lastCell = (typeof last === 'number') ? last.toFixed(3) : '<span class="na">n/a</span>';
      return '<tr><td>' + esc(name) + '</td><td>' + spark(series) + '</td><td>' + lastCell + '</td></tr>';
    }).join('');
    el.innerHTML = '<table><thead><tr><th>case</th><th>sparkline</th><th>last ratio</th></tr></thead><tbody>' +
      rows + '</tbody></table>';
  }

  function renderWeb(web) {
    var el = document.getElementById('web');
    if (!web) {
      el.innerHTML = '<p class="na">No web-request column yet — run <code>php script/bench-web-request.php --merge-results</code>.</p>';
      return;
    }
    var keys = ['zend_builtin', 'phpc_serve', 'phpc_serve_aot', 'php_fpm'];
    var rows = keys.map(function (k) {
      var rps = web.req_per_s && web.req_per_s[k];
      var p99 = web.p99_ms && web.p99_ms[k];
      var rpsCell = (typeof rps === 'number') ? rps.toFixed(1) : '<span class="na">n/a</span>';
      var p99Cell = (typeof p99 === 'number') ? p99.toFixed(1) : '<span class="na">n/a</span>';
      return '<tr><td>' + esc(k) + '</td><td>' + rpsCell + '</td><td>' + p99Cell + '</td></tr>';
    }).join('');
    var notes = (web.notes || []).map(function (n) { return '<li>' + esc(n) + '</li>'; }).join('');
    el.innerHTML = '<p class="muted">requests=' + esc(web.requests || '?') +
      (web.generated_at ? (' · ' + esc(web.generated_at)) : '') + '</p>' +
      '<table><thead><tr><th>runtime</th><th>req/s</th><th>p99 ms</th></tr></thead><tbody>' +
      rows + '</tbody></table>' +
      (notes ? ('<ul class="muted">' + notes + '</ul>') : '');
  }

  renderLatest(data.latest);
  renderSparks(data.history);
  renderWeb(data.web_request);
})();
  </script>
</body>
</html>
HTML;

if (false === file_put_contents($outPath, $html)) {
    fwrite(STDERR, "generate-bench-chart: failed to write {$outPath}\n");
    exit(1);
}

echo "Wrote {$outPath} (history points: ".count($points).")\n";

/**
 * @param array<string, mixed> $cases
 * @return array<string, array{zend: ?float, aot: ?float, ratio_aot_over_zend: ?float}>
 */
function summarizeCases(array $cases): array
{
    $out = [];
    foreach ($cases as $name => $row) {
        if (!is_array($row)) {
            continue;
        }
        $zend = null;
        foreach ($row as $k => $v) {
            if (is_string($k) && preg_match('/^\\d+\\.\\d+/', $k) && (is_float($v) || is_int($v))) {
                $zend = (float) $v;
                break;
            }
        }
        if (null === $zend && isset($row['zend']) && (is_float($row['zend']) || is_int($row['zend']))) {
            $zend = (float) $row['zend'];
        }
        $aot = isset($row['aot']) && (is_float($row['aot']) || is_int($row['aot'])) ? (float) $row['aot'] : null;
        $ratio = (null !== $zend && null !== $aot && $zend > 0.0) ? ($aot / $zend) : null;
        $out[(string) $name] = [
            'zend' => $zend,
            'aot' => $aot,
            'ratio_aot_over_zend' => $ratio,
        ];
    }

    return $out;
}

/**
 * @param mixed $web
 * @return ?array<string, mixed>
 */
function summarizeWeb(mixed $web): ?array
{
    if (!is_array($web)) {
        return null;
    }

    return [
        'generated_at' => $web['generated_at'] ?? null,
        'requests' => $web['requests'] ?? null,
        'req_per_s' => $web['req_per_s'] ?? null,
        'p99_ms' => $web['p99_ms'] ?? null,
        'notes' => $web['notes'] ?? [],
    ];
}
