#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Generate docs/configuration.md from PHPCompiler\Config registry (#36201).
 *
 * Usage:
 *   php script/generate-configuration-docs.php           # write docs/configuration.md
 *   php script/generate-configuration-docs.php --check   # exit 1 on drift
 */

$repoRoot = dirname(__DIR__);
require_once $repoRoot.'/vendor/autoload.php';

use PHPCompiler\Config;

$check = in_array('--check', $argv, true);
$path = $repoRoot.'/docs/configuration.md';

$lines = [];
$lines[] = '<!-- Generated by script/generate-configuration-docs.php — do not edit by hand (#36201) -->';
$lines[] = '';
$lines[] = '# Configuration environment variables';
$lines[] = '';
$lines[] = 'Single registry: `lib/Config.php`. Inspect effective values with:';
$lines[] = '';
$lines[] = '```bash';
$lines[] = './phpc doctor --env';
$lines[] = '```';
$lines[] = '';
$lines[] = 'Image `ENV` pins in `Docker/dev/ubuntu-22.04/Dockerfile` shadow `script/ci-defaults.env`';
$lines[] = 'defaults — `doctor --env` exits non-zero when they drift.';
$lines[] = '';
$lines[] = '| Name | Type | Scope | Default | Description | Since |';
$lines[] = '|------|------|-------|---------|-------------|-------|';

$rows = Config::registry();
ksort($rows);
foreach ($rows as $name => $spec) {
    $default = null === $spec['default'] ? '—' : '`'.$spec['default'].'`';
    $since = null === $spec['since'] ? '—' : $spec['since'];
    $desc = str_replace('|', '\\|', $spec['description']);
    $lines[] = sprintf(
        '| `%s` | %s | %s | %s | %s | %s |',
        $name,
        $spec['type'],
        $spec['scope'],
        $default,
        $desc,
        $since
    );
}
$lines[] = '';
$lines[] = 'Dynamic: `PHP_COMPILER_ENABLE_<ext>` toggles individual extensions (`lib/ReleaseUnsupportedExtensions.php`).';
$lines[] = '';

$new = implode("\n", $lines);
if ($check) {
    if (!is_file($path)) {
        fwrite(STDERR, "generate-configuration-docs: missing {$path} — run without --check\n");
        exit(1);
    }
    $old = (string) file_get_contents($path);
    if ($old !== $new) {
        fwrite(STDERR, "generate-configuration-docs: drift in docs/configuration.md — regenerate\n");
        exit(1);
    }
    fwrite(STDOUT, "generate-configuration-docs: OK\n");
    exit(0);
}

if (false === file_put_contents($path, $new)) {
    fwrite(STDERR, "generate-configuration-docs: failed to write {$path}\n");
    exit(1);
}
fwrite(STDOUT, "generate-configuration-docs: wrote {$path}\n");
