#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Generate ext/tokenizer/TokenConstantsData.php from host ext/tokenizer (php-src parity).
 *
 * Mirrors php-src ext/tokenizer/tokenizer_data.c / tokenizer_data_gen.php (#7254, #4561).
 *
 * Usage:
 *   php script/generate-token-constants.php
 *   php script/generate-token-constants.php --check
 */

$root = dirname(__DIR__);
$outFile = $root . '/ext/tokenizer/TokenConstantsData.php';
$check = \in_array('--check', $argv, true);

$groups = \get_defined_constants(true);
$tokenizer = $groups['tokenizer'] ?? null;
if (!\is_array($tokenizer) || [] === $tokenizer) {
    \fwrite(STDERR, "generate-token-constants: ext/tokenizer required to regenerate {$outFile}\n");
    exit(1);
}

/** php-src get_token_type_name() canonical names when multiple T_* share one id. */
$canonicalIdToName = [
    397 => 'T_DOUBLE_COLON',
];

$nameToId = [];
foreach ($tokenizer as $name => $value) {
    if (!\is_string($name) || !\is_int($value)) {
        continue;
    }
    if (!\str_starts_with($name, 'T_') && 'TOKEN_PARSE' !== $name) {
        continue;
    }
    $nameToId[$name] = $value;
}
\ksort($nameToId);

$idToName = [];
foreach ($nameToId as $name => $id) {
    // TOKEN_PARSE (id 1) is not a named lexer token in tokenizer_data.c (#14925).
    if ('TOKEN_PARSE' === $name) {
        continue;
    }
    if (isset($canonicalIdToName[$id])) {
        $idToName[$id] = $canonicalIdToName[$id];
    } elseif (!isset($idToName[$id])) {
        $idToName[$id] = $name;
    }
}
\ksort($idToName);

$lines = [];
$lines[] = '<?php';
$lines[] = '';
$lines[] = 'declare(strict_types=1);';
$lines[] = '';
$lines[] = 'namespace PHPCompiler\\ext\\tokenizer;';
$lines[] = '';
$lines[] = '/**';
$lines[] = ' * Generated by script/generate-token-constants.php — do not edit manually.';
$lines[] = ' *';
$lines[] = ' * php-src: ext/tokenizer/tokenizer_data.c (#7254, #4561).';
$lines[] = ' */';
$lines[] = 'final class TokenConstantsData';
$lines[] = '{';
$lines[] = '    /** @return array<string, int> */';
$lines[] = '    public static function nameToId(): array';
$lines[] = '    {';
$lines[] = '        return [';
foreach ($nameToId as $name => $id) {
    $lines[] = '            ' . \var_export($name, true) . ' => ' . $id . ',';
}
$lines[] = '        ];';
$lines[] = '    }';
$lines[] = '';
$lines[] = '    /** @return array<int, string> */';
$lines[] = '    public static function idToName(): array';
$lines[] = '    {';
$lines[] = '        return [';
foreach ($idToName as $id => $name) {
    $lines[] = '            ' . $id . ' => ' . \var_export($name, true) . ',';
}
$lines[] = '        ];';
$lines[] = '    }';
$lines[] = '}';
$lines[] = '';

$content = \implode("\n", $lines) . "\n";

if ($check) {
    if (!\is_file($outFile)) {
        \fwrite(STDERR, "generate-token-constants: missing {$outFile}\n");
        exit(1);
    }
    if ($content !== (string) \file_get_contents($outFile)) {
        \fwrite(STDERR, "generate-token-constants: {$outFile} is stale; run php script/generate-token-constants.php\n");
        exit(1);
    }
    exit(0);
}

\file_put_contents($outFile, $content);
echo "Wrote {$outFile}\n";
