#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Generate ext/tokenizer/TokenConstantsData.php base tables from host ext/tokenizer.
 *
 * Mirrors php-src ext/tokenizer/tokenizer_data.c / tokenizer_data_gen.php (#7254, #4561).
 * PHP 8.4+ forward-profile id derivation (T_*_SET / T_PROPERTY_C) is kept in the wrapper (#28130).
 *
 * Usage:
 *   php script/generate-token-constants.php
 *   php script/generate-token-constants.php --check
 */

$root = dirname(__DIR__);
$outFile = $root . '/ext/tokenizer/TokenConstantsData.php';
$check = \in_array('--check', $argv, true);

$groups = \get_defined_constants(true);
$tokenizer = $groups['tokenizer'] ?? null;
if (!\is_array($tokenizer) || [] === $tokenizer) {
    \fwrite(STDERR, "generate-token-constants: ext/tokenizer required to regenerate {$outFile}\n");
    exit(1);
}

/** php-src get_token_type_name() canonical names when multiple T_* share one id. */
$canonicalIdToName = [
    397 => 'T_DOUBLE_COLON',
];

$nameToId = [];
foreach ($tokenizer as $name => $value) {
    if (!\is_string($name) || !\is_int($value)) {
        continue;
    }
    if (!\str_starts_with($name, 'T_') && 'TOKEN_PARSE' !== $name) {
        continue;
    }
    $nameToId[$name] = $value;
}
\ksort($nameToId);

$idToName = [];
foreach ($nameToId as $name => $id) {
    // TOKEN_PARSE (id 1) is not a named lexer token in tokenizer_data.c (#14925).
    if ('TOKEN_PARSE' === $name) {
        continue;
    }
    if (isset($canonicalIdToName[$id])) {
        $idToName[$id] = $canonicalIdToName[$id];
    } elseif (!isset($idToName[$id])) {
        $idToName[$id] = $name;
    }
}
\ksort($idToName);

$lines = [];
$lines[] = '<?php';
$lines[] = '';
$lines[] = 'declare(strict_types=1);';
$lines[] = '';
$lines[] = 'namespace PHPCompiler\\ext\\tokenizer;';
$lines[] = '';
$lines[] = '/**';
$lines[] = ' * Tokenizer T_* id tables (php-src ext/tokenizer/tokenizer_data.c; #7254, #4561).';
$lines[] = ' *';
$lines[] = ' * Base (reference/8.2) tables are regenerated by script/generate-token-constants.php.';
$lines[] = ' * PHP 8.4+ forward-profile ids (T_*_SET / T_PROPERTY_C + shifts) are derived here (#28130).';
$lines[] = ' */';
$lines[] = 'final class TokenConstantsData';
$lines[] = '{';
$lines[] = '    /** @return array<string, int> */';
$lines[] = '    public static function nameToId(): array';
$lines[] = '    {';
$lines[] = '        $base = self::nameToIdBase();';
$lines[] = '        if (!self::usePhp84TokenIds()) {';
$lines[] = '            return $base;';
$lines[] = '        }';
$lines[] = '';
$lines[] = '        return self::applyPhp84NameToId($base);';
$lines[] = '    }';
$lines[] = '';
$lines[] = '    /** @return array<int, string> */';
$lines[] = '    public static function idToName(): array';
$lines[] = '    {';
$lines[] = '        if (!self::usePhp84TokenIds()) {';
$lines[] = '            return self::idToNameBase();';
$lines[] = '        }';
$lines[] = '';
$lines[] = '        $nameToId = self::applyPhp84NameToId(self::nameToIdBase());';
$lines[] = '        $idToName = [];';
$lines[] = '        foreach ($nameToId as $name => $id) {';
$lines[] = '            if (\'TOKEN_PARSE\' === $name || \'T_PAAMAYIM_NEKUDOTAYIM\' === $name) {';
$lines[] = '                continue;';
$lines[] = '            }';
$lines[] = '            if (!isset($idToName[$id])) {';
$lines[] = '                $idToName[$id] = $name;';
$lines[] = '            }';
$lines[] = '        }';
$lines[] = '        \\ksort($idToName);';
$lines[] = '';
$lines[] = '        return $idToName;';
$lines[] = '    }';
$lines[] = '';
$lines[] = '    /** PHP 8.4 tokenizer surface: T_*_SET + T_PROPERTY_C and shifted ids (#28130). */';
$lines[] = '    private static function usePhp84TokenIds(): bool';
$lines[] = '    {';
$lines[] = '        return \\version_compare(\\PHPCompiler\\CompilerVersion::languageProfileVersion(), \'8.4.0\', \'>=\');';
$lines[] = '    }';
$lines[] = '';
$lines[] = '    /**';
$lines[] = '     * @param array<string, int> $base';
$lines[] = '     *';
$lines[] = '     * @return array<string, int>';
$lines[] = '     */';
$lines[] = '    private static function applyPhp84NameToId(array $base): array';
$lines[] = '    {';
$lines[] = '        $nameToId = $base;';
$lines[] = '        foreach ($nameToId as $name => $id) {';
$lines[] = '            if ($id >= 327) {';
$lines[] = '                $nameToId[$name] = $id + 3;';
$lines[] = '            }';
$lines[] = '        }';
$lines[] = '        $nameToId[\'T_PRIVATE_SET\'] = 327;';
$lines[] = '        $nameToId[\'T_PROTECTED_SET\'] = 328;';
$lines[] = '        $nameToId[\'T_PUBLIC_SET\'] = 329;';
$lines[] = '';
$lines[] = '        foreach ($nameToId as $name => $id) {';
$lines[] = '            if ($id >= 353 && !\\in_array($name, [\'T_PRIVATE_SET\', \'T_PROTECTED_SET\', \'T_PUBLIC_SET\'], true)) {';
$lines[] = '                $nameToId[$name] = $id + 1;';
$lines[] = '            }';
$lines[] = '        }';
$lines[] = '        $nameToId[\'T_PROPERTY_C\'] = 353;';
$lines[] = '        \\ksort($nameToId);';
$lines[] = '';
$lines[] = '        return $nameToId;';
$lines[] = '    }';
$lines[] = '';
$lines[] = '    /** @return array<string, int> */';
$lines[] = '    public static function nameToIdBase(): array';
$lines[] = '    {';
$lines[] = '        return [';
foreach ($nameToId as $name => $id) {
    $lines[] = '            ' . \var_export($name, true) . ' => ' . $id . ',';
}
$lines[] = '        ];';
$lines[] = '    }';
$lines[] = '';
$lines[] = '    /** @return array<int, string> */';
$lines[] = '    public static function idToNameBase(): array';
$lines[] = '    {';
$lines[] = '        return [';
foreach ($idToName as $id => $name) {
    $lines[] = '            ' . $id . ' => ' . \var_export($name, true) . ',';
}
$lines[] = '        ];';
$lines[] = '    }';
$lines[] = '}';
$lines[] = '';

$content = \implode("\n", $lines) . "\n";

if ($check) {
    if (!\is_file($outFile)) {
        \fwrite(STDERR, "generate-token-constants: missing {$outFile}\n");
        exit(1);
    }
    if ($content !== (string) \file_get_contents($outFile)) {
        \fwrite(STDERR, "generate-token-constants: {$outFile} is stale; run php script/generate-token-constants.php\n");
        exit(1);
    }
    exit(0);
}

\file_put_contents($outFile, $content);
echo "Wrote {$outFile}\n";
