#!/usr/bin/env bash
#
# Can a single spine chunk compile as its own translation unit AND bind its cross-chunk calls?
# (RELEASE-PLAN Phase 3 item 9)
#
# WHY THIS EXISTS
#
# The gen-1 bootstrap link compiles the whole spine — 6,519 files — as ONE translation unit, and
# that build has now failed four times purely on memory: OOM at 6 GiB, 24 GiB and 48 GiB, and a
# fourth run that sat pinned at a 12 GiB cap for 4h55m in direct reclaim (memory.events max=1426,
# oom_kill=0 — it survived by swapping, not by fitting). Capacity is not the constraint; unbounded
# growth in a single TU is. The fix is to split the spine into separately-compiled chunks, which
# requires cross-chunk binding to work.
#
# TWO TRAPS THIS ENCODES, both of which produced a wrong answer before it existed:
#
#   1. A chunk of `require_once` lines over ext/<name>/ is NOT a valid PHP program. Every extension
#      references classes declared elsewhere (ModuleAbstract, VmClassMethod, Func\Internal), so Zend
#      fatals on the bare fixture with rc=255. Measuring "the compiler failed to build this chunk"
#      against a fixture Zend cannot load conflates a compiler gap with an invalid program. The
#      autoloader is prepended so the fixture is a program first; the Zend baseline is then checked
#      rather than assumed.
#   2. rc=0 plus a non-empty binary is NOT a pass. ext/ds compiles to an 18.5 MB binary that exits 0
#      — while reporting 61 method calls, including hexdec/substr/is_string/str_starts_with, lowered
#      to a SILENT NULL because their class is not in the module (#579, #24227). A binary with core
#      stdlib hollowed out cannot host a compiler. Silent wrong output is the characteristic failure
#      of this project (AGENTS.md §3), so an unbound stub is a failure here, not a warning.
#
# #24429 named the first blocker (Call\ExternalMethod returning null instead of calling) and #24496
# landed PHP_COMPILER_SPINE_CHUNK=1 to fall through to it. That moved the wall; it did not remove it.
#
# USAGE
#   script/spine-chunk-probe.sh                       # default probe set
#   script/spine-chunk-probe.sh --ext=sockets --ext=spl
#   script/spine-chunk-probe.sh --timeout=1800
#
# EXIT: 0 only if every probed chunk compiled, bound every call, and matched Zend. 1 otherwise.
# Today every chunk fails — that is the status quo being tracked. A zero exit here is real news.
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT" || exit 1

: "${CHUNK_TIMEOUT:=1800}"
: "${PHP_BIN:=php}"
EXTS=()

for arg in "$@"; do
    case "$arg" in
        --ext=*)     EXTS+=("${arg#*=}") ;;
        --timeout=*) CHUNK_TIMEOUT="${arg#*=}" ;;
        *) echo "unknown argument: $arg" >&2; exit 2 ;;
    esac
done

# Default set: one that currently compiles (ds), one mid, one large. vm is the one that actually
# matters for the spine and takes ~200 s to reach its failure.
if [ "${#EXTS[@]}" -eq 0 ]; then
    EXTS=(ds sockets vm)
fi

OUT_DIR="build/micro/chunk"
mkdir -p "$OUT_DIR"

failures=0
results=()

for ext in "${EXTS[@]}"; do
    src_dir="ext/${ext}"
    if [ ! -d "$src_dir" ]; then
        results+=("$(printf '%-12s %s' "$ext" 'NO SUCH EXTENSION')")
        failures=$((failures + 1))
        continue
    fi

    # Paths are __DIR__-relative so the fixture works outside the container too (the original
    # hand-made chunks hardcoded /app and were silently container-only).
    tu="${OUT_DIR}/${ext}.php"
    {
        echo '<?php'
        echo
        echo "// Generated by script/spine-chunk-probe.sh — spine chunk TU probe for ext/${ext}."
        echo '// Do not edit; regenerate instead.'
        echo '//'
        echo '// The autoloader comes first deliberately: without it Zend cannot load this file at'
        echo '// all (rc=255, "Class PHPCompiler\\ModuleAbstract not found"), and a fixture Zend'
        echo '// rejects cannot be used to judge the compiler.'
        echo
        printf "require_once __DIR__ . '/../../../vendor/autoload.php';\n"
        find "$src_dir" -name '*.php' -type f | LC_ALL=C sort | while read -r f; do
            printf "require_once __DIR__ . '/../../../%s';\n" "$f"
        done
    } > "$tu"

    n_files=$(grep -c "^require_once __DIR__ . '/../../../ext/" "$tu")
    if [ "$n_files" -eq 0 ]; then
        results+=("$(printf '%-12s %s' "$ext" 'EMPTY — no .php files in the extension')")
        failures=$((failures + 1))
        continue
    fi

    # --- Zend baseline: is the fixture even a program? -------------------------------------
    zend_out="${OUT_DIR}/${ext}.zend.out"
    timeout "$CHUNK_TIMEOUT" "$PHP_BIN" "$tu" > "$zend_out" 2> "${OUT_DIR}/${ext}.zend.err"
    zend_rc=$?
    if [ "$zend_rc" -ne 0 ]; then
        results+=("$(printf '%-12s INVALID FIXTURE — Zend rc=%s: %s' \
            "$ext" "$zend_rc" "$(head -1 "${OUT_DIR}/${ext}.zend.err" | cut -c1-70)")")
        failures=$((failures + 1))
        continue
    fi

    # --- compile -----------------------------------------------------------------------------
    bin="${OUT_DIR}/${ext}.bin"
    log="${OUT_DIR}/${ext}.log"
    rm -f "$bin"

    t0=$(date +%s)
    # SPINE_CHUNK=1 is what #24496 added: fall through unresolved instance methods to ExternalMethod
    # instead of aborting. Without it the probe measures the OLD wall and reads as "still broken"
    # for the wrong reason — which is exactly how this probe was first misread.
    timeout "$CHUNK_TIMEOUT" env \
        PHP_COMPILER_SPINE_CHUNK=1 \
        PHP_COMPILER_REPORT_EXTERNAL_STUBS=1 \
        "$PHP_BIN" bin/compile.php -o "$bin" "$tu" > "$log" 2>&1
    rc=$?
    t1=$(date +%s)
    wall=$((t1 - t0))

    size=0
    [ -f "$bin" ] && size=$(stat -c%s "$bin" 2>/dev/null || echo 0)

    if [ "$rc" -ne 0 ] || [ "${size:-0}" -eq 0 ]; then
        results+=("$(printf '%-12s FAILED TO COMPILE rc=%s %ss: %s' \
            "$ext" "$rc" "$wall" "$(tail -1 "$log" 2>/dev/null | cut -c1-60)")")
        failures=$((failures + 1))
        continue
    fi

    # --- unbound cross-chunk calls -------------------------------------------------------------
    # Only meaningful now that the compile above succeeded: a stub count of 0 read from an aborted
    # build is a false clean, and has been reported as one before.
    stub_line=$(grep -m1 'external method stubs' "$log" 2>/dev/null)
    stubs=0
    if [ -n "$stub_line" ]; then
        stubs=$(printf '%s' "$stub_line" | sed -E 's/.*— ([0-9]+) method call\(s\).*/\1/')
        [ -n "$stubs" ] || stubs=0
    fi

    # --- does the artifact behave like Zend? ---------------------------------------------------
    bin_out="${OUT_DIR}/${ext}.bin.out"
    timeout "$CHUNK_TIMEOUT" "./$bin" > "$bin_out" 2> "${OUT_DIR}/${ext}.bin.err"
    bin_rc=$?
    match="differs"
    if [ "$bin_rc" -eq "$zend_rc" ] && cmp -s "$zend_out" "$bin_out"; then
        match="matches"
    fi

    verdict="OK"
    if [ "$stubs" -ne 0 ] || [ "$match" != "matches" ]; then
        verdict="HOLLOW"
        failures=$((failures + 1))
    fi
    results+=("$(printf '%-12s %-7s %4ss %10s bytes  stubs=%-4s zend_rc=%s bin_rc=%s %s' \
        "$ext" "$verdict" "$wall" "$size" "$stubs" "$zend_rc" "$bin_rc" "$match")")
done

printf '%s\n' "${results[@]}"
echo

if [ "$failures" -eq 0 ]; then
    echo "spine-chunk-probe: all ${#EXTS[@]} chunk(s) compiled with every call bound — split-TU is UNBLOCKED."
    echo "  Next step is linking two chunks and exercising a cross-chunk call at runtime; each half"
    echo "  compiling cleanly is necessary, not sufficient."
    exit 0
fi

echo "spine-chunk-probe: ${failures} of ${#EXTS[@]} chunk(s) failed — split-TU still blocked."
echo "  HOLLOW means the chunk compiled but cross-chunk calls were lowered to a silent null"
echo "  (#579, #24227) — the binary runs and does the wrong thing, which is worse than not building."
exit 1
