<?php

declare(strict_types=1);

/**
 * Sync ext/<name>/ext.json + docs/extensions.md from the live extension tree (#36204 / #23480).
 *
 * Each manifest is the per-extension source of truth for name, load_order, depends, default_enabled,
 * policy_env, host_libs, and backends. script/generate-extension-registry.php reads these to emit
 * lib/ExtensionRegistry.php. Policy advertisement classes stay for now — folding them is a
 * follow-up once every surface reads policy_env from the manifest.
 *
 * Usage:
 *   php script/sync-extension-manifests.php           # write manifests + docs/extensions.md
 *   php script/sync-extension-manifests.php --check   # fail if out of date
 */

$root = dirname(__DIR__);
$check = in_array('--check', $argv, true);

$registryPath = $root.'/lib/ExtensionRegistry.php';
$order = [];
if (is_file($registryPath)
    && preg_match_all(
        '/new \\\\PHPCompiler\\\\ext\\\\([A-Za-z0-9_]+)\\\\Module\\(\\)/',
        (string) file_get_contents($registryPath),
        $rm
    )
) {
    $order = $rm[1];
}
if ([] === $order) {
    fwrite(STDERR, "sync-extension-manifests: could not parse lib/ExtensionRegistry.php\n");
    exit(2);
}

$dirs = [];
foreach (glob($root.'/ext/*/Module.php') ?: [] as $path) {
    $dirs[] = basename(dirname($path));
}
sort($dirs);

$missingFromRegistry = array_values(array_diff($dirs, $order));
$missingFromTree = array_values(array_diff($order, $dirs));
if ([] !== $missingFromTree) {
    fwrite(STDERR, 'sync-extension-manifests: registry names missing Module.php: '
        .implode(', ', $missingFromTree)."\n");
    exit(2);
}
// Directories not yet in the registry still get a manifest (append after current order).
$fullOrder = array_values(array_merge($order, $missingFromRegistry));

/**
 * @return list<string>
 */
function ext_declared_deps(string $moduleSrc): array
{
    if (!preg_match('/function getExtensionDependencies\(\): array\s*\{\s*return \[(.*?)\];/s', $moduleSrc, $dm)) {
        return [];
    }
    if (!preg_match_all("/'([^']+)'/", $dm[1], $names)) {
        return [];
    }

    return array_values(array_unique(array_map('strtolower', $names[1])));
}

/**
 * @return list<string>
 */
function ext_policy_env(string $extDir): array
{
    $envs = [];
    foreach (glob($extDir.'/*ExtensionPolicy.php') ?: [] as $policyPath) {
        $src = (string) file_get_contents($policyPath);
        if (preg_match_all("/PHP_COMPILER_ENABLE_[A-Z0-9_]+/", $src, $m)) {
            foreach ($m[0] as $name) {
                $envs[$name] = true;
            }
        }
    }

    return array_keys($envs);
}

/**
 * @return list<string>
 */
function ext_host_libs(string $moduleSrc): array
{
    // Best-effort: soname-ish string literals near FFI::cdef / dlopen comments.
    $libs = [];
    if (preg_match_all("/['\"](lib[a-zA-Z0-9_.+-]+\\.so(?:\\.[0-9]+)?)['\"]/", $moduleSrc, $m)) {
        foreach ($m[1] as $lib) {
            $libs[$lib] = true;
        }
    }

    return array_keys($libs);
}

$written = 0;
$drift = [];
$manifests = [];

foreach ($fullOrder as $index => $name) {
    $extDir = $root.'/ext/'.$name;
    $moduleSrc = (string) file_get_contents($extDir.'/Module.php');
    $manifest = [
        'name' => $name,
        'load_order' => $index,
        'depends' => ext_declared_deps($moduleSrc),
        'default_enabled' => true,
        'host_libs' => ext_host_libs($moduleSrc),
        'backends' => [
            'vm' => true,
            'jit' => true,
            'aot' => true,
        ],
        'provides' => [
            'functions' => [],
            'classes' => [],
        ],
        'policy_env' => ext_policy_env($extDir),
    ];
    $manifests[$name] = $manifest;

    $json = json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)."\n";
    $path = $extDir.'/ext.json';
    $current = is_file($path) ? (string) file_get_contents($path) : '';
    if ($current !== $json) {
        if ($check) {
            $drift[] = 'ext/'.$name.'/ext.json';
        } else {
            file_put_contents($path, $json);
            $written++;
        }
    }
}

$docLines = [
    '# Extensions',
    '',
    'Generated by `script/sync-extension-manifests.php` from `ext/<name>/ext.json` (#36204).',
    'Do not edit by hand — regenerate in the pinned Docker image.',
    '',
    '| name | load_order | depends | default_enabled | policy_env | host_libs |',
    '|---|---:|---|---|---|---|',
];
foreach ($fullOrder as $name) {
    $m = $manifests[$name];
    $docLines[] = sprintf(
        '| `%s` | %d | %s | %s | %s | %s |',
        $name,
        $m['load_order'],
        [] === $m['depends'] ? '—' : '`'.implode('`, `', $m['depends']).'`',
        $m['default_enabled'] ? 'yes' : 'no',
        [] === $m['policy_env'] ? '—' : '`'.implode('`, `', $m['policy_env']).'`',
        [] === $m['host_libs'] ? '—' : '`'.implode('`, `', $m['host_libs']).'`'
    );
}
$docLines[] = '';
$docLines[] = sprintf('%d extensions.', count($fullOrder));
$docLines[] = '';
$doc = implode("\n", $docLines);

$docsPath = $root.'/docs/extensions.md';
$docsCurrent = is_file($docsPath) ? (string) file_get_contents($docsPath) : '';
if ($docsCurrent !== $doc) {
    if ($check) {
        $drift[] = 'docs/extensions.md';
    } else {
        file_put_contents($docsPath, $doc);
        $written++;
    }
}

if ($check) {
    if ([] === $drift) {
        printf("sync-extension-manifests: ok — %d manifests + docs/extensions.md current\n", count($fullOrder));
        exit(0);
    }
    fwrite(STDERR, "sync-extension-manifests: OUT OF DATE:\n  - ".implode("\n  - ", $drift)."\n");
    fwrite(STDERR, "  run: php script/sync-extension-manifests.php\n");
    exit(1);
}

printf(
    "sync-extension-manifests: wrote %d file(s); %d extensions (registry order %d, tree-only %d)\n",
    $written,
    count($fullOrder),
    count($order),
    count($missingFromRegistry)
);
exit(0);
