#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Inventory patches/ divergences for docs/vendor-patches.md (#36229).
 *
 * Usage:
 *   php script/vendor-patches-inventory.php           # write docs/vendor-patches.md
 *   php script/vendor-patches-inventory.php --check   # exit 1 if doc is stale
 */

$root = dirname(__DIR__);
$patchDir = $root.'/patches';
$docPath = $root.'/docs/vendor-patches.md';
$check = in_array('--check', $argv, true);

$files = glob($patchDir.'/*.patch') ?: [];
sort($files);

$rows = [];
$hunkless = [];
$byPrefix = ['php-cfg' => 0, 'php-types' => 0, 'php-llvm' => 0, 'other' => 0];

foreach ($files as $path) {
    $name = basename($path);
    $body = (string) file_get_contents($path);
    $hunks = preg_match_all('/^@@/m', $body);
    if ($hunks === 0) {
        $hunkless[] = $name;
    }
    $targets = [];
    if (preg_match_all('/^\+\+\+\s+(?:b\/)?(\S+)/m', $body, $m)) {
        foreach ($m[1] as $t) {
            if ($t === '/dev/null') {
                continue;
            }
            $targets[$t] = true;
        }
    }
    $targetList = array_keys($targets);
    sort($targetList);
    $target = $targetList === [] ? '(overlay-only / no +++ path)' : implode(', ', $targetList);

    $reason = 'vendor divergence';
    if (preg_match('/^#\s*(.+)$/m', $body, $rm)) {
        $reason = trim($rm[1]);
        if (strlen($reason) > 120) {
            $reason = substr($reason, 0, 117).'...';
        }
    }

    if (str_starts_with($name, 'php-cfg-')) {
        $byPrefix['php-cfg']++;
    } elseif (str_starts_with($name, 'php-types-')) {
        $byPrefix['php-types']++;
    } elseif (str_starts_with($name, 'php-llvm-')) {
        $byPrefix['php-llvm']++;
    } else {
        $byPrefix['other']++;
    }

    $rows[] = [
        'name' => $name,
        'hunks' => $hunks,
        'target' => $target,
        'reason' => $reason,
    ];
}

$generated = date('Y-m-d');
$lines = [];
$lines[] = '# Vendor patches inventory';
$lines[] = '';
$lines[] = 'Generated by `php script/vendor-patches-inventory.php` on **'.$generated.'** (#36229).';
$lines[] = '';
$lines[] = 'Interim honesty rules (until php-cfg/php-types are forked):';
$lines[] = '';
$lines[] = '- Every `patches/*.patch` must contain at least one `@@` hunk (no comment-only stubs).';
$lines[] = '- `script/apply-patches.sh` applies `patch(1)` with **`-F0`** (no fuzz) and fails on partial applies.';
$lines[] = '- Overlay-only edits are invoked by name from `apply-patches.sh`; they do not leave empty `.patch` files.';
$lines[] = '- `./script/apply-patches.sh --verify-pristine` rejects hunkless stubs and applies the **full php-llvm patch stack in order** to `patches/pristine-snapshots/ircmaxell/php-llvm/` (composer.lock SHA in `ORIGIN`); a patch missing from the `apply_patch` list is a failure.';
$lines[] = '';
$lines[] = '| prefix | count |';
$lines[] = '|---|---|';
foreach ($byPrefix as $prefix => $count) {
    $lines[] = '| `'.$prefix.'` | '.$count.' |';
}
$lines[] = '| **total** | '.count($rows).' |';
$lines[] = '';
$lines[] = '| patch | hunks | primary target(s) | note |';
$lines[] = '|---|---|---|---|';
foreach ($rows as $row) {
    $note = str_replace('|', '\\|', $row['reason']);
    $target = str_replace('|', '\\|', $row['target']);
    $lines[] = '| `'.$row['name'].'` | '.$row['hunks'].' | `'.$target.'` | '.$note.' |';
}
$lines[] = '';

$doc = implode("\n", $lines);

if ($hunkless !== []) {
    fwrite(STDERR, "vendor-patches-inventory: hunkless stubs still present:\n  ".implode("\n  ", $hunkless)."\n");
    if (!$check) {
        // Still write the doc so the failure is visible in the table.
        file_put_contents($docPath, $doc);
    }
    exit(1);
}

if ($check) {
    if (!is_readable($docPath)) {
        fwrite(STDERR, "vendor-patches-inventory: missing {$docPath} — run without --check\n");
        exit(1);
    }
    $existing = (string) file_get_contents($docPath);
    // Ignore the generated date line for staleness (regen churn).
    $norm = static function (string $s): string {
        return preg_replace('/Generated by `php script\/vendor-patches-inventory\.php` on \*\*[0-9-]+\*\*/', 'Generated by DATE', $s) ?? $s;
    };
    if ($norm($existing) !== $norm($doc)) {
        fwrite(STDERR, "vendor-patches-inventory: docs/vendor-patches.md is stale — regenerate\n");
        exit(1);
    }
    fwrite(STDOUT, "vendor-patches-inventory: OK (".count($rows)." patches)\n");
    exit(0);
}

file_put_contents($docPath, $doc);
fwrite(STDOUT, "Wrote {$docPath} (".count($rows)." patches)\n");
exit(0);
