<?php
declare(strict_types=1);
$a = ["x", "y", "z"];
$b = array_merge($a, ["w"]);
$c = array_keys($b);
$d = array_values($b);
$e = array_combine(["k1", "k2"], ["v1", "v2"]);
$f = array_flip($e);
$g = array_reverse($d);
array_push($g, "tail");
$h = array_pop($g);
array_shift($f);
array_unshift($f, "head");
$i = array_sum([1, 2, 3]);
$j = array_product([2, 3]);
$k = array_unique(["a", "a", "b"]);
$l = array_values(array_merge(["ok"], []));
$m = count($k);
sort($l);
define("BOOT_CONST", 7);
$n = defined("BOOT_CONST") ? BOOT_CONST : 0;
$o = compact("a", "b");
$p = ["foo" => 1, "bar" => 2];
extract($p);
echo (string) count($c);
echo (string) $m;
echo (string) $i;
echo (string) $n;
echo isset($foo) ? "1" : "0";
