<?php

declare(strict_types=1);

namespace PHPCompiler;

use PHPUnit\Framework\TestCase;

/** @group aot-lint */
final class BootstrapSelfhostBundleTest extends TestCase
{
    private static string $root;

    /** @var list<string> */
    private const LIB_SPINE_SMOKE_NEW_UNITS = [
        'lib/JIT/Builtin/Type.php',
        'lib/JIT/Builtin/Type/String_.php',
        'lib/Doctor.php',
        'lib/Cli/InvokeCwd.php',
        'lib/Cli/PhpcBuild.php',
        'lib/BuiltinParamNames.php',
        'lib/VM/NamedArgs.php',
        'lib/VM/Builtin/VmClassMethod.php',
        'lib/VM/WeakRefSupport.php',
        'lib/VM/InterfaceCheck.php',
        'lib/VM/ClassReadonly.php',
        'lib/VM/Builtin/WeakMapConstruct.php',
        'lib/VM/Builtin/WeakMapCount.php',
        'lib/VM/Builtin/WeakMapOffsetExists.php',
        'lib/VM/Builtin/WeakMapOffsetGet.php',
        'lib/VM/Builtin/WeakMapOffsetSet.php',
        'lib/VM/Builtin/WeakMapOffsetUnset.php',
        'lib/VM/Builtin/WeakReferenceConstruct.php',
        'lib/VM/Builtin/WeakReferenceCreate.php',
        'lib/VM/Builtin/WeakReferenceGet.php',
        'lib/VM/BuiltinClasses.php',
        'ext/types/is_type.php',
        'ext/types/strlen.php',
        'ext/types/mb_strlen.php',
        'ext/types/JitMbStrlen.php',
        'ext/types/Module.php',
        'lib/Cli/PhpcInit.php',
        'lib/Cli/PhpcRun.php',
        'lib/Web/CgiAotDriver.php',
        'lib/Web/CgiDriver.php',
        'lib/Web/ProjectDeploy.php',
        'lib/AOT/ProjectGraph.php',
        'lib/Web/DevServer.php',
        'lib/Web/ManifestValidator.php',
        'lib/Web/Params.php',
        'lib/Web/ProjectAutoload.php',
        'lib/Web/ProjectBootstrap.php',
        'lib/Web/ProjectManifest.php',
        'lib/Web/ResponseContext.php',
        'lib/JIT/Builtin/CallArgv.php',
        'lib/JIT/Builtin/IniSet.php',
        'lib/JIT/Builtin/SessionId.php',
        'lib/JIT/Builtin/SessionName.php',
        'lib/JIT/Builtin/StringFunctionExists.php',
        'lib/JIT/Builtin/StringHttpBuildQuery.php',
        'lib/JIT/Builtin/StringSerialize.php',
        'lib/JIT/Builtin/StringSuperglobalName.php',
        'lib/JIT/ErrorHandlerCallbackPolicy.php',
        'lib/JIT/UsortCallbackPolicy.php',
        'lib/JIT/PregReplaceCallbackPolicy.php',
        'lib/JIT/ArrayReduceCallbackPolicy.php',
        'lib/JIT/ArrayMapCallbackPolicy.php',
        'lib/JIT/TypeCheck.php',
        'lib/JIT/ReflectionBuiltinHelper.php',
        'lib/JIT/ArrayBuiltinHelper.php',
        'lib/JIT/UnsetHelper.php',
        'lib/JIT/VarFetchHelper.php',
        'lib/JIT/Builtin/Type/HashTable.php',
        'lib/JIT/Builtin/Type/Object_.php',
        'lib/JIT/Builtin/StringParseStr.php',
        'lib/JIT/Builtin/StringPregMatch.php',
        'lib/JIT/Builtin/StringUnserialize.php',
        'lib/JIT/Builtin/StringUrldecode.php',
        'ext/standard/JitAddslashes.php',
        'ext/standard/JitBase64Encode.php',
        'ext/standard/JitBin2hex.php',
        'ext/standard/JitChunkSplit.php',
        'ext/standard/JitCrc32.php',
        'ext/standard/JitExplode.php',
        'ext/standard/JitChmod.php',
        'ext/standard/JitCopy.php',
        'ext/standard/JitDate.php',
        'ext/standard/JitImplode.php',
        'ext/standard/JitNl2br.php',
        'ext/standard/JitPregQuote.php',
        'ext/standard/JitQuotemeta.php',
        'ext/standard/JitStrRot13.php',
        'ext/standard/JitSessionId.php',
        'ext/standard/JitSessionName.php',
        'ext/standard/JitChdir.php',
        'ext/standard/JitClassExists.php',
        'ext/standard/JitClearstatcache.php',
        'ext/standard/JitDeployPath.php',
        'ext/standard/JitEnumExists.php',
        'ext/standard/JitEnv.php',
        'ext/standard/JitFclose.php',
        'ext/standard/JitFeof.php',
        'ext/standard/JitFgetc.php',
        'ext/standard/JitFgetcsv.php',
        'ext/standard/JitFgets.php',
        'ext/standard/JitFopen.php',
        'ext/standard/JitFpassthru.php',
        'ext/standard/JitFputcsv.php',
        'ext/standard/JitFread.php',
        'ext/standard/JitFseek.php',
        'ext/standard/JitFileGetContents.php',
        'ext/standard/JitFilter.php',
        'ext/standard/JitFunctionExists.php',
        'ext/standard/JitGetcwd.php',
        'ext/standard/JitHash.php',
        'ext/standard/JitHex2bin.php',
        'ext/standard/JitHtmlspecialchars.php',
        'ext/standard/JitIni.php',
        'ext/standard/JitJsonDecode.php',
        'ext/standard/JitJsonEncode.php',
        'ext/standard/JitJsonLastError.php',
        'ext/standard/JitNumberFormat.php',
        'ext/standard/JitPregMatch.php',
        'ext/standard/JitRealpath.php',
        'ext/standard/JitSerialize.php',
        'ext/standard/JitSprintf.php',
        'ext/standard/JitStrPad.php',
        'ext/standard/JitStrRepeat.php',
        'ext/standard/JitStrReplace.php',
        'ext/standard/JitStrShuffle.php',
        'ext/standard/JitStrSplit.php',
        'ext/standard/JitStringConcat.php',
        'ext/standard/JitStringIndex.php',
        'ext/standard/JitStripTags.php',
        'ext/standard/JitStripslashes.php',
        'ext/standard/JitStrpbrk.php',
        'ext/standard/JitStrpos.php',
        'ext/standard/JitStrrchr.php',
        'ext/standard/JitStrrpos.php',
        'ext/standard/JitStrstr.php',
        'ext/standard/JitSubstrCount.php',
        'ext/standard/JitStrtr.php',
        'ext/standard/JitSuperglobalName.php',
        'ext/standard/JitTempnam.php',
        'ext/standard/JitUnserialize.php',
        'ext/standard/JitUrlencode.php',
        'ext/standard/JitWordwrap.php',
        'ext/standard/JitFflush.php',
        'ext/standard/JitFilePutContents.php',
        'ext/standard/JitFilemtime.php',
        'ext/standard/JitFileperms.php',
        'ext/standard/JitFilesize.php',
        'ext/standard/JitFiletype.php',
        'ext/standard/JitFsGlob.php',
        'ext/standard/JitFtell.php',
        'ext/standard/JitFwrite.php',
        'ext/standard/JitMkdir.php',
        'ext/standard/JitPath.php',
        'ext/standard/JitPathinfo.php',
        'ext/standard/JitReadfile.php',
        'ext/standard/JitReadlink.php',
        'ext/standard/JitRename.php',
        'ext/standard/JitRequestBody.php',
        'ext/standard/JitRmdir.php',
        'ext/standard/JitShellExec.php',
        'ext/standard/JitStat.php',
        'ext/standard/JitStatArray.php',
        'ext/standard/JitSysGetTempDir.php',
        'ext/standard/JitTouch.php',
        'ext/standard/JitUnlink.php',
        'ext/standard/JitWebParams.php',
        'ext/standard/JitBase64Decode.php',
        'ext/standard/JitFuncArgs.php',
        'ext/standard/JitGetObjectVars.php',
        'ext/standard/JitGetallheaders.php',
        'ext/standard/JitHttpBuildQuery.php',
        'ext/standard/JitHttpResponseCode.php',
        'ext/standard/JitInterfaceExists.php',
        'ext/standard/JitParseStr.php',
        'ext/standard/JitParseUrl.php',
        'ext/standard/JitPendingHeaders.php',
        'ext/standard/JitPregGrep.php',
        'ext/standard/JitPregLastError.php',
        'ext/standard/JitPregMatchAll.php',
        'ext/standard/JitPregReplace.php',
        'ext/standard/JitPregReplaceCallback.php',
        'ext/standard/JitPregSplit.php',
        'ext/standard/JitPropertyExists.php',
        'ext/standard/JitSetcookie.php',
        'ext/standard/JitSleep.php',
        'ext/standard/JitTraitExists.php',
        'ext/standard/Module.php',
        'lib/Lint/SwitchDetector.php',
        'ext/standard/VmCrc32.php',
        'ext/standard/VmDate.php',
        'ext/standard/VmErrorHandler.php',
        'ext/standard/VmExit.php',
        'ext/standard/VmHttpBuildQuery.php',
        'ext/standard/VmInternalCall.php',
        'ext/standard/VmInternalCompare.php',
        'ext/standard/VmJson.php',
        'ext/standard/VmNumberFormat.php',
        'ext/standard/VmPack.php',
        'ext/standard/VmParseStr.php',
        'ext/standard/VmReflection.php',
        'ext/standard/VmScope.php',
        'ext/standard/VmSprintf.php',
        'ext/standard/VmStreamContext.php',
        'ext/standard/VmUserCall.php',
        'ext/standard/VmDebugBacktrace.php',
        'ext/standard/VmSerialize.php',
        'ext/standard/filter_input.php',
        'ext/standard/filter_var.php',
        'ext/standard/crc32.php',
        'ext/standard/hash_.php',
        'ext/standard/hash_hmac.php',
        'ext/standard/json_decode.php',
        'ext/standard/json_encode.php',
        'ext/standard/json_last_error_.php',
        'ext/standard/serialize.php',
        'ext/standard/unserialize.php',
        'ext/standard/class_exists_.php',
        'ext/standard/function_exists.php',
        'ext/standard/http_build_query.php',
        'ext/standard/floatval.php',
        'ext/standard/hex2bin.php',
        'ext/standard/addslashes.php',
        'ext/standard/stripslashes.php',
        'ext/standard/bin2hex.php',
        'ext/standard/doubleval.php',
        'ext/standard/pi.php',
        'lib/JIT/RuntimeInitVmContext.php',
        'ext/standard/parse_url.php',
        'ext/standard/parse_str.php',
        'ext/standard/abs.php',
        'ext/standard/array_chunk.php',
        'ext/standard/array_column.php',
        'ext/standard/array_map.php',
        'ext/standard/array_merge.php',
        'ext/standard/array_count.php',
        'ext/standard/array_diff.php',
        'ext/standard/array_fill.php',
        'ext/standard/array_flip.php',
        'ext/standard/array_key_exists.php',
        'ext/standard/array_keys.php',
        'ext/standard/array_intersect.php',
        'ext/standard/array_push.php',
        'ext/standard/array_product.php',
        'ext/standard/array_replace.php',
        'ext/standard/array_reverse.php',
        'ext/standard/array_slice.php',
        'ext/standard/array_splice.php',
        'ext/standard/array_sum.php',
        'ext/standard/array_unique.php',
        'ext/standard/array_unshift.php',
        'ext/standard/array_values.php',
        'ext/standard/atan2.php',
        'ext/standard/base64_decode.php',
        'ext/standard/base64_encode.php',
        'ext/standard/basename.php',
        'ext/standard/bindec.php',
        'ext/standard/chunk_split.php',
        'ext/standard/explode.php',
        'ext/standard/htmlspecialchars.php',
        'ext/standard/implode.php',
        'ext/standard/lcfirst.php',
        'ext/standard/nl2br.php',
        'ext/standard/number_format.php',
        'ext/standard/preg_replace.php',
        'ext/standard/quotemeta.php',
        'ext/standard/rawurldecode.php',
        'ext/standard/rawurlencode.php',
        'ext/standard/sprintf_.php',
        'ext/standard/str_contains.php',
        'ext/standard/str_ends_with.php',
        'ext/standard/str_pad.php',
        'ext/standard/str_repeat.php',
        'ext/standard/str_replace.php',
        'ext/standard/str_rot13.php',
        'ext/standard/str_shuffle.php',
        'ext/standard/str_split.php',
        'ext/standard/str_starts_with.php',
        'ext/standard/strcasecmp.php',
        'ext/standard/strchr.php',
        'ext/standard/strcmp.php',
        'ext/standard/strcspn.php',
        'ext/standard/string_ltrim.php',
        'ext/standard/string_rtrim.php',
        'ext/standard/string_trim.php',
        'ext/standard/strip_tags.php',
        'ext/standard/stripos.php',
        'ext/standard/stristr.php',
        'ext/standard/strncasecmp.php',
        'ext/standard/strncmp.php',
        'ext/standard/strpbrk.php',
        'ext/standard/strpos.php',
        'ext/standard/strrchr.php',
        'ext/standard/strrev.php',
        'ext/standard/strrpos.php',
        'ext/standard/strspn.php',
        'ext/standard/strstr.php',
        'ext/standard/strtolower.php',
        'ext/standard/strtoupper.php',
        'ext/standard/strtr.php',
        'ext/standard/strval.php',
        'ext/standard/substr.php',
        'ext/standard/substr_count.php',
        'ext/standard/ucfirst.php',
        'ext/standard/ucwords.php',
        'ext/standard/urldecode.php',
        'ext/standard/urlencode.php',
        'ext/standard/wordwrap.php',
        'src/llvm-env.php',
    ];

    public static function setUpBeforeClass(): void
    {
        self::$root = dirname(__DIR__, 2);
    }

    public function testCompilerMinimalBundleUnitCount(): void
    {
        $entry = self::$root.'/test/selfhost/compiler_minimal/main.php';
        $this->assertFileExists($entry);
        $count = substr_count((string) file_get_contents($entry), 'require_once __DIR__');
        $this->assertSame(108, $count);
    }

    public function testCompilerLibSpineSmokeBundleUnitCountAndKeyUnits(): void
    {
        $entry = self::$root.'/test/selfhost/compiler_lib_spine_smoke/main.php';
        $this->assertFileExists($entry);
        $contents = (string) file_get_contents($entry);
        $count = substr_count($contents, 'require_once __DIR__');
                $this->assertSame(410, $count, '108 compiler_minimal units + 302 M2 spine units (#1743 llvm-env); array_pop/shift/search + preg/array_combine wrappers skipped (AOT types); Vm* deferred #1467');
        foreach (self::LIB_SPINE_SMOKE_NEW_UNITS as $unit) {
            $this->assertStringContainsString(
                "require_once __DIR__.'/../../../{$unit}';",
                $contents,
                "missing {$unit}"
            );
        }
    }

    public function testCompilerLibSpineSmokePassesAotLint(): void
    {
        $entry = self::$root.'/test/selfhost/compiler_lib_spine_smoke/main.php';
        $prefix = LlvmToolchain::envPrefix(self::$root);
        $cmd = implode(' ', array_map('escapeshellarg', [
            ...$prefix,
            'php',
            self::$root.'/bin/compile.php',
            '-l',
            $entry,
        ])).' 2>&1';
        exec($cmd, $lines, $exitCode);
        $this->assertSame(0, $exitCode, implode("\n", $lines));
    }
}
