<?php

declare(strict_types=1);

namespace PHPCompiler;

use PHPUnit\Framework\TestCase;

/** @group aot-lint */
final class BootstrapSelfhostBundleTest extends TestCase
{
    private static string $root;

    /** @var list<string> */
    private const LIB_SPINE_SMOKE_NEW_UNITS = [
        'ext/standard/PhpinfoJitHelper.php',
        'lib/JIT/JitArrayUserSetOps.php',
        'lib/JIT/Builtin/CastArrayRuntime.php',
        'lib/JIT/Builtin/VarFetchRuntime.php',
        'lib/JIT/Builtin/CastArrayValueBoxJit.php',
        'lib/JIT/Builtin/CastObjectFromHashtableJit.php',
        'lib/JIT/Builtin/CastObjectValueBoxJit.php',
        'lib/JIT/CastArrayShared.php',
        'lib/VM/CastJitHelper.php',
        'lib/VM/LateStaticBinding.php',
        'lib/VM/LateStaticJitHelper.php',
        'lib/JIT/Builtin/LateStaticBindingGlobals.php',
        'lib/JIT/Builtin/LateStaticBindingRuntime.php',
        'lib/VM/InOperatorJitHelper.php',
        'lib/VM/InstanceOfJitHelper.php',
        'ext/standard/func_get_arg.php',
        'lib/JIT/Builtin/Type/ObjectExitStatusLlvm.php',
        'lib/VM/VmArrayAccess.php',
        'lib/VM/VmBoundMethodCallable.php',
        'lib/VM/VmIteratorProtocol.php',
        'lib/VM/VmObjectPropertyForeach.php',
        'lib/VM/VmVarFetch.php',
        'lib/VM/VmVarFetchJitHelper.php',
        'lib/VM/VmFromCallable.php',
        'lib/VM/VmClosure.php',
        'lib/JIT/Builtin/IniGet.php',
        'lib/JIT/Builtin/Type.php',
        'lib/JIT/Builtin/Type/String_.php',
        'lib/Doctor.php',
        'lib/Cli/InvokeCwd.php',
        'lib/Cli/PhpcBuild.php',
        'lib/BuiltinParamNames.php',
        'lib/VM/NamedArgs.php',
        'lib/VM/Builtin/VmClassMethod.php',
        'ext/standard/StreamLibcHandleJitHelper.php',
        'ext/standard/StreamLifecycleJitHelper.php',
        'ext/standard/JitStreamLibcHandleKernel.php',
        'ext/standard/JitStreamLifecycleKernel.php',
        'ext/standard/JitStreamCapsKernel.php',
        'ext/standard/JitStreamBufferKernel.php',
        'ext/standard/JitStreamModeKernel.php',
        'ext/standard/JitEnvLocalKernel.php',
        'ext/standard/JitStreamContextKernel.php',
        'ext/standard/JitStatPathKernel.php',
        'ext/standard/JitTriggerErrorKernel.php',
        'ext/standard/JitProgressNoteKernel.php',
        'ext/standard/JitSessionStorageKernel.php',
        'ext/standard/JitSessionLifecycleKernel.php',
        'lib/JIT/Builtin/StreamLibcHandleRuntime.php',
        'lib/JIT/Builtin/StreamLifecycleRuntime.php',
        'lib/JIT/Builtin/StreamCapsRuntime.php',
        'lib/JIT/Builtin/StreamBufferRuntime.php',
        'lib/JIT/Builtin/StreamModeRuntime.php',
        'lib/JIT/Builtin/EnvLocalRuntime.php',
        'lib/JIT/Builtin/StreamContextRuntime.php',
        'lib/VM/WeakRefSupport.php',
        'lib/VM/InterfaceCheck.php',
        'lib/VM/ClassReadonly.php',
        'lib/VM/Builtin/WeakMapConstruct.php',
        'lib/VM/Builtin/WeakMapCount.php',
        'lib/VM/Builtin/WeakMapGetIterator.php',
        'lib/VM/Builtin/WeakMapOffsetExists.php',
        'lib/VM/Builtin/WeakMapOffsetGet.php',
        'lib/VM/Builtin/WeakMapOffsetSet.php',
        'lib/VM/Builtin/WeakMapOffsetUnset.php',
        'lib/VM/WeakMapInternalIteratorHandler.php',
        'lib/VM/Builtin/WeakReferenceConstruct.php',
        'lib/VM/Builtin/WeakReferenceCreate.php',
        'lib/VM/Builtin/WeakReferenceGet.php',
        'lib/VM/BuiltinClasses.php',
        'ext/types/is_type.php',
        'ext/types/strlen.php',
        'ext/mbstring/Module.php',
        'ext/mbstring/mb_strlen.php',
        'ext/mbstring/JitMbStrlen.php',
        'ext/standard/Utf8JitHelper.php',
        'ext/standard/HrtimeJitHelper.php',
        'ext/standard/GetrusageJitHelper.php',
        'ext/standard/SleepJitHelper.php',
        'ext/ctype/CtypeJitHelper.php',
        'lib/JIT/Builtin/CtypeRuntime.php',
        'lib/JIT/Builtin/StringUtf8StrlenJit.php',
        'lib/JIT/Builtin/StringUtf8ValidJit.php',
        'lib/JIT/Builtin/StringUtf8Runtime.php',
        'lib/JIT/Builtin/StringHrtimeRuntime.php',
        'lib/JIT/Builtin/StringGetrusageRuntime.php',
        'ext/types/Module.php',
        'lib/Cli/PhpcInit.php',
        'lib/Cli/PhpcRun.php',
        'lib/Web/CgiAotDriver.php',
        'lib/Web/CgiDriver.php',
        'lib/Web/ProjectDeploy.php',
        'lib/AOT/ProjectGraph.php',
        'lib/Ast/GroupUseStripper.php',
        'lib/Ast/GeneratorYieldSourceMarker.php',
        'lib/Web/DevServer.php',
        'lib/Web/ManifestValidator.php',
        'lib/Web/Params.php',
        'lib/Web/ProjectAutoload.php',
        'lib/Web/ProjectBootstrap.php',
        'lib/Web/ProjectManifest.php',
        'lib/Web/ResponseContext.php',
        'lib/JIT/Builtin/CallArgv.php',
        'lib/JIT/Builtin/IniSet.php',
        'lib/JIT/Builtin/SessionId.php',
        'lib/JIT/Builtin/SessionName.php',
        'lib/JIT/Builtin/SessionStart.php',
        'lib/JIT/Builtin/SessionWriteClose.php',
        'ext/standard/BuiltinRegistry.php',
        'lib/JIT/Builtin/FunctionExistsRuntime.php',
        'lib/JIT/Builtin/StringFunctionExists.php',
        'lib/JIT/Builtin/StringHttpBuildQuery.php',
        'lib/JIT/Builtin/StringSerialize.php',
        'lib/JIT/Builtin/StringSuperglobalName.php',
        'lib/JIT/Builtin/SuperglobalNameRuntime.php',
        'ext/standard/SuperglobalNames.php',
        'lib/JIT/ErrorHandlerCallbackPolicy.php',
        'lib/JIT/UsortCallbackPolicy.php',
        'lib/JIT/PregReplaceCallbackPolicy.php',
        'lib/JIT/ArrayReduceCallbackPolicy.php',
        'lib/JIT/ArrayMapCallbackPolicy.php',
        'lib/JIT/TypeCheck.php',
        'lib/JIT/ReflectionBuiltinHelper.php',
        'lib/JIT/ArrayBuiltinHelper.php',
        'lib/JIT/UnsetHelper.php',
        'lib/JIT/VarFetchHelper.php',
        'lib/JIT/Builtin/Type/HashTable.php',
        'lib/JIT/Builtin/Type/Object_.php',
        'lib/JIT/Builtin/StringParseStr.php',
        'lib/JIT/Builtin/StringPregMatch.php',
        'ext/standard/PregJitHelper.php',
        'lib/JIT/Builtin/StringUnserialize.php',
        'lib/JIT/Builtin/StringUrldecode.php',
        'ext/standard/AddslashesJitHelper.php',
        'ext/standard/Base64JitHelper.php',
        'ext/standard/Bin2hexJitHelper.php',
        'ext/standard/ChunkSplitJitHelper.php',
        'ext/standard/VmChunkSplit.php',
        'ext/standard/QuotemetaJitHelper.php',
        'ext/standard/VmQuotemeta.php',
        'lib/JIT/Builtin/StringQuotemeta.php',
        'ext/standard/CountCharsJitHelper.php',
        'ext/standard/JitChunkSplit.php',
        'ext/standard/Crc32JitHelper.php',
        'ext/standard/JitCrc32.php',
        'ext/standard/JitExplode.php',
        'ext/standard/ChmodJitHelper.php',
        'ext/standard/JitChmod.php',
        'ext/standard/ChdirJitHelper.php',
        'ext/standard/JitChdir.php',
        'ext/standard/ChrootJitHelper.php',
        'ext/standard/JitChroot.php',
        'ext/standard/ProcNiceJitHelper.php',
        'ext/standard/JitProcNice.php',
        'ext/standard/GetmypidJitHelper.php',
        'ext/posix/PosixGetpidJitHelper.php',
        'lib/JIT/Builtin/PosixGetpidJit.php',
        'ext/posix/PosixGetuidJitHelper.php',
        'lib/JIT/Builtin/PosixGetuidJit.php',
        'ext/posix/JitPosixGetuidKernel.php',
        'ext/posix/PosixGeteuidJitHelper.php',
        'lib/JIT/Builtin/PosixGeteuidJit.php',
        'ext/posix/JitPosixGeteuidKernel.php',
        'ext/standard/JitGetmypidKernel.php',
        'ext/standard/GethostnameJitHelper.php',
        'ext/standard/JitGethostname.php',
        'ext/standard/JitGethostnameKernel.php',
        'ext/standard/JitCopy.php',
        'ext/standard/JitDate.php',
        'ext/standard/JitImplode.php',
        'ext/standard/Nl2brJitHelper.php',
        'ext/standard/PregQuoteJitHelper.php',
        'ext/standard/StrRot13JitHelper.php',
        'ext/standard/JitSessionId.php',
        'ext/standard/JitSessionName.php',
        'ext/standard/JitSessionStart.php',
        'ext/standard/JitSessionWriteClose.php',
        'ext/standard/JitClassAlias.php',
        'ext/standard/JitClassExists.php',
        'ext/standard/JitClearstatcache.php',
        'ext/standard/JitDeployPath.php',
        'ext/standard/JitEnumExists.php',
        'ext/standard/GetenvJitHelper.php',
        'ext/standard/JitEnv.php',
        'ext/standard/JitFclose.php',
        'ext/standard/JitFeof.php',
        'ext/standard/JitFgetc.php',
        'ext/standard/JitFgetcsv.php',
        'ext/standard/JitFgets.php',
        'ext/standard/JitFopen.php',
        'ext/standard/JitFpassthru.php',
        'ext/standard/JitFputcsv.php',
        'ext/standard/JitFread.php',
        'ext/standard/JitFseek.php',
        'ext/standard/JitFileGetContents.php',
        'ext/filter/JitFilter.php',
        'ext/standard/JitFunctionExists.php',
        'ext/standard/JitGetcwd.php',
        'ext/standard/JitHash.php',
        'ext/standard/Hex2binJitHelper.php',
        'ext/standard/LevenshteinJitHelper.php',
        'ext/standard/StrspnJitHelper.php',
        'ext/standard/SpnJitLowering.php',
        'ext/standard/JitHtmlspecialchars.php',
        'ext/standard/JitIni.php',
        'ext/standard/JitIniGetAll.php',
        'ext/standard/JitJsonDecode.php',
        'ext/standard/JitJsonEncode.php',
        'ext/standard/JitJsonLastError.php',
        'ext/standard/JitJsonLastErrorMsg.php',
        'ext/standard/JitNumberFormat.php',
        'ext/standard/JitPregMatch.php',
        'ext/standard/JitRealpath.php',
        'ext/standard/JitSerialize.php',
        'ext/standard/JitSprintf.php',
        'ext/standard/StrPadJitHelper.php',
        'ext/standard/StrRepeatJitHelper.php',
        'ext/standard/JitStrReplace.php',
        'ext/standard/StrReplaceJitHelper.php',
        'ext/standard/JitStrShuffle.php',
        'ext/standard/JitStrSplit.php',
        'ext/standard/JitStringConcat.php',
        'ext/standard/JitStringIndex.php',
        'ext/standard/JitStripTags.php',
        'ext/standard/StripslashesJitHelper.php',
        'ext/standard/JitStrpbrk.php',
        'ext/standard/StrContainsJitHelper.php',
        'ext/standard/StrposJitHelper.php',
        'ext/standard/StrstrJitHelper.php',
        'lib/JIT/Builtin/StringStrContains.php',
        'lib/JIT/Builtin/StringStrpos.php',
        'lib/JIT/Builtin/StringStrstr.php',
        'lib/JIT/Builtin/StringStrReplace.php',
        'ext/standard/JitStrrchr.php',
        'ext/standard/StrrposJitHelper.php',
        'ext/standard/JitStrstr.php',
        'ext/standard/SubstrCountJitHelper.php',
        'lib/JIT/Builtin/StringSubstrCount.php',
        'lib/JIT/Builtin/StringCountChars.php',
        'ext/standard/JitStrtr.php',
        'ext/standard/JitSuperglobalName.php',
        'ext/standard/JitTempnam.php',
        'ext/standard/JitTempnamKernel.php',
        'ext/standard/JitUnserialize.php',
        'ext/standard/UniqidJitHelper.php',
        'ext/standard/JitUrlencode.php',
        'ext/standard/VmWordwrap.php',
        'ext/standard/WordwrapJitHelper.php',
        'lib/JIT/Builtin/StringWordwrap.php',
        'lib/JIT/Builtin/StringBin2hex.php',
        'lib/JIT/Builtin/StringBase64Encode.php',
        'lib/JIT/Builtin/StringBase64Decode.php',
        'lib/JIT/Builtin/StringChdir.php',
        'lib/JIT/Builtin/StringChroot.php',
        'lib/JIT/Builtin/StringProcNice.php',
        'lib/JIT/Builtin/StringGethostname.php',
        'lib/JIT/Builtin/StringChunkSplit.php',
        'lib/JIT/Builtin/StringHex2bin.php',
        'lib/JIT/Builtin/StringLevenshtein.php',
        'lib/JIT/Builtin/StringStrspn.php',
        'lib/JIT/Builtin/StringStrrev.php',
        'lib/JIT/Builtin/StringStrPad.php',
        'lib/JIT/Builtin/StringStrRot13.php',
        'lib/JIT/Builtin/StringUniqid.php',
        'lib/JIT/Builtin/StringStrRepeat.php',
        'ext/standard/StrrevJitHelper.php',
        'ext/standard/UrldecodeJitHelper.php',
        'ext/standard/UrlencodeJitHelper.php',
        'ext/standard/JitFflush.php',
        'ext/standard/JitFilePutContents.php',
        'ext/standard/JitFilemtime.php',
        'ext/standard/JitFileowner.php',
        'ext/standard/JitFilegroup.php',
        'ext/standard/JitFileperms.php',
        'ext/standard/JitFilesize.php',
        'ext/standard/JitFiletype.php',
        'ext/standard/JitFsGlob.php',
        'ext/standard/JitFtell.php',
        'ext/standard/JitFwrite.php',
        'ext/standard/JitMkdir.php',
        'ext/standard/JitMoveUploadedFile.php',
        'ext/standard/JitPath.php',
        'ext/standard/JitPathinfo.php',
        'ext/standard/JitReadfile.php',
        'ext/standard/JitReadlink.php',
        'ext/standard/JitRename.php',
        'ext/standard/JitRequestBody.php',
        'ext/standard/JitRmdir.php',
        'ext/standard/JitShellExec.php',
        'ext/standard/JitStat.php',
        'ext/standard/JitStatArray.php',
        'ext/standard/JitSysGetTempDir.php',
        'ext/standard/JitSysGetloadavg.php',
        'ext/standard/JitTouch.php',
        'ext/standard/JitUnlink.php',
        'ext/standard/JitWebParams.php',
        'ext/standard/JitFuncArgs.php',
        'ext/standard/JitGetObjectVars.php',
        'ext/standard/JitGetallheaders.php',
        'ext/standard/JitHttpBuildQuery.php',
        'ext/standard/JitHttpResponseCode.php',
        'ext/standard/JitInterfaceExists.php',
        'ext/standard/JitParseStr.php',
        'ext/standard/JitParseUrl.php',
        'ext/standard/JitPendingHeaders.php',
        'ext/standard/JitPregGrep.php',
        'ext/standard/JitPregLastError.php',
        'ext/standard/JitPregMatchAll.php',
        'ext/standard/JitPregReplace.php',
        'ext/standard/JitPregReplaceCallback.php',
        'ext/standard/JitPregSplit.php',
        'ext/standard/JitPropertyExists.php',
        'ext/standard/JitSetcookie.php',
        'ext/standard/JitSleep.php',
        'ext/standard/JitTraitExists.php',
        'ext/standard/Module.php',
        'lib/Lint/SwitchDetector.php',
        'bin/vm.php',
        'ext/standard/VmCrc32.php',
        'ext/standard/VmDate.php',
        'ext/standard/VmErrorHandler.php',
        'ext/standard/VmExit.php',
        'ext/standard/VmHttpBuildQuery.php',
        'ext/standard/VmInternalCall.php',
        'ext/standard/VmInternalCompare.php',
        'ext/standard/VmJson.php',
        'ext/standard/VmJsonFormat.php',
        'ext/standard/VmJsonParser.php',
        'ext/standard/VmNumberFormat.php',
        'ext/standard/VmPack.php',
        'ext/standard/VmParseStr.php',
        'ext/standard/VmReflection.php',
        'ext/standard/VmScope.php',
        'ext/standard/VmSprintf.php',
        'ext/standard/VmStreamContext.php',
        'ext/standard/VmUserCall.php',
        'ext/standard/VmPregReplaceCallback.php',
        'ext/standard/VmDebugBacktrace.php',
        'ext/standard/VmSerialize.php',
        'ext/filter/filter_input.php',
        'ext/filter/filter_var.php',
        'ext/standard/crc32.php',
        'ext/standard/hash_.php',
        'ext/standard/hash_hmac.php',
        'ext/standard/json_decode.php',
        'ext/standard/json_encode.php',
        'ext/standard/json_validate.php',
        'ext/standard/json_last_error_.php',
        'ext/standard/json_last_error_msg_.php',
        'ext/standard/serialize.php',
        'ext/standard/unserialize.php',
        'ext/standard/class_exists_.php',
        'ext/standard/function_exists.php',
        'ext/standard/http_build_query.php',
        'ext/standard/floatval.php',
        'ext/standard/hex2bin.php',
        'ext/standard/addslashes.php',
        'ext/standard/stripslashes.php',
        'ext/standard/bin2hex.php',
        'ext/standard/doubleval.php',
        'ext/standard/pi.php',
        'lib/JIT/RuntimeInitVmContext.php',
        'ext/standard/parse_url.php',
        'ext/standard/parse_str.php',
        'ext/standard/abs.php',
        'ext/standard/array_chunk.php',
        'ext/standard/array_column.php',
        'ext/standard/array_map.php',
        'ext/standard/array_merge.php',
        'ext/standard/array_count.php',
        'ext/standard/array_diff.php',
        'ext/standard/array_fill.php',
        'ext/standard/array_flip.php',
        'ext/standard/array_key_exists.php',
        'ext/standard/array_keys.php',
        'ext/standard/array_intersect.php',
        'ext/standard/array_push.php',
        'ext/standard/array_product.php',
        'ext/standard/array_replace.php',
        'ext/standard/array_reverse.php',
        'ext/standard/array_slice.php',
        'ext/standard/array_splice.php',
        'ext/standard/array_sum.php',
        'ext/standard/array_unique.php',
        'ext/standard/array_unshift.php',
        'ext/standard/array_values.php',
        'ext/standard/atan2.php',
        'ext/standard/tan.php',
        'ext/standard/base64_decode.php',
        'ext/standard/base64_encode.php',
        'ext/standard/basename.php',
        'ext/standard/bindec.php',
        'ext/standard/boolval.php',
        'ext/standard/ceil.php',
        'ext/standard/cos.php',
        'ext/standard/decbin.php',
        'ext/standard/dechex.php',
        'ext/standard/decoct.php',
        'ext/standard/deg2rad.php',
        'ext/standard/exp.php',
        'ext/standard/floor.php',
        'ext/standard/fmod.php',
        'ext/standard/gettype.php',
        'ext/standard/intval.php',
        'ext/standard/is_finite.php',
        'ext/standard/is_infinite.php',
        'ext/standard/is_nan.php',
        'ext/standard/chunk_split.php',
        'ext/standard/explode.php',
        'ext/standard/htmlspecialchars.php',
        'ext/standard/implode.php',
        'ext/standard/lcfirst.php',
        'ext/standard/nl2br.php',
        'ext/standard/number_format.php',
        'ext/standard/preg_replace.php',
        'ext/standard/quotemeta.php',
        'ext/standard/rawurldecode.php',
        'ext/standard/rawurlencode.php',
        'ext/standard/sprintf_.php',
        'ext/standard/str_contains.php',
        'ext/standard/str_ends_with.php',
        'ext/standard/str_pad.php',
        'ext/standard/str_repeat.php',
        'ext/standard/str_replace.php',
        'ext/standard/str_rot13.php',
        'ext/standard/str_shuffle.php',
        'ext/standard/str_split.php',
        'ext/standard/str_starts_with.php',
        'ext/standard/strcasecmp.php',
        'ext/standard/strchr.php',
        'ext/standard/strcmp.php',
        'ext/standard/strcspn.php',
        'ext/standard/string_ltrim.php',
        'ext/standard/string_rtrim.php',
        'ext/standard/string_trim.php',
        'ext/standard/strip_tags.php',
        'ext/standard/stripos.php',
        'ext/standard/stristr.php',
        'ext/standard/strncasecmp.php',
        'ext/standard/strncmp.php',
        'ext/standard/strpbrk.php',
        'ext/standard/strpos.php',
        'ext/standard/strrchr.php',
        'ext/standard/strrev.php',
        'ext/standard/strrpos.php',
        'ext/standard/strspn.php',
        'ext/standard/strstr.php',
        'ext/standard/strtolower.php',
        'ext/standard/strtoupper.php',
        'ext/standard/strtr.php',
        'ext/standard/strval.php',
        'ext/standard/substr.php',
        'ext/standard/substr_count.php',
        'ext/standard/ucfirst.php',
        'ext/standard/UcwordsJitHelper.php',
        'ext/standard/ucwords.php',
        'ext/standard/urldecode.php',
        'ext/standard/urlencode.php',
        'ext/standard/var_dump.php',
        'ext/standard/web_int.php',
        'ext/standard/wordwrap.php',
        'ext/standard/VmFs.php',
        'ext/standard/VmFsGlob.php',
        'ext/filter/VmFilter.php',
        'ext/standard/VmHash.php',
        'ext/standard/VmHashNative.php',
        'ext/standard/VmPregNative.php',
        'ext/standard/VmSession.php',
        'ext/standard/SetcookieLine.php',
        'ext/standard/sqrt.php',
        'ext/standard/sin.php',
        'ext/standard/range.php',
        'ext/standard/fopen.php',
        'ext/standard/readfile.php',
        'ext/standard/stream_context_create.php',
        'ext/standard/pack.php',
        'ext/standard/date.php',
        'ext/standard/session_start.php',
        'ext/standard/VmSplAutoload.php',
        'ext/standard/uasort_.php',
        'ext/standard/uksort_.php',
        'ext/standard/usort_.php',
        'lib/JIT/Builtin/ReflectionEnumJitHelper.php',
        'lib/JIT/Call/ReflectionEnumConstruct.php',
        'lib/JIT/Call/ReflectionEnumGetCase.php',
        'lib/JIT/Call/ReflectionEnumGetCases.php',
        'lib/JIT/Call/ReflectionEnumGetName.php',
        'lib/JIT/Call/ReflectionEnumHasCase.php',
        'lib/JIT/Call/ReflectionEnumIsBacked.php',
        'lib/JIT/Call/ReflectionEnumUnitCaseGetName.php',
        'ext/standard/FstatJitHelper.php',
        'ext/standard/JsonDecodeJitHelper.php',
        'ext/standard/VmStreamFstat.php',
        'ext/standard/timezone_abbreviations_list.php',
        'lib/BuiltinTypeClassConstant.php',
        'lib/JIT/Builtin/StreamFstat.php',
        'lib/JIT/Builtin/StreamFstatRuntime.php',
        'lib/VM/Builtin/DateTimeZoneListAbbreviations.php',
        'lib/VM/Builtin/DateTimeZoneListIdentifiers.php',
        'ext/standard/JitRand.php',
        'ext/standard/LcgJitHelper.php',
        'ext/standard/RandJitHelper.php',
        'ext/standard/VmCombinedLcg.php',
        'ext/standard/VmMt19937.php',
        'ext/standard/getrandmax.php',
        'ext/standard/mt_getrandmax.php',
        'ext/standard/lcg_value.php',
        'ext/standard/mt_rand.php',
        'ext/standard/mt_srand.php',
        'ext/standard/rand_.php',
        'ext/standard/srand.php',
        'lib/JIT/Builtin/Lcg.php',
        'lib/JIT/Builtin/Rand.php',
        'lib/JIT/HashTableReadLlvm.php',
        'lib/JIT/HashTableWriteLlvm.php',
        'lib/VM/HashTableJitHelper.php',
        'ext/standard/ArrayReplaceJitHelper.php',
        'ext/standard/ArraySearchJitHelper.php',
        'lib/AsymmetricVisibilityRejector.php',
        'lib/PropertyHookSyntaxRejector.php',
        'lib/Ast/ListSpreadAssignSyntax.php',
        'lib/ListSpreadAssignSyntaxRejector.php',
        'lib/JIT/Builtin/ArrayReplaceRuntime.php',
        'lib/JIT/Builtin/ArraySearchRuntime.php',
    ];

    public static function setUpBeforeClass(): void
    {
        self::$root = dirname(__DIR__, 2);
    }

    public function testCompilerMinimalBundleUnitCount(): void
    {
        $entry = self::$root.'/test/selfhost/compiler_minimal/main.php';
        $this->assertFileExists($entry);
        $count = substr_count((string) file_get_contents($entry), 'require_once __DIR__');
        $this->assertSame(111, $count);
    }

    public function testCompilerLibSpineSmokeBundleUnitCountAndKeyUnits(): void
    {
        require_once self::$root.'/script/bootstrap-spine-count.php';
        $entry = self::$root.'/test/selfhost/compiler_lib_spine_smoke/main.php';
        $this->assertFileExists($entry);
        $contents = (string) file_get_contents($entry);
        $count = bootstrap_spine_counts(self::$root)['spine'];
        // Spine ratio 7410/7412 — 2 deferred still listed in coverage sync (#24115, #27103).
        $this->assertSame(7415, $count, 'M2 spine require_once units track Phase A inventory (#8559, #9234, #11629, #18550); coverage sync defers PregJitHelperThinAot (#24115) + NetworkServicesNameLookupThinAot (#27103)');
        foreach (self::LIB_SPINE_SMOKE_NEW_UNITS as $unit) {
            $this->assertStringContainsString(
                "require_once __DIR__.'/../../../{$unit}';",
                $contents,
                "missing {$unit}"
            );
        }
    }

    public function testCompilerLibSpineSmokeVmClassMethodBeforeExtenders(): void
    {
        $entry = self::$root.'/test/selfhost/compiler_lib_spine_smoke/main.php';
        $lines = file($entry, FILE_IGNORE_NEW_LINES) ?: [];
        $internalLine = null;
        $vmClassMethodLine = null;
        $firstExtenderLine = null;
        foreach ($lines as $i => $line) {
            if (!preg_match("#require_once __DIR__\\.'/\\.\\./\\.\\./\\.\\./([^']+)';#", $line, $m)) {
                continue;
            }
            $rel = $m[1];
            if ('lib/Func/Internal.php' === $rel) {
                $internalLine = $i + 1;
                continue;
            }
            if ('lib/VM/Builtin/VmClassMethod.php' === $rel) {
                $vmClassMethodLine = $i + 1;
                continue;
            }
            if (null !== $firstExtenderLine) {
                continue;
            }
            $abs = self::$root.'/'.$rel;
            if (!is_file($abs)) {
                continue;
            }
            $src = (string) file_get_contents($abs);
            if (str_contains($src, 'extends VmClassMethod')) {
                $firstExtenderLine = $i + 1;
            }
        }
        $this->assertNotNull($internalLine, 'Func/Internal.php must be in spine');
        $this->assertNotNull($vmClassMethodLine, 'VmClassMethod.php must be in spine');
        $this->assertLessThan(
            $vmClassMethodLine,
            $internalLine,
            'Func/Internal must load before VmClassMethod (base class for VmClassMethod extenders)'
        );
        if (null !== $firstExtenderLine) {
            $this->assertLessThan(
                $firstExtenderLine,
                $vmClassMethodLine,
                'VmClassMethod must load before first extends VmClassMethod unit'
            );
        }
    }

    public function testCompilerLibSpineSmokePassesAotLint(): void
    {
        $entry = self::$root.'/test/selfhost/compiler_lib_spine_smoke/main.php';
        $prefix = LlvmToolchain::envPrefix(self::$root);
        $cmd = implode(' ', array_map('escapeshellarg', [
            ...$prefix,
            'php',
            self::$root.'/bin/compile.php',
            '-l',
            $entry,
        ])).' 2>&1';
        exec($cmd, $lines, $exitCode);
        $this->assertSame(0, $exitCode, implode("\n", $lines));
    }
}
